/* Translation unit unit-0800bc48: 0x0800bc48 .. 0x0800bc70.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0800bc48.c"
