/* Translation unit unit-08004bd4: 0x08004bd4 .. 0x08004c6c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/08004bd4.c"
#include "../main/08004c1c.c"
