[workspace]

[package]
name = "build-full"
version = "0.1.0"
edition = "2021"

[dependencies]
canonical-json = { path = "../canonical-json" }
decomp-targets = { path = "../decomp-targets" }
serde_json = { version = "1", features = ["preserve_order"] }

[lib]
name = "build_full"
path = "src/lib.rs"

[[bin]]
name = "build-full"
path = "src/main.rs"
