[workspace]

[package]
name = "simple-resources"
version = "0.1.0"
edition = "2021"

[lib]
name = "simple_resources"
path = "src/lib.rs"

[[bin]]
name = "simple-resources"
path = "src/main.rs"

[dependencies]
export-asset = { path = "../export-asset" }
extract-resource = { path = "../extract-resource" }
import-asset = { path = "../import-asset" }
serde_json = { version = "1", features = ["preserve_order"] }
