/* Draft of PlayStoryScene, resource_3bf at 0x0200a7b0, built with
 * games/THE BROKEN SEAL/SRC/FIELD/RUNPA_JO/FORTRESS.H.
 * Remaining difference: it compiles 16 bytes short of the ROM's 0x8a4, and the
 * ROM loads scene 0xa3 from its literal pool as a link-time value.
 * The listing keeps these rows. */
#include "FORTRESS.H"
extern u8 MsgRunpaBackMoreGuess[];
extern u8 MsgRunpaDodonpaPulledLever[];
extern u8 MsgRunpaTimeEat[];

void Func_020057ec();
s32 Func_02007e76();
s32 Func_0200804e();
void Func_020080e6_a();
void Func_020080e6_b();
void Func_02008788_a();
void Func_02008788_b();

/* Runs one of two long fixed sequences (chosen by a status check), each
 * placing actors, panning/animating them, and running dialogue lines built
 * from a base text pointer plus a running line offset. */
void PlayStoryScene(void)
{

    s32 text_line;

    if (GameFlag_IsSet(769) != 0) {
        Func_020057ec();
    }
    GameFlag_Set(624);
    Event_Begin();
    if (GameFlag_IsSet(2370) != 0) {
        Actor_SetSpeed(ACTOR_PARTY_LEADER, 32768, 16384);
        Actor_WalkToAndWait(ACTOR_PARTY_LEADER, 456, 216);
        Actor_FaceActor(ACTOR_PARTY_LEADER, 12, 0);
        FieldScene_RunScene3bf_0200252c();
        Actor_ShowEmote(12, 256, 60);
        Actor_FaceDirection(12, 32768, 0);
        Actor_Jump(12, 4, 0);
        Actor_SetSpriteFlags(Func_02007e76(12), 1);
        Event_Wait(30);
        Actor_SetSpeed(ACTOR_IVAN, 45875, 22937);
        Value3(Engine_ActorWalkTo, 2, 464, 192);
        Actor_WaitForMove(ACTOR_IVAN);
        Event_Wait(30);
        Actor_FaceDirection(ACTOR_PARTY_LEADER, 16384, 0);
        Actor_FaceDirection(ACTOR_IVAN, 16384, 0);
        Actor_FaceDirection(ACTOR_GERALD, 16384, 0);
        Actor_FaceDirection(ACTOR_MIA, 16384, 0);
        Actor_SetPosition(13, 29884416, 20971520);
        Value2(Engine_CameraSetSpeed, 131072, 16384);
        text_line = (s32)MsgRunpaBackMoreGuess;
        Event_SetMessage(text_line);
        Event_ShowMessage(13, 0);
        Value3(Engine_ActorWalkTo, 13, 458, 272);
        Actor_WaitForMove(13);
        Value3(Engine_ActorFaceDirection, 13, 20480, 0);
        Event_Wait(40);
        Value3(ObjectMotion_OffsetPositionAndResetMotion, 13, -8, 8);
        Actor_WaitForMove(13);
        Event_Wait(60);
        Audio_PlayCue(155);
        Message_ShowCentered(text_line + 1, 1);
        Value3(ObjectMotion_OffsetPositionAndResetMotion, 13, 8, -8);
        FieldScene_RunScene3bf_020025f8();
        Event_Wait(120);
        Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
        Actor_StartRepeatedMotion(ACTOR_IVAN, 2);
        Actor_StartRepeatedMotion(ACTOR_GERALD, 2);
        Actor_StartRepeatedMotion(ACTOR_MIA, 2);
        Event_Wait(20);
        text_line += 2;
        FieldScene_RunScene3bf_02002718();
        Actor_FaceActor(13, ACTOR_PARTY_LEADER, 0);
        Event_SetMessage(text_line);
        Event_ShowMessage(13, 0);
        FieldScene_RunScene3bf_0200269c();
        SHARED_RECORD_FIELD_448 = 512;
        Event_Wait(1);
        do {
            gGameState.unknown_1f8[0x22b - 0x1f8] = 3;
        } while (0);
        Func_020080e6_a(0xa3, 4);
        Func_020080e6_b(98, 4);
    } else {
        Actor_SetAnimation(ACTOR_PARTY_LEADER, 1);
        Audio_PlayCue(17);
        Event_Wait(30);
        text_line = (s32)MsgRunpaTimeEat;
        Event_SetMessage(text_line);
        Event_ShowMessage(12, 0);
        Actor_FaceEachOther(ACTOR_PARTY_LEADER, 12, 0);
        Event_Wait(140);
        Actor_FaceDirection(12, 32768, 0);
        Actor_Jump(12, 4, 0);
        Actor_SetSpriteFlags(Func_0200804e(12), 1);
        Event_SetMessage(text_line + 1);
        Event_ShowMessage(12, 0);
        Actor_SetSpeed(ACTOR_PARTY_LEADER, 32768, 16384);
        Actor_WalkToAndWait(ACTOR_PARTY_LEADER, 456, 216);
        Actor_FaceActor(ACTOR_PARTY_LEADER, 12, 0);
        FieldScene_RunScene3bf_0200252c();
        Actor_SetSpeed(ACTOR_IVAN, 45875, 22937);
        Value3(Engine_ActorWalkTo, 2, 464, 192);
        Actor_WaitForMove(ACTOR_IVAN);
        Event_Wait(30);
        Event_SetMessage(text_line + 2);
        Event_ShowMessage(ACTOR_IVAN, 0);
        Value3(Engine_ActorShowEmote, 12, 256, 0);
        Event_Wait(110);
        Audio_PlayCue(60);
        Event_SetMessage(text_line + 3);
        Event_ShowMessage(12, 0);
        Event_Wait(30);
        Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
        Event_Wait(20);
        Actor_SetAnimation(ACTOR_IVAN, 1);
        Actor_StartRepeatedMotion(12, 1);
        Event_Wait(20);
        Actor_SetSpeed(12, 26214, 13107);
        Value3(Engine_ActorWalkTo, 12, 520, 208);
        Actor_WaitForMove(12);
        Actor_SetAnimation(12, 1);
        Event_Wait(20);
        Value3(Engine_ActorFaceDirection, 12, 45056, 0);
        Event_Wait(30);
        Value3(Engine_ActorFaceDirection, 12, 20480, 0);
        Event_Wait(30);
        Actor_FaceActor(12, ACTOR_IVAN, 0);
        Event_Wait(20);
        Event_SetMessage(text_line + 4);
        Event_ShowMessage(12, 0);
        Event_Wait(40);
        Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
        Event_Wait(20);
        Value3(Engine_ActorShowEmote, 12, 264, 0);
        Event_Wait(120);
        Event_SetMessage(text_line + 5);
        Event_ShowMessage(12, 0);
        Event_Wait(25);
        Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
        Event_Wait(30);
        Actor_SetAnimationAndWait(12, 3);
        Event_Wait(40);
        Value3(Engine_ActorWalkTo, 2, 480, 200);
        Actor_WaitForMove(ACTOR_IVAN);
        Actor_FaceEachOther(ACTOR_IVAN, 12, 0);
        Event_Wait(60);
        Event_SetMessage(text_line + 6);
        Event_ShowMessage(ACTOR_IVAN, 0);
        Event_Wait(20);
        Actor_SetAnimation(12, 4);
        Event_Wait(80);
        Event_SetMessage(text_line + 7);
        Event_ShowMessage(12, 0);
        Value3(Engine_ActorSetPosition, 13, 29884416, 20971520);
        Audio_PlayCue(19);
        Event_SetMessage(text_line + 8);
        Event_ShowMessage(13, 0);
        Actor_FaceActor(ACTOR_PARTY_LEADER, 13, 0);
        Actor_FaceActor(ACTOR_IVAN, 13, 0);
        Actor_FaceActor(ACTOR_GERALD, 13, 0);
        Event_Wait(5);
        Actor_FaceDirection(ACTOR_MIA, 16384, 0);
        Actor_FaceActor(12, 13, 0);
        Event_Wait(30);
        Audio_PlayCue(61);
        Camera_SetSpeed(131072, 16384);
        Camera_MoveToActor(13, 1);
        Camera_WaitForMove();
        Actor_SetSpeed(13, 52428, 26214);
        Actor_WalkTo(13, 456, 304);
        Camera_FollowActor(13, 1);
        Actor_WaitForMove(13);
        Camera_FollowActor(ACTOR_GERALD, 1);
        Actor_ShowEmote(ACTOR_PARTY_LEADER, 258, 0);
        Actor_ShowEmote(ACTOR_IVAN, 258, 0);
        Actor_ShowEmote(ACTOR_GERALD, 258, 0);
        Actor_ShowEmote(ACTOR_MIA, 258, 0);
        Value3(Engine_ActorShowEmote, 12, 258, 0);
        Event_Wait(60);
        Actor_FaceActor(12, 13, 0);
        Actor_StartRepeatedMotion(12, 2);
        Event_Wait(60);
        Event_SetMessage(text_line + 9);
        Event_ShowMessage(12, 0);
        Actor_FaceActor(13, 12, 0);
        Event_SetMessage(text_line + 10);
        Event_ShowMessage(13, 0);
        Event_Wait(60);
        Actor_FaceActor(13, ACTOR_IVAN, 0);
        Event_Wait(30);
        Event_SetMessage(text_line + 11);
        Event_ShowMessage(13, 0);
        Actor_FaceEachOther(ACTOR_MIA, ACTOR_IVAN, 0);
        Actor_FaceEachOther(ACTOR_PARTY_LEADER, ACTOR_GERALD, 0);
        Event_Wait(60);
        Actor_FaceActor(ACTOR_PARTY_LEADER, 13, 0);
        Actor_FaceActor(ACTOR_IVAN, 13, 0);
        Actor_FaceActor(ACTOR_GERALD, 13, 0);
        Actor_FaceActor(ACTOR_MIA, 13, 0);
        Actor_StartRepeatedMotion(13, 1);
        Event_Wait(60);
        Event_SetMessage(text_line + 12);
        Event_ShowMessage(13, 0);
        Value3(Engine_ActorShowEmote, 1, 259, 0);
        Event_Wait(60);
        Actor_SetAnimation(13, 4);
        Event_SetMessage(text_line + 13);
        Event_ShowMessage(13, 0);
        Value3(Engine_ActorWalkTo, 1, 456, 248);
        Actor_WaitForMove(ACTOR_GERALD);
        Value3(Engine_ActorFaceDirection, 1, 16384, 0);
        Event_SetMessage(text_line + 14);
        Event_ShowMessage(ACTOR_GERALD, 0);
        Value3(Engine_ActorWalkTo, 2, 472, 216);
        Actor_WaitForMove(ACTOR_IVAN);
        Value3(Engine_ActorFaceDirection, 2, 16384, 0);
        Event_Wait(10);
        Event_SetMessage(text_line + 15);
        Event_ShowMessage(ACTOR_IVAN, 0);
        Value3(Engine_ActorShowEmote, 12, 261, 0);
        Event_Wait(60);
        Event_SetMessage(text_line + 16);
        Event_ShowMessage(12, 0);
        Value3(Engine_ActorWalkTo, 3, 440, 216);
        Actor_WaitForMove(ACTOR_MIA);
        Actor_FaceActor(ACTOR_MIA, 13, 0);
        Actor_SetAnimationAndWait(ACTOR_MIA, 3);
        Event_Wait(10);
        Event_SetMessage(text_line + 17);
        Event_ShowMessage(ACTOR_MIA, 0);
        Actor_SetAnimation(13, 4);
        Event_SetMessage(text_line + 18);
        Event_ShowMessage(13, 0);
        Actor_ShowEmote(ACTOR_PARTY_LEADER, 258, 0);
        Actor_ShowEmote(ACTOR_GERALD, 258, 0);
        Actor_ShowEmote(ACTOR_MIA, 258, 0);
        Actor_ShowEmote(ACTOR_IVAN, 258, 0);
        Value3(Engine_ActorShowEmote, 13, 264, 0);
        Event_Wait(60);
        Event_SetMessage(text_line + 19);
        Event_ShowMessage(13, 0);
        Event_Wait(20);
        Value3(Engine_ActorShowEmote, 1, 259, 0);
        Event_Wait(60);
        Event_SetMessage(text_line + 20);
        Event_ShowMessage(ACTOR_GERALD, 0);
        Actor_StartRepeatedMotion(13, 1);
        Event_Wait(60);
        Event_SetMessage(text_line + 21);
        Event_ShowMessage(13, 0);
        Value3(Engine_ActorWalkTo, 13, 456, 280);
        Actor_WaitForMove(13);
        Value3(Engine_ActorFaceDirection, 13, 20480, 0);
        Event_Wait(80);
        Value3(ObjectMotion_OffsetPositionAndResetMotion, 13, -8, 8);
        Actor_WaitForMove(13);
        Event_Wait(60);
        Audio_PlayCue(155);
        Message_ShowCentered((s32)MsgRunpaDodonpaPulledLever, 1);
        Actor_SetDestinationOffset(13, 8, -8);
        Actor_FaceActor(13, 11, 0);
        FieldScene_RunScene3bf_020025f8();
        Audio_PlayCue(52);
        Event_SetMessage(text_line + 23);
        Event_ShowMessage(13, 0);
        Event_Wait(60);
        Actor_FaceActor(ACTOR_PARTY_LEADER, 11, 0);
        Actor_FaceActor(ACTOR_GERALD, 11, 0);
        Actor_FaceActor(ACTOR_IVAN, 11, 0);
        Actor_FaceActor(ACTOR_MIA, 11, 0);
        Actor_FaceActor(12, 11, 0);
        FieldScene_RunScene3bf_02002718();
        FieldScene_RunScene3bf_0200269c();
        GameFlag_Set(2370);
        SHARED_RECORD_FIELD_448 = 512;
        Event_Wait(1);
        do {
            gGameState.unknown_1f8[0x22b - 0x1f8] = 3;
        } while (0);
        Func_02008788_a(0xa3, 4);
        Func_02008788_b(98, 4);
    }
    Event_End();
}
