[workspace]

[package]
name = "sentou-kouka-runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "sentou_kouka_runtime"
path = "src/lib.rs"

[[bin]]
name = "sentou-kouka-runtime"
path = "src/main.rs"

[dependencies]
canonical-json = { path = "../canonical-json" }
serde_json = { version = "1", features = ["preserve_order"] }
