[package]
name = "alchemy"
version = "0.1.0"
edition = "2021"

[dependencies]
png = "0.17"
psynergy = { path = "../psynergy" }
candidate-compiler = { path = "../candidate-compiler" }
diff = { path = "../diff" }
compiler-core = { path = "../compiler-core" }
objdiff-core = { version = "3.8.0", default-features = false, features = ["arm", "std"] }
disassemble = { path = "../disassemble" }
matching = { path = "../matching" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
walkdir = "2.5"
lz-codecs = { path = "../lz-codecs" }
import-asset = { path = "../import-asset" }
sha1 = "0.10"
sha2 = "0.10"
coverage-map = { path = "../coverage-map" }
overlay-adopt = { path = "../overlay-adopt" }
tempfile = "3"

[[bin]]
name = "alchemy"
path = "src/main.rs"
