[package]
name = "integrate-matches"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
disassemble = { path = "../disassemble" }
tempfile = "3"
serde_json = { version = "1", features = ["preserve_order"] }
candidate-compiler = { path = "../candidate-compiler" }
compiler-core = { path = "../compiler-core" }
no-asm-c = { path = "../no-asm-c" }

[lib]
name = "integrate_matches"
path = "src/lib.rs"
