#include "HEYA.H"
#include "CALL.H"
extern u8 MsgRariberoDoNotWorryAboutSheba[];
extern u8 MsgRariberoHowDidSearchForSheba[];

void FieldScene_RunPrimaryScript(void)
{
    void Event_Begin();

    Engine_EventBegin();
    Owner_RefreshActiveRatios(1);
    Actor_SetPosition(ACTOR_PARTY_LEADER, 6291456, 12058624);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 49152, 0);
    Actor_FaceDirection(11, 0, 0);
    Value3(Engine_ActorFaceDirection, 12, 32768, 0);
    Event_SetMessage((s32)MsgRariberoHowDidSearchForSheba);
    Engine_EventOpenScreen();
    Engine_EventWaitForScreen();
    Engine_EventWait(10);
    Actor_SetSpeed(ACTOR_PARTY_LEADER, 65536, 32768);
    Actor_WalkByAndWait(ACTOR_PARTY_LEADER, 0, -16);
    Engine_ActorWalkToAndWait(0, 104, 136);
    Engine_EventWait(10);
    Call4(Motion_LaunchFromFocusedObject, 1, -16, 16, 49152);
    Call4(Motion_LaunchFromFocusedObject, 3, 0, 24, 49152);
    Value4(Motion_LaunchFromFocusedObject, 2, 16, 16, 49152);
    Engine_ActorWaitForMove(1);
    Engine_EventWait(20);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Actor_FaceDirection(11, 16384, 0);
    Engine_ActorFaceDirection(12, 16384, 0);
    Engine_EventWait(30);
    Actor_ShowEmote(11, 261, 70);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(20);
    Engine_ActorRunRepeatedMotion(11, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(20);
    Actor_ShowEmote(12, 258, 40);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(12, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(20);
    Event_Wait(10);
    Actor_ShowEmote(11, 261, 50);
    Engine_EventShowMessage(11, 0);
    if (GameFlag_IsSet(2495) == 0) {
        FieldScene_RunSecondaryScript();
    } else {
    Event_Wait(20);
    Engine_ActorRunRepeatedMotion(11, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_PARTY_LEADER, 50);
    Actor_ShowEmote(ACTOR_PARTY_LEADER, 261, 60);
    Engine_EventWait(10);
    Engine_ActorFaceDirection(1, 49152, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(3, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(20);
    Actor_ShowEmote(12, 257, 40);
    Event_OpenMessage(12, 0);
    Event_ChooseYesNo(0, 0);
    Engine_EventWait(20);
    Engine_ActorRunRepeatedMotion(12, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimationAndWait(0, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(3, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(2, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_PARTY_LEADER, 30);
    Event_OpenMessage(8194, 0);
    }
    Event_SetMessage((s32)MsgRariberoDoNotWorryAboutSheba);
    Engine_EventWait(10);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 16384, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_PARTY_LEADER, 20);
    if (Event_ChooseYesNo(0, 0) == 0) {
    Engine_EventWait(20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 49152, 0);
    Actor_FaceDirection(ACTOR_GERALD, 49152, 0);
    Engine_ActorFaceDirection(2, 49152, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(11, 0);
    (*(u16 *)(*(u8 **)&gEventWork + 0x1d8))++;
    } else {
    Event_Wait(20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 49152, 0);
    Actor_FaceDirection(ACTOR_GERALD, 49152, 0);
    Engine_ActorFaceDirection(2, 49152, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 4);
    Engine_EventWait(20);
    (*(u16 *)(*(u8 **)&gEventWork + 0x1d8))++;
    Event_ShowMessage(11, 0);
    }
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(11, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_FaceEachOther(ACTOR_GERALD, ACTOR_PARTY_LEADER, 0);
    Engine_ActorFaceEachOther(3, 2, 0);
    Engine_EventWait(40);
    Engine_EventWait(10);
    Actor_ShowEmote(11, 258, 40);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 49152, 0);
    Actor_FaceDirection(ACTOR_GERALD, 49152, 0);
    Actor_FaceDirection(ACTOR_IVAN, 49152, 0);
    Value3(Engine_ActorFaceDirection, 3, 49152, 0);
    Engine_EventWait(50);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(11, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_ShowEmote(ACTOR_MIA, 256, 40);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(20);
    Engine_ActorFaceDirection(11, 0, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(12, 2);
    Engine_EventWait(20);
    Value3(Engine_ActorFaceDirection, 12, 32768, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 11, 16384, 0);
    Engine_EventWait(30);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_ShowEmote(12, 258, 50);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(20);
    Actor_ShowEmote(11, 257, 65);
    Engine_ActorFaceDirection(11, 0, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(20);
    Actor_ShowEmote(12, 256, 40);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(20);
    Value3(Engine_ActorFaceDirection, 12, 16384, 0);
    Event_Wait(40);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 11, 16384, 0);
    Engine_EventWait(50);
    Actor_ShowEmote(11, 262, 60);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Actor_StartRepeatedMotion(ACTOR_GERALD, 2);
    Actor_StartRepeatedMotion(ACTOR_MIA, 2);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorFaceDirection(11, 0, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(12, 2);
    Engine_EventWait(30);
    Value3(Engine_ActorFaceDirection, 12, 32768, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(10);
    Actor_ShowEmote(11, 257, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 1, 57344, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(1, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 12, 16384, 0);
    Engine_EventWait(30);
    Actor_ShowEmote(12, 261, 60);
    Engine_EventShowMessage(12, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 11, 16384, 0);
    Engine_EventWait(40);
    Actor_ShowEmote(11, 258, 40);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorFaceDirection(2, 32768, 0);
    Engine_EventWait(30);
    Actor_ShowEmote(ACTOR_IVAN, 263, 60);
    Engine_ActorFaceDirection(2, 49152, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(2, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Actor_StartRepeatedMotion(ACTOR_GERALD, 2);
    Actor_StartRepeatedMotion(ACTOR_MIA, 2);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(20);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, 3);
    Actor_SetAnimation(ACTOR_GERALD, 3);
    Actor_SetAnimation(ACTOR_MIA, 3);
    Engine_ActorSetAnimationAndWait(2, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(11, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(11, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(11, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimationAndWait(3, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 16384, 0);
    Actor_FaceDirection(ACTOR_GERALD, 57344, 0);
    Engine_ActorFaceDirection(2, 40960, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(0, 3);
    Engine_EventWait(10);
    Actor_SetAnimation(ACTOR_GERALD, 3);
    Actor_SetAnimation(ACTOR_IVAN, 3);
    Engine_ActorSetAnimationAndWait(3, 3);
    Engine_EventWait(30);
    Actor_SetSpeed(ACTOR_GERALD, 78643, 39321);
    Actor_SetSpeed(ACTOR_MIA, 78643, 39321);
    Actor_SetSpeed(ACTOR_IVAN, 78643, 39321);
    Engine_ActorSetAnimation(1, 2);
    {
        u8 *rec = Engine_ActorGet(ACTOR_PARTY_LEADER);
        if (rec != 0) {
            s16 y = *(s16 *)(rec + 10);
            s16 x = *(s16 *)(rec + 18);
            Engine_ActorSetDestination(1, y, x);
        }
    }
    Engine_ActorWaitForMove(1);
    Actor_SetPosition(ACTOR_GERALD, 0, 0);
    Engine_ActorSetAnimation(3, 2);
    {
        u8 *rec = Engine_ActorGet(ACTOR_PARTY_LEADER);
        if (rec != 0) {
            s16 y = *(s16 *)(rec + 10);
            s16 x = *(s16 *)(rec + 18);
            Engine_ActorSetDestination(3, y, x);
        }
    }
    Engine_ActorWaitForMove(3);
    Actor_SetPosition(ACTOR_MIA, 0, 0);
    Engine_ActorSetAnimation(2, 2);
    {
        u8 *rec = Engine_ActorGet(ACTOR_PARTY_LEADER);
        if (rec != 0) {
            s16 y = *(s16 *)(rec + 10);
            s16 x = *(s16 *)(rec + 18);
            Engine_ActorSetDestination(2, y, x);
        }
    }
    Engine_ActorWaitForMove(2);
    Engine_ActorSetPosition(2, 0, 0);
    Engine_EventWait(10);
    Engine_EventEnd();
}
