#ifndef ALCHEMY_ABI_OVERLAYS_SCENE_ACTOR_SELECTED_PRESENTATION_APPLY_ZERO_AND_CLEAR_BYTE_89
#define ALCHEMY_ABI_OVERLAYS_SCENE_ACTOR_SELECTED_PRESENTATION_APPLY_ZERO_AND_CLEAR_BYTE_89

/* Binding layer — not production source. Address / far-call ABI only. */

void Func_02001568();

#define Actor_Run Func_02001568

#endif
