[workspace]

[package]
name = "staff-roll"
version = "0.1.0"
edition = "2021"

[lib]
name = "staff_roll"
path = "src/lib.rs"

[[bin]]
name = "staff-roll"
path = "src/main.rs"

[dependencies]
canonical-json = { path = "../canonical-json" }
import-asset = { path = "../import-asset" }
serde_json = { version = "1", features = ["preserve_order"] }
