[workspace]

[package]
name = "namae-nyuuryoku"
version = "0.1.0"
edition = "2021"

[lib]
name = "namae_nyuuryoku"
path = "src/lib.rs"

[[bin]]
name = "namae-nyuuryoku"
path = "src/main.rs"

[dependencies]
extract-resource = { path = "../extract-resource" }
serde_json = { version = "1", features = ["preserve_order"] }
