#include "INTERIORS.H"

const struct SceneEntrance *Scene_GetEntrances(void)
{
    return gInteriorEntrances;
}

const struct SceneRegion *Scene_GetRegions(void)
{
    return NULL;
}

const u32 *Scene_GetExits(void)
{
    return gInteriorExits;
}

const struct ScenePlacement *Scene_GetPlacements(void)
{
    return gInteriorPlacements;
}

const struct SceneEvent *Scene_GetEvents(void)
{
    if (gGameState.entrance == ROOM_SUHARA_GATE_HOUSE) {
        return gSuharaGateHouseEvents;
    }
    if (GameFlag_IsSet(FLAG_LUNPA_TRADE_REOPENED) != 0) {
        return gInteriorReopenedEvents;
    }
    return gInteriorSealedEvents;
}

void Innkeeper_Talk(void)
{
    struct FieldActor *leader;

    leader = Actor_Get(ACTOR_PARTY_LEADER);
    if (FACING_IS_NORTH(leader->facing)) {
        if (GameFlag_IsSet(FLAG_LUNPA_TRADE_REOPENED) != 0) {
            Inn_Open(INN_LUNPA, ACTOR_INNKEEPER);
            return;
        }
    }
    Event_Begin();
    if (GameFlag_IsSet(FLAG_LUNPA_TRADE_REOPENED) != 0) {
        Event_SetMessage(MSG_INNKEEPER_OFFERS_ROOM);
        Event_AskYesNo(ACTOR_INNKEEPER, 0);
    } else {
        Event_SetMessage(MSG_INNKEEPER_OFFERS_OWN_HOME);
        Event_AskYesNo(ACTOR_INNKEEPER, 0);
    }
    Event_End();
}

void Chef_Talk(void)
{
    Event_Begin();
    Event_SetMessage(MSG_CHEF_OFFERS_STORY);
    Event_AskYesNo(ACTOR_CHEF, 0);
    GameFlag_Set(FLAG_LUNPA_HEARD_OF_PRISONER);
    Event_End();
}

void Chef_ReadMind(void)
{
    Event_Begin();
    Event_SetMessage(MSG_CHEF_THINKS_OF_PRISONER);
    Event_ShowMessage(ACTOR_CHEF, 0);
    GameFlag_Set(FLAG_LUNPA_HEARD_OF_PRISONER);
    Event_End();
}

void InnClerk_Talk(void)
{
    Event_Begin();
    Event_SetMessage(MSG_INN_CLERK_ASKS_ABOUT_GUEST);
    Event_AskYesNo(ACTOR_INN_CLERK, 0);
    Event_End();
}

void TemplePriest_Talk(void)
{
    struct FieldActor *leader;

    leader = Actor_Get(ACTOR_PARTY_LEADER);
    if (FACING_IS_NORTH(leader->facing)) {
        Sanctum_Open(ACTOR_TEMPLE_PRIEST);
    } else if (GameFlag_IsSet(FLAG_LUNPA_TRADE_REOPENED) != 0) {
        Event_Begin();
        Event_SetMessage(MSG_TEMPLE_PRIEST_REOPENED);
        Event_ShowMessage(ACTOR_TEMPLE_PRIEST, 0);
        Event_End();
    } else {
        Event_Begin();
        Event_SetMessage(MSG_TEMPLE_PRIEST_SEALED);
        Event_ShowMessage(ACTOR_TEMPLE_PRIEST, 0);
        Event_End();
    }
}

const struct SceneEntrance gInteriorEntrances[] = {
    { 0, CONDITION_ALWAYS, 172, 0, 149, FACING_SOUTH, 0, -1, -1, -1, -1, 0 },
    { ROOM_FIRST_HOME, CONDITION_ALWAYS, 192, 0, 184, FACING_NORTH, 0, 16, 0, 256, 224, 0 },
    { ROOM_SECOND_HOME, CONDITION_ALWAYS, 432, 0, 264, FACING_NORTH, 0, 296, 48, 536, 288, 0 },
    { ROOM_THIRD_HOME, CONDITION_ALWAYS, 160, 0, 584, FACING_NORTH, 0, 16, 400, 256, 624, 0 },
    { ROOM_ARMS_SHOP, CONDITION_ALWAYS, 464, 0, 616, FACING_NORTH, 0, 296, 384, 536, 640, 0 },
    { ROOM_ITEM_SHOP, CONDITION_ALWAYS, 704, 0, 584, FACING_NORTH, 0, 576, 352, 816, 608, 0 },
    { ROOM_INN, CONDITION_ALWAYS, 288, 0, 840, FACING_NORTH, 0, 40, 656, 368, 944, 0 },
    { ROOM_TEMPLE, CONDITION_ALWAYS, 688, 0, 280, FACING_NORTH, 0, 568, 32, 808, 304, 0 },
    { ROOM_EIGHTH, CONDITION_ALWAYS, 560, 0, 880, FACING_NORTH, 0, 400, 656, 640, 912, 0 },
    { ROOM_NINTH, CONDITION_ALWAYS, 672, 0, 888, FACING_NORTH, 0, 520, 656, 760, 896, 0 },
    { ROOM_SUHARA_GATE_HOUSE, CONDITION_ALWAYS, 832, 0, 848, FACING_NORTH, 0, 680, 656, 920, 896, 0 },
    { ROOM_TEMPLE_SECOND_ENTRANCE, CONDITION_ALWAYS, 688, 0, 184, FACING_NORTH, 0, 568, 32, 808, 288, 0 },
    { SCENE_TABLE_END },
};

const u32 gInteriorExits[] = {
    SCENE_EXITS(SCENE_RUNPA_SUHARA),
    SCENE_EXIT(ROOM_FIRST_HOME, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_FIRST_HOME),
    SCENE_EXIT(ROOM_SECOND_HOME, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_SECOND_HOME),
    SCENE_EXIT(ROOM_THIRD_HOME, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_THIRD_HOME),
    SCENE_EXIT(ROOM_ARMS_SHOP, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_ARMS_SHOP),
    SCENE_EXIT(ROOM_ITEM_SHOP, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_ITEM_SHOP),
    SCENE_EXIT(ROOM_INN, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_INN),
    SCENE_EXIT(ROOM_TEMPLE, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_TEMPLE),
    SCENE_EXIT(ROOM_EIGHTH, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_EIGHTH_ROOM),
    SCENE_EXIT(ROOM_SUHARA_GATE_HOUSE, SCENE_SUHARA_GATE, SUHARA_GATE_ENTRANCE_FROM_LUNPA),
    SCENE_EXITS_END,
};

const struct ScenePlacement gInteriorPlacements[] = {
    { SPRITE_TOWNSPERSON_D, CONDITION_ALWAYS, ACTOR_WANDER,
      PIXELS(144), 0, PIXELS(168), FACING_WEST, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_C, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(96), 0, PIXELS(128), FACING_SOUTH, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_TOWNSPERSON_A, CONDITION_ALWAYS, ACTOR_WANDER,
      PIXELS(392), 0, PIXELS(240), FACING_SOUTH, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_F, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(403), 0, PIXELS(138), FACING_EAST, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_B, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(160), 0, PIXELS(508), FACING_SOUTH - FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_E, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(88), 0, PIXELS(584), FACING_NORTH + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_WEAPON_MERCHANT, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(376), 0, PIXELS(531), FACING_SOUTH - FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_ARMOR_MERCHANT, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(464), 0, PIXELS(531), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_ITEM_MERCHANT, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(720), 0, PIXELS(499), FACING_SOUTH, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_INNKEEPER, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(264), 0, PIXELS(744), FACING_SOUTH, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_F, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(248), 0, PIXELS(808), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_C, CONDITION_ALWAYS, ACTOR_WANDER,
      PIXELS(144), 0, PIXELS(888), FACING_NORTHWEST, TALK_FACE_PARTY, 0 },
    { SPRITE_CHEF, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(152), 0, PIXELS(744), FACING_SOUTH, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_PRIEST, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(688), 0, PIXELS(152), FACING_SOUTH, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_PRIEST, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(776), 0, PIXELS(800), FACING_SOUTH, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_COUNTER, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(376), 0, PIXELS(544), FACING_SOUTH - FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_COUNTER, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(464), 0, PIXELS(544), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_COUNTER, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(720), 0, PIXELS(512), FACING_SOUTH, TALK_FACE_PARTY_AND_BACK, 0 },
    { SCENE_TABLE_END },
};

const struct SceneEvent gInteriorSealedEvents[] = {
    ROOM_DOOR(ROOM_FIRST_HOME),
    ROOM_DOOR(ROOM_SECOND_HOME),
    ROOM_DOOR(ROOM_THIRD_HOME),
    ROOM_DOOR(ROOM_ARMS_SHOP),
    ROOM_DOOR(ROOM_ITEM_SHOP),
    ROOM_DOOR(ROOM_INN),
    ROOM_DOOR(ROOM_TEMPLE),
    ROOM_DOOR(ROOM_EIGHTH),
    { EVENT_TALK, ACTOR_FIRST_HOME_RESIDENT_A, CONDITION_ALWAYS, MSG_FIRST_HOME_A_SEALED },
    { EVENT_TALK, ACTOR_FIRST_HOME_RESIDENT_B, CONDITION_ALWAYS, MSG_FIRST_HOME_B_SEALED },
    { EVENT_TALK, ACTOR_SECOND_HOME_RESIDENT_A, CONDITION_ALWAYS, MSG_SECOND_HOME_A_SEALED },
    { EVENT_TALK, ACTOR_SECOND_HOME_RESIDENT_B, CONDITION_ALWAYS, MSG_SECOND_HOME_B_SEALED },
    { EVENT_TALK, ACTOR_THIRD_HOME_RESIDENT_A, CONDITION_ALWAYS, MSG_THIRD_HOME_A_SEALED },
    { EVENT_TALK, ACTOR_THIRD_HOME_RESIDENT_B, CONDITION_ALWAYS, MSG_THIRD_HOME_B_SEALED },
    { EVENT_TALK, ACTOR_WEAPON_MERCHANT, CONDITION_ALWAYS, EVENT_SCRIPT(WeaponMerchant_Talk) },
    { EVENT_TALK, ACTOR_ARMOR_MERCHANT, CONDITION_ALWAYS, EVENT_SCRIPT(ArmorMerchant_Talk) },
    { EVENT_TALK, ACTOR_WEAPON_COUNTER, CONDITION_ALWAYS, EVENT_SCRIPT(WeaponMerchant_Talk) },
    { EVENT_TALK, ACTOR_ARMOR_COUNTER, CONDITION_ALWAYS, EVENT_SCRIPT(ArmorMerchant_Talk) },
    { EVENT_TALK, ACTOR_ITEM_MERCHANT, CONDITION_ALWAYS, EVENT_SCRIPT(ItemMerchant_Talk) },
    { EVENT_TALK, ACTOR_ITEM_COUNTER, CONDITION_ALWAYS, EVENT_SCRIPT(ItemMerchant_Talk) },
    { EVENT_TALK, ACTOR_INNKEEPER, CONDITION_ALWAYS, EVENT_SCRIPT(Innkeeper_Talk) },
    { EVENT_TALK, ACTOR_INN_CLERK, CONDITION_ALWAYS, MSG_INN_CLERK_SEALED },
    { EVENT_TALK, ACTOR_INN_WORKER, CONDITION_ALWAYS, MSG_INN_WORKER_SEALED },
    { EVENT_TALK, ACTOR_CHEF, CONDITION_ALWAYS, EVENT_SCRIPT(Chef_Talk) },
    { EVENT_TALK, ACTOR_TEMPLE_PRIEST, CONDITION_ALWAYS, EVENT_SCRIPT(TemplePriest_Talk) },
    { EVENT_TALK, ACTOR_TRAVELING_PRIEST, CONDITION_ALWAYS, EVENT_SCRIPT(TravelingPriest_Talk) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_FIRST_HOME_RESIDENT_A, CONDITION_ALWAYS,
      MSG_FIRST_HOME_A_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_FIRST_HOME_RESIDENT_B, CONDITION_ALWAYS,
      MSG_FIRST_HOME_B_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_SECOND_HOME_RESIDENT_A, CONDITION_ALWAYS,
      MSG_SECOND_HOME_A_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_SECOND_HOME_RESIDENT_B, CONDITION_ALWAYS,
      MSG_SECOND_HOME_B_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_THIRD_HOME_RESIDENT_A, CONDITION_ALWAYS,
      MSG_THIRD_HOME_A_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_THIRD_HOME_RESIDENT_B, CONDITION_ALWAYS,
      MSG_THIRD_HOME_B_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_WEAPON_MERCHANT, CONDITION_ALWAYS,
      EVENT_SCRIPT(WeaponMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ARMOR_MERCHANT, CONDITION_ALWAYS,
      EVENT_SCRIPT(ArmorMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_WEAPON_COUNTER, CONDITION_ALWAYS,
      EVENT_SCRIPT(WeaponMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ARMOR_COUNTER, CONDITION_ALWAYS,
      EVENT_SCRIPT(ArmorMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ITEM_MERCHANT, CONDITION_ALWAYS,
      EVENT_SCRIPT(ItemMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ITEM_COUNTER, CONDITION_ALWAYS,
      EVENT_SCRIPT(ItemMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_INNKEEPER, CONDITION_ALWAYS,
      MSG_INNKEEPER_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_INN_CLERK, CONDITION_ALWAYS,
      MSG_INN_CLERK_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_INN_WORKER, CONDITION_ALWAYS,
      MSG_INN_WORKER_SEALED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_CHEF, CONDITION_ALWAYS,
      EVENT_SCRIPT(Chef_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_TEMPLE_PRIEST, CONDITION_ALWAYS,
      MSG_TEMPLE_PRIEST_SEALED_THOUGHTS },
    { SEARCH(SEARCH_WOODEN_BOX), TRIGGER_WOODEN_BOX, FLAG_INTERIOR_WOODEN_BOX,
      FIND_ITEM(ITEM_LUCKY_MEDAL) },
    { SEARCH(SEARCH_BARREL), TRIGGER_BARREL, FLAG_INTERIOR_BARREL, FIND_ITEM(ITEM_VIAL) },
    { SEARCH(SEARCH_OVEN), TRIGGER_FIRST_OVEN, CONDITION_ALWAYS, FIND_MESSAGE(MSG_FIRST_OVEN) },
    { SEARCH(SEARCH_OVEN), TRIGGER_SECOND_OVEN, CONDITION_ALWAYS, FIND_MESSAGE(MSG_SECOND_OVEN) },
    { SCENE_EVENTS_END },
};

const struct SceneEvent gInteriorReopenedEvents[] = {
    ROOM_DOOR(ROOM_FIRST_HOME),
    ROOM_DOOR(ROOM_SECOND_HOME),
    ROOM_DOOR(ROOM_THIRD_HOME),
    ROOM_DOOR(ROOM_ARMS_SHOP),
    ROOM_DOOR(ROOM_ITEM_SHOP),
    ROOM_DOOR(ROOM_INN),
    ROOM_DOOR(ROOM_TEMPLE),
    ROOM_DOOR(ROOM_EIGHTH),
    { EVENT_TALK, ACTOR_FIRST_HOME_RESIDENT_A, CONDITION_ALWAYS, MSG_FIRST_HOME_A_REOPENED },
    { EVENT_TALK, ACTOR_FIRST_HOME_RESIDENT_B, CONDITION_ALWAYS, MSG_FIRST_HOME_B_REOPENED },
    { EVENT_TALK, ACTOR_SECOND_HOME_RESIDENT_A, CONDITION_ALWAYS, MSG_SECOND_HOME_A_REOPENED },
    { EVENT_TALK, ACTOR_SECOND_HOME_RESIDENT_B, CONDITION_ALWAYS, MSG_SECOND_HOME_B_REOPENED },
    { EVENT_TALK, ACTOR_THIRD_HOME_RESIDENT_A, CONDITION_ALWAYS, MSG_THIRD_HOME_A_REOPENED },
    { EVENT_TALK, ACTOR_THIRD_HOME_RESIDENT_B, CONDITION_ALWAYS, MSG_THIRD_HOME_B_REOPENED },
    { EVENT_TALK, ACTOR_WEAPON_MERCHANT, CONDITION_ALWAYS, EVENT_SCRIPT(WeaponMerchant_Talk) },
    { EVENT_TALK, ACTOR_ARMOR_MERCHANT, CONDITION_ALWAYS, EVENT_SCRIPT(ArmorMerchant_Talk) },
    { EVENT_TALK, ACTOR_ITEM_MERCHANT, CONDITION_ALWAYS, EVENT_SCRIPT(ItemMerchant_Talk) },
    { EVENT_TALK, ACTOR_ITEM_COUNTER, CONDITION_ALWAYS, EVENT_SCRIPT(ItemMerchant_Talk) },
    { EVENT_TALK, ACTOR_WEAPON_COUNTER, CONDITION_ALWAYS, EVENT_SCRIPT(WeaponMerchant_Talk) },
    { EVENT_TALK, ACTOR_ARMOR_COUNTER, CONDITION_ALWAYS, EVENT_SCRIPT(ArmorMerchant_Talk) },
    { EVENT_TALK, ACTOR_INNKEEPER, CONDITION_ALWAYS, EVENT_SCRIPT(Innkeeper_Talk) },
    { EVENT_TALK, ACTOR_INN_CLERK, CONDITION_ALWAYS, EVENT_SCRIPT(InnClerk_Talk) },
    { EVENT_TALK, ACTOR_INN_WORKER, CONDITION_ALWAYS, MSG_INN_WORKER_REOPENED },
    { EVENT_TALK, ACTOR_CHEF, CONDITION_ALWAYS, MSG_CHEF_REOPENED },
    { EVENT_TALK, ACTOR_TEMPLE_PRIEST, CONDITION_ALWAYS, EVENT_SCRIPT(TemplePriest_Talk) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_FIRST_HOME_RESIDENT_A, CONDITION_ALWAYS,
      MSG_FIRST_HOME_A_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_FIRST_HOME_RESIDENT_B, CONDITION_ALWAYS,
      MSG_FIRST_HOME_B_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_SECOND_HOME_RESIDENT_A, CONDITION_ALWAYS,
      MSG_SECOND_HOME_A_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_SECOND_HOME_RESIDENT_B, CONDITION_ALWAYS,
      MSG_SECOND_HOME_B_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_THIRD_HOME_RESIDENT_A, CONDITION_ALWAYS,
      MSG_THIRD_HOME_A_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_THIRD_HOME_RESIDENT_B, CONDITION_ALWAYS,
      MSG_THIRD_HOME_B_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_WEAPON_MERCHANT, CONDITION_ALWAYS,
      EVENT_SCRIPT(WeaponMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ARMOR_MERCHANT, CONDITION_ALWAYS,
      EVENT_SCRIPT(ArmorMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_WEAPON_COUNTER, CONDITION_ALWAYS,
      EVENT_SCRIPT(WeaponMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ARMOR_COUNTER, CONDITION_ALWAYS,
      EVENT_SCRIPT(ArmorMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ITEM_MERCHANT, CONDITION_ALWAYS,
      EVENT_SCRIPT(ItemMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_ITEM_COUNTER, CONDITION_ALWAYS,
      EVENT_SCRIPT(ItemMerchant_ReadMind) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_INNKEEPER, CONDITION_ALWAYS,
      MSG_INNKEEPER_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_INN_CLERK, CONDITION_ALWAYS,
      MSG_INN_CLERK_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_INN_WORKER, CONDITION_ALWAYS,
      MSG_INN_WORKER_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_CHEF, CONDITION_ALWAYS,
      MSG_CHEF_REOPENED_THOUGHTS },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_TEMPLE_PRIEST, CONDITION_ALWAYS,
      MSG_TEMPLE_PRIEST_REOPENED_THOUGHTS },
    { SEARCH(SEARCH_WOODEN_BOX), TRIGGER_WOODEN_BOX, FLAG_INTERIOR_WOODEN_BOX,
      FIND_ITEM(ITEM_LUCKY_MEDAL) },
    { SEARCH(SEARCH_BARREL), TRIGGER_BARREL, FLAG_INTERIOR_BARREL, FIND_ITEM(ITEM_VIAL) },
    { SEARCH(SEARCH_OVEN), TRIGGER_FIRST_OVEN, CONDITION_ALWAYS, FIND_MESSAGE(MSG_FIRST_OVEN) },
    { SEARCH(SEARCH_OVEN), TRIGGER_SECOND_OVEN, CONDITION_ALWAYS, FIND_MESSAGE(MSG_SECOND_OVEN) },
    { SCENE_EVENTS_END },
};

const struct SceneEvent gSuharaGateHouseEvents[] = {
    ROOM_DOOR(ROOM_SUHARA_GATE_HOUSE),
    { EVENT_TALK, ACTOR_TRAVELING_PRIEST, CONDITION_ALWAYS, EVENT_SCRIPT(TravelingPriest_Talk) },
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), ACTOR_TRAVELING_PRIEST, CONDITION_ALWAYS,
      MSG_TRAVELING_PRIEST_THOUGHTS },
    { SCENE_EVENTS_END },
};
