[package]
name = "disassemble"
version = "0.1.0"
edition = "2021"

[lib]
name = "disassemble"
path = "src/lib.rs"

[dependencies]
psynergy = { path = "../psynergy" }
compiler-core = { path = "../compiler-core" }
candidate-compiler = { path = "../candidate-compiler" }
lz-codecs = { path = "../lz-codecs" }
regex = "1.13.1"
serde_json = "1"
tempfile = "3"
