[package]
name = "disassemble"
version = "0.1.0"
edition = "2021"

[lib]
name = "disassemble"
path = "src/lib.rs"

[dependencies]
compiler-core = { path = "../compiler-core" }
candidate-compiler = { path = "../candidate-compiler" }
cache-entry = { path = "../cache-entry" }
extract-resource = { path = "../extract-resource" }
regex = "1.13.1"
serde_json = "1"
tempfile = "3"
