/* Offering the guarantee. */
#include "STAR.H"
extern u8 MsgSoruMenardiDontYouWantThem[];

void Scene_OfferGuarantee(void)
{
    u32 i;
    s32 record;

    Actor_FaceDirection(ACTOR_JASMINE, 0x6000, 0);
    Actor_FaceDirection(ACTOR_SUKURETA, 0x5000, 0);
    Actor_FaceDirection(ACTOR_SATUROS, 0x8000, 0);
    Actor_FaceDirection(ACTOR_GARCIA_MASKED, 0x5000, 40);
    Actor_FaceDirection(ACTOR_MENARDI, 0xd000, 40);
    Actor_RunRepeatedMotion(ACTOR_MENARDI, 2);
    Event_SayThenWait(11, 20);
    Actor_RunRepeatedMotion(ACTOR_GARCIA_MASKED, 2);
    Actor_SetAttachedEffect(ACTOR_GARCIA_MASKED, 0x102);
    Event_Wait(60);
    Event_SayThenWait(12, 10);
    Actor_FaceActor(ACTOR_SATUROS, ACTOR_GARCIA_MASKED, 0);
    Actor_FaceActor(ACTOR_JASMINE, ACTOR_GARCIA_MASKED, 0);
    Actor_FaceActor(ACTOR_SUKURETA, ACTOR_GARCIA_MASKED, 0);
    Event_Wait(40);
    Actor_RunRepeatedMotion(ACTOR_SATUROS, 1);
    Actor_FaceDirection(ACTOR_SATUROS, 0x8000, 10);
    Actor_SetAnimation(ACTOR_SATUROS, 3);
    Event_SayThenWait(10, 10);
    Actor_FaceDirection(ACTOR_MENARDI, 0, 10);
    Actor_SetAnimationAndWait(ACTOR_MENARDI, 3);
    Event_Wait(10);
    Actor_FaceDirection(ACTOR_JASMINE, 0, 0);
    Actor_FaceDirection(ACTOR_SUKURETA, 0x8000, 20);
    Actor_StartRepeatedMotion(ACTOR_JASMINE, 2);
    Actor_RunRepeatedMotion(ACTOR_SUKURETA, 2);
    Event_Wait(10);
    Actor_FaceDirection(ACTOR_JASMINE, 0xc000, 0);
    Actor_FaceDirection(ACTOR_SUKURETA, 0xb000, 10);
    Actor_FaceDirection(ACTOR_SATUROS, 0xb000, 40);
    Actor_SetAnimationAndWait(ACTOR_SATUROS, 3);
    Event_SayThenWait(10, 10);
    Actor_ShowEmote(ACTOR_JASMINE, 0x100, 20);
    Actor_SetAttachedEffect(ACTOR_GARCIA_MASKED, 0x102);
    Actor_RunRepeatedMotion(ACTOR_GARCIA_MASKED, 3);
    Event_Wait(40);
    Actor_SetPosition(ACTOR_GERALD, 0x15a0000, 0x1b80000);
    Task_Wait(1);
    Event_ShowMessage(ACTOR_GERALD, 0);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x2000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xa000, 20);
    Event_CloseScreen();
    Event_WaitForScreen();
    Actor_SetPosition(ACTOR_GERALD, 0x1180000, 0x1d60000);
    Camera_MoveTo(0x1050000, -1, 0x1d20000, 0);
    Map_Redraw();
    Task_Wait(1);
    Event_OpenScreen();
    Event_WaitForScreen();
    Event_Wait(20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x3000, 10);
    Actor_ShowEmote(ACTOR_GERALD, 0x102, 0);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 3);
    Event_AskYesNo(ACTOR_GERALD, 0);
    Event_Wait(10);
    Actor_SetAnimationAndWait(ACTOR_GERALD, 4);
    Event_Wait(10);
    Event_AskYesNo(ACTOR_GERALD, 0);
    Event_Wait(10);
    Event_SetMessage((s32)MsgSoruMenardiDontYouWantThem);
    Event_ShowMessage(ACTOR_MENARDI, 0);
    Actor_FaceDirection(ACTOR_MENARDI, 0xd000, 10);
    Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Actor_RunRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Event_Wait(10);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xe000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xe000, 20);
    Event_CloseScreen();
    Event_WaitForScreen();
    Camera_MoveTo(0x1dd0000, -1, 0x14e0000, 0);
    Map_Redraw();
    Task_Wait(1);
    Event_OpenScreen();
    Event_WaitForScreen();
    Event_Wait(20);
    Actor_RunRepeatedMotion(ACTOR_SUKURETA, 2);
    Event_Wait(10);
    Actor_FaceDirection(ACTOR_SUKURETA, 0x8000, 30);
    Event_SayThenWait(9, 20);
    Actor_FaceDirection(ACTOR_JASMINE, 0, 40);
    Actor_SetAnimationAndWait(ACTOR_JASMINE, 4);
    Event_Wait(20);
    Event_SayThenWait(5, 10);
    Actor_RunRepeatedMotion(ACTOR_GARCIA_MASKED, 2);
    Event_Wait(80);
    Event_SayThenWait(12, 20);
    Actor_RunRepeatedMotion(ACTOR_JASMINE, 2);
    Actor_FaceDirection(ACTOR_JASMINE, 0xc000, 0);
    Actor_FaceDirection(ACTOR_SUKURETA, 0xb000, 20);
    Actor_SetAnimationAndWait(ACTOR_GARCIA_MASKED, 3);
    Event_SayThenWait(12, 20);
    Actor_StartRepeatedMotion(ACTOR_JASMINE, 2);
    Actor_RunRepeatedMotion(ACTOR_SUKURETA, 2);
    Actor_FaceDirection(ACTOR_GARCIA_MASKED, 0xb000, 40);
}
