// Whole-file compiler-family decisions. Every file uses its family's one
// flag set from routing.rs; these declarations contain no function addresses.

// The shared MusicPlayer2000 C library uses agbcc -O2 in both games.
// This directory contains only that library's reconstructed C modules.
pub static AGBCC_DIRECTORIES: &[&str] = &["games/COMMON/SRC/SOUND"];

// Edition-specific MusicPlayer2000 modules and the two agbcc -O2 flash helpers.
// Their neighbouring game-owned SOUND and SAVE files keep the Game family.
pub static AGBCC_SOURCES: &[&str] = &[
    "games/THE BROKEN SEAL/SRC/SOUND/CGB_UPDATE_CHANNELS.C",
    "games/THE BROKEN SEAL/SRC/SOUND/COMMAND_INVOKE_SLOT34.C",
    "games/THE BROKEN SEAL/SRC/SOUND/COMMAND_INVOKE_SLOT35.C",
    "games/THE BROKEN SEAL/SRC/SOUND/MUSIC_TRACK_OPERATE_WORK_BYTE.C",
    "games/THE BROKEN SEAL/SRC/SOUND/MUSIC_TRACK_SET_VOICE_ATTACK.C",
    "games/THE BROKEN SEAL/SRC/SOUND/MUSIC_TRACK_SET_VOICE_KIND.C",
    "games/THE BROKEN SEAL/SRC/SOUND/MUSIC_TRACK_SET_VOICE_LENGTH.C",
    "games/THE BROKEN SEAL/SRC/SOUND/MUSIC_TRACK_SET_VOICE_PAN_OR_SWEEP.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/FLASH_ERASE_VERIFY.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/FLASH_READ_ROUTINES.C",
    "games/THE LOST AGE/SRC/SOUND/MUSIC_TRACK_OPERATE_WORK_BYTE.C",
];

// The flash library uses agbcc -O: its allocation and scheduling match that
// family, while -O2 differs throughout. Game save-state handling is separate.
pub static AGBCC_FLASH_SOURCES: &[&str] = &[
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/ERASE_ATMEL_FLASH_BLOCK.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/ERASE_ATMEL_FLASH_CHIP.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/ERASE_ATMEL_FLASH_SECTOR.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/ERASE_FLASH_CHIP.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/ERASE_FLASH_SECTOR.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/FLASH_PROGRAM_BYTE.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/FLASH_TIMER_INTERRUPT.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/FLASH_VERIFY.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/IDENTIFY_FLASH.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/PROGRAM_ATMEL_FLASH_BLOCK.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/PROGRAM_ATMEL_FLASH_SECTOR.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/PROGRAM_FLASH_SECTOR.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/PROGRAM_FLASH_SECTOR_WITH_ERASE_RETRY.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/READ_FLASH.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/READ_FLASH_CORE.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/READ_FLASH_ID.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/START_FLASH_TIMER.C",
    "games/THE BROKEN SEAL/SRC/SYSTEM/SAVE/VERIFY_FLASH_SECTOR.C",
];
