#ifndef ALCHEMY_BATTLE_PARTY_H
#define ALCHEMY_BATTLE_PARTY_H

#include "types.h"

enum BattleSideMask {
    BATTLE_SIDE_PARTY = 1,
    BATTLE_SIDE_ENEMIES = 2,
    BATTLE_SIDE_BOTH = BATTLE_SIDE_PARTY | BATTLE_SIDE_ENEMIES
};

#endif
