#ifndef GUARD_GS1_EDITION_H
#define GUARD_GS1_EDITION_H

/* The Japanese render work carries 0x90 more bytes before these flags. */
#if defined(GS1_EDITION_JA)
#define RENDER_DIRTY_OFS 0xF33
#define RENDER_MODE_OFS  0xF34
#define RENDER_BUSY_OFS  0x1189
#define RENDER_VALUE_TBL_OFS 0x114C
#define RENDER_NAME_TBL_OFS  0x116C
#define RENDER_CHANNEL_OFS   0x6B0
#define RENDER_ENTRY_TBL_OFS 0xF40
#define RENDER_MENU_STATE_OFS 0xF35
#define RENDER_MENU_BUSY_OFS  0xF36
#define RENDER_ALT_OFS        0xF32
#define RENDER_WORD_OFS       0xF3C
#define RENDER_WORD2_OFS      0xF38
#define RENDER_PARAM_OFS      0xF3E
#define RENDER_TILE_ATTR_OFS  0xE30
#define RENDER_FREE_HEAD_OFS  0xE28
#define RENDER_FREE_TAIL_OFS  0xE2C
#define RENDER_ENTRY_COUNT_OFS 0x1142
#define RENDER_RESULT_OFS      0x1184
#define RENDER_ENTRY_MASK      0xFF
#define SELECT_MENU_WIDTH    5
#define TYPE_MENU_WIDTH      4
#define MENU_TEXT_X          100
#define MENU_LABEL_X         110
#define LIST_MARKER_CHAR     65
#else
#define RENDER_DIRTY_OFS 0xEA3
#define RENDER_MODE_OFS  0xEA4
#define RENDER_BUSY_OFS  0x12F9
#define RENDER_VALUE_TBL_OFS 0x12BC
#define RENDER_NAME_TBL_OFS  0x12DC
#define RENDER_CHANNEL_OFS   0x620
#define RENDER_ENTRY_TBL_OFS 0xEB0
#define RENDER_MENU_STATE_OFS 0xEA5
#define RENDER_MENU_BUSY_OFS  0xEA6
#define RENDER_ALT_OFS        0xEA2
#define RENDER_WORD_OFS       0xEAC
#define RENDER_WORD2_OFS      0xEA8
#define RENDER_PARAM_OFS      0xEAE
#define RENDER_TILE_ATTR_OFS  0xDA0
#define RENDER_FREE_HEAD_OFS  0xD98
#define RENDER_FREE_TAIL_OFS  0xD9C
#define RENDER_ENTRY_COUNT_OFS 0x12B2
#define RENDER_RESULT_OFS      0x12F4
#define RENDER_ENTRY_MASK      0x1FF
#define SELECT_MENU_WIDTH    7
#define TYPE_MENU_WIDTH      7
#define MENU_TEXT_X          74
#define MENU_LABEL_X         82
#define LIST_MARKER_CHAR     49
#endif

#define MENU_TEXT_Y 60

#if defined(GS1_EDITION_JA)
#define RENDER_RESOURCE_BASE 0x9D4
#elif defined(GS1_EDITION_DE) || defined(GS1_EDITION_ES) || \
      defined(GS1_EDITION_FR) || defined(GS1_EDITION_IT)
#define RENDER_RESOURCE_BASE 0xBDF
#else
#define RENDER_RESOURCE_BASE 0x99B
#endif

#endif
