#ifndef ALCHEMY_SOUND_IDS_H
#define ALCHEMY_SOUND_IDS_H

enum SoundId {
    SOUND_SHOP_PURCHASE = 101,
    SOUND_TRIPLE_TONE_LOW = 108,
    SOUND_TRIPLE_TONE_HIGH = 109,
    SOUND_MENU_CURSOR_MOVE = 111,
    SOUND_MENU_CONFIRM = 112,
    SOUND_MENU_CANCEL = 113,
    SOUND_MENU_ERROR = 114,
    SOUND_RECOVERY = 126,
    SOUND_HEAVY_IMPACT = 134,
    SOUND_ITEM_BREAK = 138,
    SOUND_SCENE_TRANSITION = 167,
};

#endif
