#ifndef ALCHEMY_SOUND_IDS_H
#define ALCHEMY_SOUND_IDS_H

enum SoundId {
    SOUND_SHOP_PURCHASE = 101,
    SOUND_MENU_CURSOR_MOVE = 111,
    SOUND_MENU_CONFIRM = 112,
    SOUND_MENU_CANCEL = 113,
    SOUND_MENU_ERROR = 114,
    SOUND_ITEM_BREAK = 138,
};

#endif
