#ifndef TLA_AUDIO_ENGINE_SYMBOLS_H
#define TLA_AUDIO_ENGINE_SYMBOLS_H

#define MusicPlayer_FadeOutPause Func_081c2168
#define MusicPlayer_FadeIn Func_081c2188
#define Math_Div Func_08002054
#define AUDIO_INITIAL_MODE 0x0099FA00
#define AUDIO_MIXER_DESTINATION ((void *)0x03006000)
#define Sound_Mixer Func_081c1310
#define Sound_PlayerSlots Data_081c44d0
#define Sound_SongTable Data_081c4530

#endif
