[workspace]

[package]
name = "resource-3ce"
version = "0.1.0"
edition = "2021"

[lib]
name = "resource_3ce"
path = "src/lib.rs"

[[bin]]
name = "resource-3ce"
path = "src/main.rs"

[dependencies]
canonical-json = { path = "../canonical-json" }
extract-resource = { path = "../extract-resource" }
overlay-disasm = { path = "../overlay-disasm" }
serde_json = { version = "1", features = ["preserve_order"] }
