[workspace]

[package]
name = "kind1-map-grid"
version = "0.1.0"
edition = "2021"

[lib]
name = "kind1_map_grid"
path = "src/lib.rs"

[[bin]]
name = "kind1-map-grid"
path = "src/main.rs"

[dependencies]
alchemy-zlib = { path = "../zlib" }
export-asset = { path = "../export-asset" }
extract-resource = { path = "../extract-resource" }
import-asset = { path = "../import-asset" }
serde_json = { version = "1", features = ["preserve_order"] }
