[workspace]

[package]
name = "permuter"
version = "0.1.0"
edition = "2021"

[dependencies]
alchemy-bundle = { path = "../alchemy-bundle" }
alchemy-routing = { path = "../alchemy-routing" }
candidate-compiler = { path = "../candidate-compiler" }
lang-c = "0.15.1"
overlay-disasm = { path = "../overlay-disasm" }
shape-sweep = { path = "../shape-sweep" }

[lib]
name = "permuter"
path = "src/lib.rs"

