[workspace]

[package]
name = "permuter"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler-core = { path = "../compiler-core" }
candidate-compiler = { path = "../candidate-compiler" }
candidate-show = { path = "../candidate-show" }
overlay-disasm = { path = "../overlay-disasm" }
serde_json = "1"
tempfile = "3"
regex = "1"

[lib]
name = "permuter"
path = "src/lib.rs"
