#include "SUHARA.H"
#include "CALL.H"

extern u8 MsgSuharaIodem[];

void Motion_LaunchFromFocusedObject();
void Audio_PlayCueFromEventWork(void);

/*
 * Runs the primary script for this scene: a long fixed sequence driving
 * actors 10, 19, 20, 21, 30 and 40 through position, pose and timing steps,
 * guarded by an initial skip check.
 */
void Scene_RunPrimaryScript(void)
{
    u8 *record;
    Engine_GameFlagSet(2480);
    if (Engine_GameFlagIsSet(2442) == 0) {
        Engine_AudioPlayCue(30);
        Engine_EventBegin();
        Engine_CameraMoveTo(24117248, -1, 6815744, 1);
        Call3(Engine_ActorWalkToAndWait, 0, 368, 160);
        Call3(Engine_ActorFaceDirection, 0, 49152, 0);
        Call4(Motion_LaunchFromFocusedObject, 19, 0, -16, 49152);
        Engine_ActorWaitForMove(19);
        Engine_CameraWaitForMove();
        Engine_EventSetMessage((s32)MsgSuharaIodem);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(20, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(19, 2);
        Engine_EventWait(20);
        Call3(Engine_ActorSetSpeed, 19, 78643, 39321);
        Call3(Engine_ActorWalkByAndWait, 19, 0, -16);
        Engine_ActorFaceDirection(19, 0, 0);
        Engine_EventWait(30);
        Engine_ActorFaceDirection(19, 57344, 0);
        Engine_EventWait(30);
        Engine_ActorFaceDirection(19, 0, 0);
        Engine_EventWait(30);
        Call3(Engine_ActorShowEmote, 19, 256, 40);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorSetSpeed, 19, 78643, 39321);
        Call3(Engine_ActorWalkByAndWait, 19, 0, -24);
        Engine_ActorWalkByAndWait(19, 48, 0);
        Call3(Engine_ActorFaceDirection, 19, 49152, 0);
        Engine_EventWait(30);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 19, 256, 40);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 20, 258, 40);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorFaceDirection, 19, 8192, 0);
        Engine_EventWait(20);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(21, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorFaceDirection, 19, 49152, 0);
        Engine_EventWait(30);
        Call3(Engine_ActorShowEmote, 19, 263, 40);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorStartRepeatedMotion(20, 2);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Call3(Engine_ActorSetSpeed, 0, 78643, 39321);
        Call3(Engine_ActorWalkToAndWait, 0, 368, 104);
        Engine_ActorWalkByAndWait(0, 16, 0);
        Engine_ActorFaceDirection(0, 0, 0);
        Engine_EventWait(20);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(19, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 19, 258, 50);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(20, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 20, 0);
        Call3(Engine_ActorFaceDirection, 19, 8192, 0);
        Engine_EventWait(20);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 21, 0);
        Call3(Engine_ActorFaceDirection, 19, 49152, 0);
        Engine_EventWait(40);
        Engine_ActorSetAnimationAndWait(19, 3);
        Engine_EventWait(30);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(21, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Engine_ActorFaceEachOther(19, 0, 30);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(20, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 20, 0);
        Call3(Engine_ActorFaceDirection, 19, 8192, 0);
        Engine_EventWait(40);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 21, 0);
        Call3(Engine_ActorFaceDirection, 19, 49152, 0);
        Engine_EventWait(40);
        Engine_ActorSetAnimation(0, 3);
        Engine_ActorSetAnimationAndWait(19, 3);
        Engine_EventWait(30);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(20, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 0, 256, 0);
        Call3(Engine_ActorShowEmote, 19, 256, 40);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 20, 0);
        Call3(Engine_ActorFaceDirection, 19, 8192, 0);
        Engine_EventWait(40);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 0, 256, 50);
        Engine_ActorFaceActor(0, 21, 0);
        Engine_EventWait(30);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(30);
        Engine_EventWait(10);
        Call3(Engine_ActorFaceDirection, 19, 49152, 0);
        Engine_EventWait(30);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(21, 3);
        Engine_EventWait(30);
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 19, 258, 40);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(20, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Engine_ActorShowEmote(19, 257, 50);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 20, 0);
        Call3(Engine_ActorFaceDirection, 19, 8192, 0);
        Engine_EventWait(20);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(20, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 19, 256, 40);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventWait(10);
        Engine_ActorFaceEachOther(19, 0, 0);
        Engine_EventWait(30);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(20, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 0, 258, 0);
        Call3(Engine_ActorShowEmote, 19, 258, 80);
        Call3(Engine_ActorShowEmote, 21, 258, 50);
        Engine_EventShowMessage(21, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(21, 0);
        Engine_ActorRunRepeatedMotion(21, 3);
        Engine_EventWait(20);
        Engine_EventWait(10);
        Engine_ActorFaceDirection(19, 49152, 0);
        Engine_EventWait(30);
        Engine_ActorRunRepeatedMotion(19, 2);
        Engine_EventWait(10);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(20, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Engine_ActorFaceActor(0, 20, 0);
        Engine_ActorFaceDirection(19, 8192, 0);
        Engine_EventWait(30);
        Engine_ActorSetAnimationAndWait(19, 3);
        Engine_EventWait(30);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorStartRepeatedMotion(20, 2);
        Engine_ActorRunRepeatedMotion(21, 2);
        Engine_EventWait(30);
        Engine_EventWait(10);
        Engine_ActorFaceEachOther(19, 0, 20);
        Engine_ActorWalkByAndWait(19, -12, 0);
        Engine_EventWait(20);
        Engine_EventOpenMessage(19, 0);
        if (Engine_EventChooseYesNo(0, 0) == 0) {
            Engine_EventWait(20);
            Engine_EventShowMessage(19, 0);
            gEventWork->message++;
        } else {
            Engine_EventWait(10);
            gEventWork->message++;
            Engine_EventShowMessage(19, 0);
        }
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(19, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 19, 258, 50);
        Engine_EventShowMessage(19, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 3);
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(19, 3);
        Engine_EventWait(30);
        Engine_AudioPlayCue(30);
        Call3(Engine_ActorSetSpeed, 19, 78643, 39321);
        Engine_ActorSetAnimation(19, 2);
        record = (u8 *)Engine_ActorGet(0);
        if (record != 0) {
            Engine_ActorSetDestination(19, *(s16 *)(record + 10), *(s16 *)(record + 18));
        }
        Engine_ActorWaitForMove(19);
        Engine_ActorSetPosition(19, 0, 0);
        Engine_EventWait(10);
        Audio_PlayCueFromEventWork();
        Engine_EventEnd();
    }
}
