#include "VILLAGE.H"

/* Lunpa's entrances leave the camera free; the gate's keep it on the road. */
#define LUNPA_ENTRANCE(entrance, x, z, facing) \
    { (entrance), CONDITION_ALWAYS, (x), 0, (z), (facing), 0, -1, -1, -1, -1, 0 }
#define GATE_ENTRANCE(entrance, x, z, facing) \
    { (entrance), CONDITION_ALWAYS, (x), 0, (z), (facing), 0, 32, 48, 272, 344, 0 }

const struct SceneEntrance gLunpaEntrances[] = {
    LUNPA_ENTRANCE(0, 172, 149, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_WORLD_MAP, 224, 472, FACING_NORTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_GATE, 232, 32, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_CAVE, 120, 104, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_FIRST_HOME, 248, 184, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_SECOND_HOME, 344, 232, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_THIRD_HOME, 344, 328, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_ARMS_SHOP, 232, 360, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_ITEM_SHOP, 328, 120, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_INN, 104, 184, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_TEMPLE, 48, 168, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_EIGHTH_ROOM, 216, 344, FACING_SOUTH),
    LUNPA_ENTRANCE(LUNPA_ENTRANCE_FROM_JAIL, 40, 328, FACING_SOUTH),
    { SCENE_TABLE_END },
};

const struct SceneEntrance gGateEntrances[] = {
    GATE_ENTRANCE(0, 152, 328, FACING_NORTH),
    GATE_ENTRANCE(GATE_ENTRANCE_FROM_FORTRESS, 160, 104, FACING_SOUTH),
    GATE_ENTRANCE(GATE_ENTRANCE_FROM_LUNPA, 152, 328, FACING_NORTH),
    GATE_ENTRANCE(GATE_ENTRANCE_SNEAKING_OUT, 144, 104, FACING_SOUTH),
    GATE_ENTRANCE(GATE_ENTRANCE_THROWN_OUT, 160, 224, FACING_EAST),
    { SCENE_TABLE_END },
};

/* A door leads to the room of the same number in the interiors. */
#define ROOM_EXIT(exit) SCENE_EXIT((exit), SCENE_RUNPA_SUHARA, ROOM_ENTRANCE(exit))

const u32 gLunpaExits[] = {
    SCENE_EXITS(SCENE_RUNPA_MURA),
    SCENE_EXIT(LUNPA_EXIT_TO_WORLD_MAP, SCENE_WORLD_MAP, WORLD_MAP_ENTRANCE_FROM_LUNPA),
    SCENE_EXIT(LUNPA_EXIT_TO_GATE, SCENE_RUNPA_JO_GATE, GATE_ENTRANCE_FROM_LUNPA),
    SCENE_EXIT(LUNPA_EXIT_TO_CAVE, SCENE_RUNPA_DOU, CAVE_ENTRANCE_FROM_LUNPA),
    ROOM_EXIT(LUNPA_EXIT_TO_FIRST_HOME),
    ROOM_EXIT(LUNPA_EXIT_TO_SECOND_HOME),
    ROOM_EXIT(LUNPA_EXIT_TO_THIRD_HOME),
    ROOM_EXIT(LUNPA_EXIT_TO_ARMS_SHOP),
    ROOM_EXIT(LUNPA_EXIT_TO_ITEM_SHOP),
    ROOM_EXIT(LUNPA_EXIT_TO_INN),
    ROOM_EXIT(LUNPA_EXIT_TO_TEMPLE),
    ROOM_EXIT(LUNPA_EXIT_TO_EIGHTH_ROOM),
    SCENE_EXIT(LUNPA_EXIT_TO_JAIL, SCENE_KUUPUAPPU_RUNPA, JAIL_ENTRANCE_FROM_LUNPA),
    SCENE_EXITS_END,
};

const u32 gGateExits[] = {
    SCENE_EXITS(SCENE_RUNPA_JO_GATE),
    SCENE_EXIT(GATE_EXIT_TO_FORTRESS, SCENE_RUNPA_JO, FORTRESS_ENTRANCE_FROM_GATE),
    SCENE_EXIT(GATE_EXIT_TO_LUNPA, SCENE_RUNPA_MURA, LUNPA_ENTRANCE_FROM_GATE),
    SCENE_EXITS_END,
};

/* The puddle and the glint wait at the map's far corner until Reveal places them. */
const struct ScenePlacement gLunpaPlacements[] = {
    { SPRITE_PUDDLE, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(520), 0, PIXELS(520), FACING_SOUTH, TALK_KEEP_FACING, 0 },
    { SPRITE_TOWNSPERSON_D, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(112), 0, PIXELS(168), FACING_SOUTHEAST + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_C, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(280), 0, PIXELS(352), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_TOWNSPERSON_I, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(120), 0, PIXELS(312), FACING_SOUTHEAST + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_J, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(136), 0, PIXELS(328), FACING_NORTHWEST + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_B, CONDITION_ALWAYS, ACTOR_WANDER,
      PIXELS(368), 0, PIXELS(256), FACING_WEST, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_E, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(280), 0, PIXELS(200), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY, 0 },
    { SPRITE_TOWNSPERSON_H, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(216), 0, PIXELS(40), FACING_NORTH + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_TOWNSPERSON_G, CONDITION_ALWAYS, ACTOR_WANDER,
      PIXELS(152), 0, PIXELS(184), FACING_SOUTH, TALK_FACE_PARTY, 0 },
    { SPRITE_GUARD, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(192), 0, PIXELS(448), FACING_SOUTHEAST + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_GUARD, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(256), 0, PIXELS(448), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_GLINT, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(520), 0, PIXELS(520), FACING_SOUTH + FACING_STEP, TALK_KEEP_FACING, 0 },
    { SPRITE_ITEM_ICON, FLAG_LUNPA_NUT_CAUGHT, ACTOR_FLOAT,
      PIXELS(120), 0, PIXELS(472), FACING_SOUTH, TALK_KEEP_FACING, 0 },
    { SCENE_TABLE_END, CONDITION_ALWAYS },
};

const struct ScenePlacement gGatePlacements[] = {
    { SPRITE_GUARD, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(144), 0, PIXELS(200), FACING_SOUTHEAST + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { SPRITE_GUARD, CONDITION_ALWAYS, ACTOR_STAND,
      PIXELS(176), 0, PIXELS(200), FACING_SOUTH + FACING_STEP, TALK_FACE_PARTY_AND_BACK, 0 },
    { ACTOR_GERALD, CONDITION_ALWAYS, ACTOR_STAND, 0, 0, 0, FACING_SOUTH, TALK_KEEP_FACING, 0 },
    { SCENE_TABLE_END },
};

#define TALK(actor, value) { EVENT_TALK, (actor), CONDITION_ALWAYS, (value) }
#define MIND_READ(actor, value) \
    { PSYNERGY_ON_ACTOR(ABILITY_MIND_READ), (actor), CONDITION_ALWAYS, (value) }

/* A door opens as the leader walks north into it. */
#define DOOR(trigger) \
    { TOUCH_WALKING_INTO(FACING_NORTH), (trigger), CONDITION_ALWAYS, EVENT_SCRIPT(Door_Enter) }

#define LUNPA_ROADS_AND_DOORS \
    { EVENT_EXIT, TRIGGER_WORLD_MAP_ROAD, CONDITION_ALWAYS, LUNPA_EXIT_TO_WORLD_MAP }, \
    { EVENT_EXIT, TRIGGER_GATE_ROAD, CONDITION_ALWAYS, LUNPA_EXIT_TO_GATE }, \
    { EVENT_EXIT, TRIGGER_CAVE_ROAD, CONDITION_ALWAYS, LUNPA_EXIT_TO_CAVE }, \
    DOOR(TRIGGER_FIRST_HOME_DOOR), \
    DOOR(TRIGGER_SECOND_HOME_DOOR), \
    DOOR(TRIGGER_THIRD_HOME_DOOR), \
    DOOR(TRIGGER_ARMS_SHOP_DOOR), \
    DOOR(TRIGGER_ITEM_SHOP_DOOR), \
    DOOR(TRIGGER_INN_DOOR), \
    DOOR(TRIGGER_TEMPLE_DOOR), \
    DOOR(TRIGGER_EIGHTH_ROOM_DOOR), \
    { TOUCH_WALKING_INTO(FACING_NORTH), TRIGGER_HIDDEN_PASSAGE, CONDITION_ALWAYS, \
      EVENT_SCRIPT(HiddenPassage_Enter) }

#define LUNPA_SECRETS \
    { PSYNERGY_ON_ACTOR(ABILITY_FROST), ACTOR_HIDDEN_PUDDLE, FLAG_LUNPA_PUDDLE_FROZEN, \
      EVENT_SCRIPT(HiddenPuddle_Freeze) }, \
    { PSYNERGY_IN_AREA(ABILITY_REVEAL, REVEAL_SHOWN), 0, CONDITION_ALWAYS, \
      EVENT_SCRIPT(Reveal_ShowSecrets) }, \
    { PSYNERGY_IN_AREA(ABILITY_REVEAL, REVEAL_FADED), 0, CONDITION_ALWAYS, \
      EVENT_SCRIPT(Reveal_HideSecrets) }, \
    { SEARCH(SEARCH_UNNAMED), TRIGGER_HIDDEN_SWITCH, FLAG_LUNPA_SECRETS_HIDDEN, \
      EVENT_SCRIPT(HiddenSwitch_Pull) }, \
    { SEARCH(SEARCH_UNNAMED), TRIGGER_PSYNERGY_STONE, FLAG_LUNPA_PSYNERGY_STONE, \
      FIND_PSYNERGY_STONE }, \
    { SEARCH(SEARCH_GRAVE), TRIGGER_GRAVE_SLEEP_BOMB, FLAG_LUNPA_GRAVE_SLEEP_BOMB, \
      FIND_ITEM(ITEM_SLEEP_BOMB) }, \
    { SEARCH(SEARCH_BARREL), TRIGGER_BARREL_NUT, FLAG_LUNPA_BARREL_NUT, FIND_ITEM(ITEM_NUT) }, \
    { PSYNERGY_ON_ACTOR(ABILITY_CATCH), ACTOR_FLOATING_NUT, FLAG_LUNPA_NUT_CAUGHT, \
      EVENT_SCRIPT(FloatingNut_Catch) }, \
    { SEARCH(SEARCH_UNNAMED), TRIGGER_WELL, CONDITION_ALWAYS, EVENT_SCRIPT(Well_Search) }, \
    { SCENE_EVENTS_END }

const struct SceneEvent gLunpaSealedEvents[] = {
    LUNPA_ROADS_AND_DOORS,
    TALK(ACTOR_VILLAGER_A, EVENT_SCRIPT(VillagerA_Talk)),
    TALK(ACTOR_VILLAGER_B, MsgRunpaVillageVillagerBSealed),
    TALK(ACTOR_VILLAGER_C, EVENT_SCRIPT(VillagerC_Talk)),
    TALK(ACTOR_VILLAGER_D, MsgRunpaVillageVillagerDSealed),
    TALK(ACTOR_VILLAGER_E, MsgRunpaVillageVillagerESealed),
    TALK(ACTOR_VILLAGER_F, MsgRunpaVillageVillagerFSealed),
    TALK(ACTOR_VILLAGER_G, EVENT_SCRIPT(VillagerG_Talk)),
    TALK(ACTOR_VILLAGER_H, MsgRunpaVillageVillagerHSealed),
    TALK(ACTOR_WEST_GUARD, EVENT_SCRIPT(WestGuard_Talk)),
    TALK(ACTOR_EAST_GUARD, EVENT_SCRIPT(EastGuard_Talk)),
    MIND_READ(ACTOR_VILLAGER_A, MsgRunpaVillageVillagerASealedThoughts),
    MIND_READ(ACTOR_VILLAGER_B, MsgRunpaVillageVillagerBSealedThoughts),
    MIND_READ(ACTOR_VILLAGER_C, MsgRunpaVillageVillagerCSealedThoughts),
    MIND_READ(ACTOR_VILLAGER_D, MsgRunpaVillageVillagerDSealedThoughts),
    MIND_READ(ACTOR_VILLAGER_E, MsgRunpaVillageVillagerESealedThoughts),
    MIND_READ(ACTOR_VILLAGER_F, MsgRunpaVillageVillagerFSealedThoughts),
    MIND_READ(ACTOR_VILLAGER_G, MsgRunpaVillageVillagerGSealedThoughts),
    MIND_READ(ACTOR_VILLAGER_H, MsgRunpaVillageVillagerHSealedThoughts),
    MIND_READ(ACTOR_WEST_GUARD, MsgRunpaVillageWestGuardSealedThoughts),
    MIND_READ(ACTOR_EAST_GUARD, EVENT_SCRIPT(EastGuard_MindRead)),
    LUNPA_SECRETS,
};

const struct SceneEvent gLunpaReopenedEvents[] = {
    LUNPA_ROADS_AND_DOORS,
    TALK(ACTOR_VILLAGER_A, MsgRunpaVillageVillagerAReopened),
    TALK(ACTOR_VILLAGER_B, EVENT_SCRIPT(VillagerB_Shivers)),
    TALK(ACTOR_VILLAGER_C, MsgRunpaVillageVillagerCReopened),
    TALK(ACTOR_VILLAGER_D, EVENT_SCRIPT(VillagerD_Talk)),
    TALK(ACTOR_VILLAGER_E, MsgRunpaVillageVillagerEReopened),
    TALK(ACTOR_VILLAGER_F, MsgRunpaVillageVillagerFReopened),
    TALK(ACTOR_VILLAGER_G, MsgRunpaVillageVillagerGReopened),
    TALK(ACTOR_VILLAGER_H, MsgRunpaVillageVillagerHReopened),
    TALK(ACTOR_WEST_GUARD, MsgRunpaVillageWestGuardReopened),
    TALK(ACTOR_EAST_GUARD, MsgRunpaVillageEastGuardReopened),
    MIND_READ(ACTOR_VILLAGER_A, MsgRunpaVillageVillagerAReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_B, MsgRunpaVillageVillagerBReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_C, MsgRunpaVillageVillagerCReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_D, MsgRunpaVillageVillagerDReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_E, MsgRunpaVillageVillagerEReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_F, MsgRunpaVillageVillagerFReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_G, MsgRunpaVillageVillagerGReopenedThoughts),
    MIND_READ(ACTOR_VILLAGER_H, MsgRunpaVillageVillagerHReopenedThoughts),
    MIND_READ(ACTOR_WEST_GUARD, MsgRunpaVillageWestGuardReopenedThoughts),
    MIND_READ(ACTOR_EAST_GUARD, EVENT_SCRIPT(EastGuard_MindRead)),
    LUNPA_SECRETS,
};

const struct SceneEvent gGateEvents[] = {
    { EVENT_EXIT, TRIGGER_LUNPA_ROAD, CONDITION_ALWAYS, GATE_EXIT_TO_LUNPA },
    { EVENT_EXIT, TRIGGER_THIRD_ROAD, CONDITION_ALWAYS, GATE_EXIT_THIRD },
    { PSYNERGY_IN_AREA(ABILITY_CLOAK, CLOAK_CAST), 0, CONDITION_ALWAYS, EVENT_SCRIPT(Cloak_Begin) },
    { PSYNERGY_IN_AREA(ABILITY_CLOAK, CLOAK_FADED), 0, CONDITION_ALWAYS, EVENT_SCRIPT(Cloak_End) },
    { EVENT_TOUCH, TRIGGER_FORTRESS_DOOR, FLAG_GATE_FORTRESS_ENTERED,
      EVENT_SCRIPT(FortressGate_Enter) },
    { EVENT_TOUCH, TRIGGER_GUARDED_GROUND, FLAG_GATE_GUARDS_BLOCKING,
      EVENT_SCRIPT(Guards_BlockGate) },
    { EVENT_TOUCH, TRIGGER_FORTRESS_APPROACH, CONDITION_ALWAYS,
      EVENT_SCRIPT(Gerald_RefusesToReturn) },
    { EVENT_RAISED, TRIGGER_PARTY_SPOTTED, CONDITION_ALWAYS, EVENT_SCRIPT(Guards_CatchParty) },
    TALK(ACTOR_LEFT_GUARD, EVENT_SCRIPT(LeftGuard_Talk)),
    TALK(ACTOR_RIGHT_GUARD, EVENT_SCRIPT(RightGuard_Talk)),
    MIND_READ(ACTOR_LEFT_GUARD, EVENT_SCRIPT(LeftGuard_MindRead)),
    MIND_READ(ACTOR_RIGHT_GUARD, EVENT_SCRIPT(RightGuard_MindRead)),
    { SEARCH(SEARCH_UNNAMED), TRIGGER_WELL, CONDITION_ALWAYS, EVENT_SCRIPT(Well_Search) },
    { SCENE_EVENTS_END },
};

/* Each door swings open in two steps of cells copied over the doorway. */
const u16 gLunpaDoorSteps[DOOR_COUNT][11] = {
    { MAP_CELL_STEP(38, 35, 2, 2, 5), MAP_CELL_STEP(40, 35, 2, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(42, 35, 2, 2, 5), MAP_CELL_STEP(44, 35, 2, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(46, 33, 2, 2, 5), MAP_CELL_STEP(48, 33, 2, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(46, 35, 2, 2, 5), MAP_CELL_STEP(48, 35, 2, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(50, 33, 2, 2, 5), MAP_CELL_STEP(52, 33, 2, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(50, 35, 2, 2, 5), MAP_CELL_STEP(52, 35, 2, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(42, 33, 4, 2, 5), MAP_CELL_STEP(38, 33, 4, 2, 5), MAP_CELL_STEPS_END },
    { MAP_CELL_STEP(54, 33, 2, 2, 5), MAP_CELL_STEP(56, 33, 2, 2, 5), MAP_CELL_STEPS_END },
};

/* The doorway cells each door's steps are copied onto. */
const struct LunpaDoor gLunpaDoors[] = {
    { gLunpaDoorSteps[0], 46, 9 },
    { gLunpaDoorSteps[1], 52, 12 },
    { gLunpaDoorSteps[2], 52, 18 },
    { gLunpaDoorSteps[3], 45, 20 },
    { gLunpaDoorSteps[4], 51, 5 },
    { gLunpaDoorSteps[5], 37, 9 },
    { gLunpaDoorSteps[6], 33, 6 },
    { gLunpaDoorSteps[7], 44, 17 },
};

/* Nothing in the scene reads this word. */
const u32 gLunpaUnusedWord = 0;
