#include "TYPES.H"
#include "FIELD_EVENT.H"
#include "FIELD_SCENE.H"
#include "KYUDEN.H"
extern u8 MsgTorebiCallsName[];
extern u8 MsgTorebiIodemIodem[];
extern u8 MsgTorebiLikeSleep[];
extern u8 MsgTorebiWaitingCompanions[];

void FieldScene_RunScene3b8SequenceA(void)
{
    s32 record;
    s16 dir;
    u16 facing;

    record = Engine_ActorGet(0);
    dir = (*(u16 *)(record + 6) + 0x2000) & -0x4000;
    Engine_EventBegin();
    Battle_ResetEffectCounterFar();
    Engine_EventSetMessage((s32)MsgTorebiLikeSleep);
    Value2(Engine_EventOpenMessage, -1, 0);
    if (Value2(Engine_EventChooseYesNo, 0, 0) != 0) {
    } else {
        if (Value1(Engine_GameFlagIsSet, 0x96a) != 0) {
            Engine_EventWait(20);
            Inn_PlaySleepFar(0);
            goto L_02000fe2;
        }
        Engine_EventWait(20);
        facing = dir;
        if (facing == 0) {
            Actor_WalkToAndWait(ACTOR_PARTY_LEADER, 128, 120);
        }
        if (facing == 0x8000) {
            Engine_ActorWalkToAndWait(0, 240, 120);
        }
        Engine_ActorWalkToAndWait(0, 184, 120);
        Engine_ActorFaceDirection(0, 0, 0);
        Engine_EventWait(10);
        Motion_LaunchFromFocusedObjectFar(1, 16, 0, 0x8000);
        Object_RefreshSelectorByIdFar(1);
        Engine_EventWait(10);
        Engine_EventShowMessage(1, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 3);
        Event_Wait(20);
        Call3(Engine_ActorSetSpeed, 1, 0x10000, 0x8000);
        Actor_WalkByAndWait(ACTOR_GERALD, 40, 0);
        Call3(Engine_ActorWalkByAndWait, 1, 0, -32);
        Call3(Engine_ActorFaceDirection, 1, 0x6000, 0);
        Engine_EventWait(20);
        Engine_ActorFaceDirection(0, 0x8000, 0);
        Engine_EventWait(20);
        Call4(Motion_LaunchFromFocusedObjectFar, 2, -16, 0, 0);
        Object_RefreshSelectorByIdFar(2);
        Engine_EventWait(10);
        Engine_EventShowMessage(2, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 3);
        Engine_EventWait(20);
        Call3(Engine_ActorSetSpeed, 2, 0x10000, 0x8000);
        Call3(Engine_ActorWalkByAndWait, 2, -40, 0);
        Engine_ActorWalkByAndWait(2, 0, 40);
        Call3(Engine_ActorFaceDirection, 2, 0xe000, 0);
        Engine_EventWait(20);
        Engine_ActorFaceDirection(0, 0, 0);
        Engine_EventWait(20);
        Motion_LaunchFromFocusedObjectFar(3, 16, 0, 0x8000);
        Object_RefreshSelectorByIdFar(3);
        Engine_EventWait(10);
        Engine_EventShowMessage(3, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 3);
        Engine_EventWait(20);
        Call3(Engine_ActorSetSpeed, 3, 0x10000, 0x8000);
        Engine_ActorWalkByAndWait(3, 40, 0);
        Engine_ActorWalkByAndWait(3, 0, 40);
        Call3(Engine_ActorFaceDirection, 3, 0xa000, 0);
        Engine_EventWait(20);
        Call4(Engine_CameraMoveTo, -1, -1, -1, 0);
        Call3(Engine_ActorWalkByAndWait, 0, -56, 0);
        Call3(Engine_ActorWalkByAndWait, 0, 0, -32);
        Call3(Engine_ActorFaceDirection, 0, 0x2000, 0);
        Engine_EventWait(30);
        Engine_ActorSetAnimationAndWait(3, 3);
        Event_Wait(10);
        Engine_EventShowMessage(3, 0);
        Engine_ActorSetAnimationAndWait(1, 3);
        ((void (*)())Engine_EventWait)(10);
        if (Value1(Engine_GameFlagIsSet, 0x96a) == 0) {
            Engine_EventShowMessage(1, 0);
        } else {
            AdvanceMessageCursor(1);
        }
        Engine_ActorSetAnimationAndWait(2, 3);
        Engine_EventWait(10);
        if (GameFlag_IsSet(0x96a) == 0) {
            Engine_EventShowMessage(2, 0);
        } else {
            AdvanceMessageCursor(1);
        }
        Engine_EventWait(20);
        Engine_ActorFaceDirection(0, 0, 0);
        Call3(Engine_ActorFaceDirection, 1, 0x8000, 0);
        Call3(Engine_ActorFaceDirection, 3, 0x8000, 0);
        Engine_ActorFaceDirection(2, 0, 0);
        Inn_PlaySleepFar(0);
        Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x2000, 0);
        Call3(Engine_ActorFaceDirection, 1, 0x6000, 0);
        Call3(Engine_ActorFaceDirection, 3, 0xa000, 0);
        Call3(Engine_ActorFaceDirection, 2, 0xe000, 0);
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(1, 3);
        Engine_EventWait(10);
        Engine_EventShowMessage(1, 0);
        Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
        ((void (*)())Engine_EventWait)(10);
        if (Value1(Engine_GameFlagIsSet, 0x96a) == 0) {
            Engine_EventShowMessage(2, 0);
        } else {
            AdvanceMessageCursor(1);
        }
        Engine_ActorSetAnimationAndWait(3, 3);
        Engine_EventWait(10);
        if (GameFlag_IsSet(0x96a) == 0) {
            Event_ShowMessage(ACTOR_MIA, 0);
        } else {
            AdvanceMessageCursor(1);
        }
        Engine_ActorWalkByAndWait(1, 0, 32);
        Call3(Engine_ActorWalkBy, 1, -112, 0);
        Call3(Engine_ActorWalkByAndWait, 3, 0, -40);
        Actor_WalkBy(ACTOR_MIA, -112, 0);
        Event_Wait(50);
        Call3(Engine_ActorWalkByAndWait, 2, 0, -24);
        Actor_WaitForMove(ACTOR_GERALD);
        Call3(Engine_ActorFaceDirection, 0, 0x4000, 0);
        Call3(Engine_ActorWalkByAndWait, 1, 0, -16);
        Engine_ActorWaitForMove(3);
        Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
        Engine_EventWait(20);
        Event_ShowMessage(ACTOR_GERALD, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 3);
        Engine_EventWait(20);
        Call3(Engine_ActorSetSpeed, 1, 0x13333, 0x9999);
        Call3(Engine_ActorSetSpeed, 2, 0x13333, 0x9999);
        Call3(Engine_ActorSetSpeed, 3, 0x13333, 0x9999);
        Engine_ActorSetAnimation(1, 2);
        record = Value1(Engine_ActorGet, 0);
        if (record != 0) {
            ObjectMotion_ResetAndSetPositionFar(1, *(s16 *)(record + 10), *(s16 *)(record + 18));
        }
        Actor_WaitForMove(ACTOR_GERALD);
        Engine_ActorSetPosition(1, 0, 0);
        Engine_ActorSetAnimation(3, 2);
        record = Value1(Engine_ActorGet, ACTOR_PARTY_LEADER);
        if (record != 0) {
            ObjectMotion_ResetAndSetPositionFar(3, *(s16 *)(record + 10), *(s16 *)(record + 18));
        }
        Actor_WaitForMove(ACTOR_MIA);
        Engine_ActorSetPosition(3, 0, 0);
        Engine_ActorSetAnimation(2, 2);
        record = Value1(Engine_ActorGet, 0);
        if (record != 0) {
            ObjectMotion_ResetAndSetPositionFar(2, *(s16 *)(record + 10), *(s16 *)(record + 18));
        }
        Engine_ActorWaitForMove(2);
        Engine_ActorSetPosition(2, 0, 0);
        GameFlag_Set(0x96a);
    }
    Engine_EventEnd();
    L_02000fe2:;
}

void RunPrimaryEffectSequence(void)
{
    Call1_scene_effect_sequence_head(Engine_GameFlagSet, 2411);
    Call0(Engine_EventBegin);
    Call0(Battle_ResetEffectCounterFar);
    Call1_scene_effect_sequence_head(Engine_EventSetMessage, (s32)MsgTorebiIodemIodem);
    Call3_scene_effect_sequence_head(Engine_ActorWalkToAndWait, 0, 520, 424);
    Call3_scene_effect_sequence_head(Engine_ActorFaceDirection, 0, 57344, 0);
    Camera_MoveTo(36700160, -1, 24117248, 1);
    Call0(Engine_CameraWaitForMove);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 20, 65536, 32768);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 20, 40, 0);
    Call3_scene_effect_sequence_head(Engine_ActorWalkToAndWait, 20, 584, 360);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 257, 40);
    Call3_scene_effect_sequence_head(Engine_ActorFaceDirection, 20, 32768, 0);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 21, 131072, 65536);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 22, 131072, 65536);
    Call3_scene_effect_sequence_head(Engine_ActorWalkTo, 21, 528, 352);
    Call3_scene_effect_sequence_head(Engine_ActorWalkToAndWait, 22, 528, 368);
    Call1_scene_effect_sequence_head(Engine_TaskWait, 3);
    Actor_SetAnimation(21, 1);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(22, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(20, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 20, -16, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimation(21, 4);
    Actor_SetAnimationAndWait(22, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 261, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 21, 258, 40);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 21, 65536, 32768);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 21, 8, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 257, 80);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 22, 258, 40);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 22, 65536, 32768);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 22, 8, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimation(21, 3);
    Actor_SetAnimationAndWait(22, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(21, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(22, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 261, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 21, 257, 40);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 258, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(22, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(21, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 258, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorFaceEachOther, 21, 22, 60);
    Call3_scene_effect_sequence_head(Engine_ActorFaceActor, 21, 20, 0);
    Call3_scene_effect_sequence_head(Engine_ActorFaceActor, 22, 20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(20, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 21, 256, 40);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(22, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAttachedEffect(20, 258);
    Actor_RunRepeatedMotion(20, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 21, 257, 40);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 22, 257, 40);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorFaceEachOther, 21, 22, 60);
    Call3_scene_effect_sequence_head(Engine_ActorFaceActor, 21, 20, 0);
    Call3_scene_effect_sequence_head(Engine_ActorFaceActor, 22, 20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 261, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(21, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(22, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(22, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 258, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(21, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 22, 256, 40);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 258, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 21, 257, 40);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorFaceEachOther, 21, 22, 60);
    Call3_scene_effect_sequence_head(Engine_ActorFaceActor, 21, 20, 0);
    Call3_scene_effect_sequence_head(Engine_ActorFaceActor, 22, 20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(20, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAttachedEffect(21, 258);
    Actor_SetAttachedEffect(22, 258);
    Actor_StartRepeatedMotion(21, 2);
    Actor_RunRepeatedMotion(22, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Call3_scene_effect_sequence_head(Engine_ActorFaceDirection, 20, 0, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(21, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(22, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(20, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorFaceDirection, 20, 32768, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(21, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(21, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorShowEmote, 20, 261, 40);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(22, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(22, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 40);
    Call3_scene_effect_sequence_head(Engine_ActorFaceEachOther, 21, 22, 60);
    Actor_SetAnimationAndWait(21, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Actor_SetAnimationAndWait(22, 3);
    Call1_scene_effect_sequence_head(Engine_EventWait, 20);
    Call3_scene_effect_sequence_head(Engine_ActorFaceDirection, 22, 16384, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 40);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 21, 85196, 42598);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 22, 85196, 42598);
    Call3_scene_effect_sequence_head(Engine_ActorWalkBy, 21, 0, 120);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 22, 0, 120);
    Call3_scene_effect_sequence_head(Engine_ActorSetPosition, 21, 0, 0);
    Call3_scene_effect_sequence_head(Engine_ActorSetPosition, 22, 0, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_RunRepeatedMotion(20, 2);
    Call1_scene_effect_sequence_head(Engine_EventWait, 40);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 20, 52428, 26214);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 20, -16, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Event_ShowMessage(20, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 10);
    Actor_SetAnimationAndWait(20, 4);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call3_scene_effect_sequence_head(Engine_ActorFaceDirection, 20, 0, 0);
    Call1_scene_effect_sequence_head(Engine_EventWait, 30);
    Call3_scene_effect_sequence_head(Engine_ActorSetSpeed, 20, 65536, 32768);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 20, 120, 0);
    Call3_scene_effect_sequence_head(Engine_ActorWalkByAndWait, 20, 60, 0);
    Call3_scene_effect_sequence_head(Engine_ActorSetPosition, 20, 0, 0);
    Call0(Engine_EventEnd);
}

void FieldScene_RunBranchingActorSequence(void)
{
    s32 record;
    s32 step;
    s32 pick;
    s32 state;
    u8 *work;

    Engine_EventBegin();
    Engine_EventSetMessage((s32)MsgTorebiCallsName);
    Engine_ActorSetAnimation(0, 31);
    record = Engine_ActorGet(0);
    Engine_ActorSetSpriteFlags(record, 0);
    Call3(Engine_ActorSetPosition, 1, 0x680000, 0x680000);
    Call3(Engine_ActorSetPosition, 3, 0x580000, 0x780000);
    Call3(Engine_ActorSetPosition, 2, 0x780000, 0x780000);
    Call3(Engine_ActorFaceDirection, 1, 0x4000, 0);
    Engine_ActorFaceDirection(3, 0, 0);
    Call3(Engine_ActorFaceDirection, 2, 0x8000, 0);
    state = (s32)gWork[0];
    *(s32 *)(state + 0x1c0) = 0x100;
    *(s32 *)(state + 0x1c8) = 12;
    Engine_TaskWait(1);
    DisplayTransition_InitializeBattleEffectStateFar(9);
    work = gWork[4];
    SetHalf((u16 *)(work + 0x52a), 0);
    SetHalf((u16 *)(work + 0x534), 0x1f1f);
    SetHalf((u16 *)(work + 0x536), 1);
    Event_SetStatus1c6Far();
    Event_WaitValue1c8FramesFar();
    for (step = 1; step <= 5; step++) {
        Engine_TaskWait(3);
        *(u16 *)(work + 0x52a) = step;
    }
    Engine_EventWait(40);
    Engine_ActorRunRepeatedMotion(0, 2);
    Engine_EventWait(30);
    for (step = 5; step <= 31; step++) {
        Engine_TaskWait(3);
        *(u16 *)(work + 0x52a) = step;
    }
    SetHalf((u16 *)(work + 0x536), 31);
    state = (s32)gWork[0];
    *(s32 *)(state + 0x1c0) = 0x209;
    *(s32 *)(state + 0x1c8) = 24;
    Engine_EventWait(20);
    Call3(Engine_ActorShowEmote, 1, 0x100, 50);
    Engine_ActorFaceActor(1, 0, 40);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 2, 0x101, 40);
    Call3(Engine_ActorFaceDirection, 2, 0xe000, 0);
    Engine_EventWait(30);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_EventShowMessage(3, 0);
    Engine_ActorFaceDirection(3, 0xe000, 0);
    Engine_EventWait(30);
    Engine_ActorRunRepeatedMotion(3, 2);
    Engine_EventWait(30);
    Call3(Engine_ActorSetSpeed, 3, 0x10000, 0x8000);
    Call3(Engine_ActorWalkByAndWait, 3, 0, -40);
    Engine_ActorWalkByAndWait(3, 32, 0);
    Engine_ActorFaceDirection(3, 0x2000, 0);
    Engine_EventWait(10);
    Engine_EventShowMessage(3, 0);
    record = Engine_ActorGet(0);
    *(s32 *)(record + 16) += -0x30000;
    record = Engine_ActorGet(0);
    *(s32 *)(record + 64) += -0x30000;
    Engine_ActorSetAnimation(0, 32);
    Engine_EventWait(40);
    Engine_ActorSetAnimationAndWait(0, 34);
    Engine_EventWait(30);
    Engine_ActorSetAnimation(0, 33);
    Engine_EventWait(40);
    Engine_ActorSetAnimationAndWait(1, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 0, 0x102, 80);
    Call3(Engine_ActorShowEmote, 2, 0x100, 50);
    Value2(Engine_EventOpenMessage, 2, 0);
    if (Engine_EventChooseYesNo(-1, 0) == 0) {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 33);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 1, 0x103, 40);
        Engine_ActorJump(1, 4, 13);
        Engine_ActorJump(1, 4, 30);
        Engine_EventShowMessage(1, 0);
        *(u16 *)(gWork[0] + 0x1d8) += 1;
    } else {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 34);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 1, 0x103, 40);
        Engine_ActorJump(1, 4, 13);
        Engine_ActorJump(1, 4, 30);
        *(u16 *)(gWork[0] + 0x1d8) += 1;
        Engine_EventShowMessage(1, 0);
    }
    Engine_EventWait(10);
    Engine_ActorFaceDirection(2, 0xa000, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(2, 4);
    Engine_EventWait(20);
    Call3(Engine_ActorFaceDirection, 1, 0x2000, 0);
    Engine_EventWait(30);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(40);
    Call3(Engine_ActorFaceDirection, 1, 0xe000, 0);
    Engine_ActorFaceDirection(2, 0xe000, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(1, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Engine_ActorFaceDirection(3, 0x6000, 0);
    Engine_EventWait(50);
    Engine_ActorFaceDirection(3, 0x2000, 0);
    Engine_EventWait(35);
    Engine_ActorShowEmote(3, 0x108, 50);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(3, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(20);
    Value2(Engine_EventOpenMessage, 2, 0);
    if (Engine_EventChooseYesNo(-1, 0) == 0) {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 33);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 1, 0x107, 40);
        Engine_EventShowMessage(1, 0);
        pick = 0;
        *(u16 *)(gWork[0] + 0x1d8) += 1;
    } else {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(0, 34);
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 1, 0x107, 40);
        *(u16 *)(gWork[0] + 0x1d8) += 1;
        pick = 1;
        Engine_EventShowMessage(1, 0);
    }
    Engine_EventWait(10);
    Engine_ActorFaceDirection(2, 0xa000, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(2, 4);
    Engine_EventWait(20);
    Call3(Engine_ActorFaceDirection, 1, 0x2000, 0);
    Engine_EventWait(30);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(40);
    Call3(Engine_ActorFaceDirection, 1, 0xe000, 0);
    Engine_ActorFaceDirection(2, 0xe000, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(1, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Engine_ActorFaceDirection(3, 0x6000, 0);
    Engine_EventWait(50);
    Engine_ActorFaceDirection(3, 0x2000, 0);
    Engine_EventWait(35);
    Engine_ActorShowEmote(3, 0x108, 50);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(3, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(3, 0);
    if (pick == 0) {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(2, 3);
        Engine_EventWait(30);
        Engine_EventShowMessage(2, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(1, 2);
        Engine_EventWait(30);
        Engine_EventShowMessage(1, 0);
        *(u16 *)(gWork[0] + 0x1d8) += 2;
    } else {
        *(u16 *)(gWork[0] + 0x1d8) += 2;
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(2, 4);
        Engine_EventWait(20);
        Engine_EventShowMessage(2, 0);
        Engine_EventWait(10);
        Engine_ActorRunRepeatedMotion(1, 2);
        Engine_EventWait(20);
        Engine_EventShowMessage(1, 0);
    }
    Engine_EventWait(10);
    Engine_ActorShowEmote(0, 0x102, 60);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(1, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(20);
    Engine_ActorFaceEachOther(2, 3, 40);
    Call3(Engine_ActorFaceDirection, 3, 0x2000, 0);
    Engine_ActorFaceDirection(2, 0xe000, 0);
    Engine_EventWait(30);
    while ((gKeysHeld & 240) == 0) {
        Engine_TaskWait(1);
    }
    Engine_ActorJump(0, 6, 0);
    Call3(Engine_ActorSetSpeed, 0, 0x1e666, 0xf333);
    Engine_ActorWalkByAndWait(0, -32, -8);
    record = Engine_ActorGet(0);
    Engine_ActorSetSpriteFlags(record, 1);
    Engine_EventWait(20);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0x4000, 0);
    Engine_ActorFaceDirection(2, 0xc000, 0);
    Engine_EventWait(20);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(3, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimationAndWait(2, 3);
    Engine_EventWait(30);
    Call3(Engine_ActorFaceDirection, 0, 0x4000, 0);
    Engine_ActorFaceDirection(1, 0x2000, 0);
    Engine_EventWait(30);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimation(0, 3);
    Engine_ActorSetAnimation(1, 3);
    Engine_ActorSetAnimationAndWait(3, 3);
    Engine_EventWait(30);
    Call3(Engine_ActorSetSpeed, 1, 0x13333, 0x9999);
    Call3(Engine_ActorSetSpeed, 3, 0x13333, 0x9999);
    Call3(Engine_ActorSetSpeed, 2, 0x13333, 0x9999);
    Engine_ActorSetAnimation(1, 2);
    record = Engine_ActorGet(0);
    if (record != 0) {
        ObjectMotion_ResetAndSetPositionFar(1, *(s16 *)(record + 10), *(s16 *)(record + 18));
    }
    Engine_ActorWaitForMove(1);
    Engine_ActorSetPosition(1, 0, 0);
    Engine_ActorSetAnimation(3, 2);
    record = Engine_ActorGet(0);
    if (record != 0) {
        ObjectMotion_ResetAndSetPositionFar(3, *(s16 *)(record + 10), *(s16 *)(record + 18));
    }
    Engine_ActorWaitForMove(3);
    Engine_ActorSetPosition(3, 0, 0);
    Engine_ActorSetAnimation(2, 2);
    record = Engine_ActorGet(0);
    if (record != 0) {
        ObjectMotion_ResetAndSetPositionFar(2, *(s16 *)(record + 10), *(s16 *)(record + 18));
    }
    Engine_ActorWaitForMove(2);
    Engine_ActorSetPosition(2, 0, 0);
    Engine_EventWait(10);
    Engine_EventEnd();
}

void FieldScene_RunMainCutsceneSequence(void)
{
    s32 carry;
    s16 *position;

    carry = Value1(Engine_AudioPlayCue, 30);
    Call1(Engine_EventBegin, carry);
    carry = Value1(Engine_EventSetMessage, (s32)MsgTorebiWaitingCompanions);
    carry = Event_SetStatus1c6Far(carry);
    Event_WaitValue1c8FramesFar(carry);
    carry = Value4(Engine_CameraMoveTo, 0xd80000, -1, 0x2e00000, 1);
    Call1(Engine_CameraWaitForMove, carry);
    Engine_EventWait(20);
    Engine_EventWait(10);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorSetSpeed, 14, 0xcccc, 0x6666);
    Engine_ActorWalkByAndWait(14, 0, 16);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    carry = Object_AttachWorkTargetToObjectFar(0, 1);
    Call1(Engine_CameraWaitForMove, carry);
    Engine_EventWait(40);
    Call3(Engine_ActorSetSpeed, 0, 0x10000, 0x8000);
    Value3(Engine_ActorWalkToAndWait, 0, 208, 0x2f8);
    Engine_EventWait(10);
    Camera_MoveTo(0xd80000, -1, 0x2e00000, 1);
    Call4(Motion_LaunchFromFocusedObjectFar, 1, -16, 16, 0xc000);
    Call4(Motion_LaunchFromFocusedObjectFar, 3, 0, 24, 0xc000);
    Value4(Motion_LaunchFromFocusedObjectFar, 2, 16, 16, 0xc000);
    Engine_ActorWaitForMove(1);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);

    if (Value1(Engine_GameFlagIsSet, 0x951) != 0) {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(20, 3);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_EventWait(10);
        Actor_FaceDirection(14, 0xa000, 0);
        Engine_EventWait(30);
        Engine_ActorSetAnimationAndWait(14, 3);
        Engine_EventWait(20);
        Engine_EventShowMessage(14, 0);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(20, 3);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Call3(Engine_ActorFaceDirection, 20, 0xc000, 0);
        Engine_EventWait(20);
        Call3(Engine_ActorSetSpeed, 20, 0x10000, 0x8000);
        Value3(Engine_ActorWalkByAndWait, 20, 0, -16);
        Event_Wait(40);
        Engine_ActorSetAnimationAndWait(20, 3);
        Engine_EventWait(40);
        Value3(Engine_ActorFaceDirection, 20, 0x4000, 0);
        Engine_EventWait(20);
        Engine_ActorWalkByAndWait(20, 0, 32);
        Engine_ActorFaceDirection(14, 0x8000, 0);
        Engine_EventWait(10);
        Engine_ActorFaceDirection(20, 0, 0);
        Engine_EventWait(30);
        Engine_ActorSetAnimationAndWait(20, 3);
        Engine_EventWait(30);
        Value3(Engine_ActorFaceDirection, 20, 0x4000, 0);
        Engine_EventWait(20);
        Value3(Engine_ActorSetSpeed, 20, 0xcccc, 0x6666);
        Engine_ActorGet(20)->unknown_5a &= 0xfe;
        Value3(Engine_ActorWalkByAndWait, 20, 0, -16);
        Engine_ActorGet(20)->unknown_5a |= 1;
        Value3(Engine_ActorFaceDirection, 14, 0x4000, 0);
        Engine_EventWait(40);
        Call3(Engine_ActorSetSpeed, 14, 0xcccc, 0x6666);
        Engine_ActorWalkByAndWait(14, 0, 16);
        Engine_EventWait(40);
        UiText_DrawQuantity(164, 2);
        Engine_EventShowMessage(-1, 0);
        Engine_ItemShowFound(164, 3);
        Engine_PartyGiveItem(164, 0);
        Engine_ActorFaceDirection(0, 0xc000, 0);
        Engine_EventWait(30);
        Call3(Engine_ActorWalkByAndWait, 14, 0, -16);
        Actor_FaceDirection(14, 0x4000, 0);
        Engine_EventWait(30);
        Engine_ActorRunRepeatedMotion(14, 2);
        Engine_EventWait(20);
        Engine_EventOpenMessage(14, 0);
        AdvanceMessage(2);
    } else {
        AdvanceMessage(5);
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(20, 3);
        Engine_EventWait(20);
        Engine_EventShowMessage(20, 0);
        Engine_ActorFaceDirection(14, 0xa000, 0);
        Event_Wait(40);
        Actor_SetAnimationAndWait(14, 3);
        Engine_EventWait(20);
        Actor_SetAnimationAndWait(20, 3);
        Engine_EventWait(30);
        Actor_FaceDirection(14, 0x4000, 0);
        Engine_EventWait(30);
        Engine_ActorRunRepeatedMotion(14, 2);
        Engine_EventWait(20);
        Engine_EventOpenMessage(14, 0);
    }

    if (Event_ChooseYesNo(0, 0) == 0) {
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(20, 3);
        Event_Wait(20);
        Engine_EventShowMessage(20, 0);
        AdvanceMessage(1);
    } else {
        Event_Wait(10);
        Engine_ActorSetAnimationAndWait(20, 3);
        Event_Wait(20);
        AdvanceMessage(1);
        Engine_EventShowMessage(20, 0);
    }

    Event_Wait(10);
    Actor_FaceDirection(14, 0xa000, 0);
    Engine_EventWait(20);
    Actor_SetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_SetAnimationAndWait(20, 3);
    Event_Wait(30);
    Engine_EventWait(10);
    Actor_Jump(ACTOR_GERALD, 4, 13);
    Engine_ActorJump(1, 4, 30);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Actor_SetSpeed(14, 0x19999, 0xcccc);
    Engine_ActorWalkByAndWait(20, 0, 16);
    Task_Wait(2);
    Actor_FaceDirection(20, 0x2000, 0);
    Event_Wait(10);
    Engine_EventShowMessage(20, 0);
    Event_Wait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Event_Wait(30);
    Engine_ActorFaceActor(14, 20, 30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Actor_FaceEachOther(14, ACTOR_GERALD, 0);
    Engine_EventWait(40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(30);
    Engine_ActorFaceActor(1, 2, 30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(20);
    Engine_ActorFaceActor(2, 1, 30);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_ActorShowEmote(1, 0x106, 50);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Event_Wait(10);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 2, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Event_Wait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 0);
    Engine_ActorFaceEachOther(3, 2, 50);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Engine_ActorFaceDirection(2, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(20, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Actor_SetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 2, 0x101, 40);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Engine_EventOpenMessage(14, 0);
    if (Engine_EventChooseYesNo(0, 0) == 0) {
        Engine_EventWait(20);
        Engine_ActorSetAnimationAndWait(14, 3);
        Engine_EventWait(30);
        Engine_EventShowMessage(14, 0);
        AdvanceMessage(1);
    } else {
        Engine_EventWait(10);
        Engine_ActorSetAnimationAndWait(14, 4);
        Engine_EventWait(20);
        AdvanceMessage(1);
        Event_ShowMessage(14, 0);
    }

    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x102, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimation(0, 3);
    Actor_SetAnimation(ACTOR_GERALD, 3);
    Engine_ActorSetAnimation(3, 3);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Engine_EventWait(50);
    Engine_ActorFaceActor(14, 20, 60);
    Engine_ActorFaceDirection(14, 0x4000, 0);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x102, 40);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(20, 4);
    Engine_EventWait(20);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorShowEmote, 0, 0x102, 40);
    Event_Wait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 50);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, 3);
    Engine_ActorSetAnimationAndWait(1, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Event_ShowMessage(14, 0);
    Event_Wait(10);
    Call3(Engine_ActorShowEmote, 3, 0x100, 40);
    Engine_EventShowMessage(3, 0);
    Event_Wait(10);
    Call3(Engine_ActorShowEmote, 14, 0x102, 50);
    Engine_ActorFaceActor(20, 14, 50);
    Event_Wait(10);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Engine_EventWait(20);
    Engine_ActorFaceEachOther(1, 0, 0);
    Engine_ActorFaceEachOther(3, 2, 50);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 2, 0xc000, 0);
    Engine_EventWait(50);
    Engine_ActorFaceDirection(20, 0x2000, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Event_Wait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(20);
    Engine_ActorFaceDirection(14, 0x8000, 0);
    Engine_EventWait(40);
    Call3(Engine_ActorShowEmote, 14, 0x105, 60);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 2, 0x100, 40);
    Engine_EventShowMessage(2, 0);
    Event_Wait(10);
    Engine_ActorFaceEachOther(14, 2, 40);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 0);
    Engine_ActorFaceEachOther(3, 2, 60);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Engine_ActorFaceDirection(2, 0xc000, 0);
    Engine_EventWait(50);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 40);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 2);
    Engine_EventWait(20);
    Engine_EventOpenMessage(1, 0);
    if (Engine_EventChooseYesNo(0, 0) == 0) {
        Engine_EventWait(20);
        Engine_EventShowMessage(1, 0);
        AdvanceMessage(3);
    } else {
        do {
            Engine_EventWait(10);
        } while (0);
        {
            u8 **scene_address = (u8 **)&gEventWork;

            AdvanceMessageAt(scene_address, 1);
            Engine_EventOpenMessage(1, 0);
            if (Event_ChooseYesNo(0, 0) == 0) {
                Engine_EventWait(20);
                Engine_EventShowMessage(1, 0);
                AdvanceMessageAt(scene_address, 1);
            } else {
                AdvanceMessageAt(scene_address, 1);
                Engine_EventShowMessage(1, 0);
            }
        }
    }

    Event_Wait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Engine_EventWait(40);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventWait(10);
    Actor_SetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Event_ShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 3, 0x101, 40);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Actor_FaceActor(20, 14, 40);
    Actor_RunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(20);
    Call3(Engine_ActorShowEmote, 14, 0x105, 70);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_ShowEmote(ACTOR_PARTY_LEADER, 0x101, 0);
    Call3(Engine_ActorShowEmote, 1, 0x101, 0);
    Actor_ShowEmote(ACTOR_MIA, 0x101, 0);
    Value3(Engine_ActorShowEmote, 2, 0x101, 40);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Event_Wait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(20);
    Actor_SetAnimationAndWait(ACTOR_GERALD, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Actor_ShowEmote(ACTOR_IVAN, 0x101, 40);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(40);
    Engine_ActorFaceActor(0, 2, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_IVAN, 0);
    Engine_ActorFaceActor(3, 2, 0);
    Engine_ActorFaceActor(20, 2, 0);
    Event_Wait(50);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(2, 2);
    Event_Wait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Actor_ShowEmote(14, 0x101, 40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, 3);
    Engine_ActorSetAnimation(1, 3);
    Engine_ActorSetAnimationAndWait(3, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(2, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(20);
    Actor_SetAnimationAndWait(20, 3);
    Engine_EventWait(30);
    Engine_ActorFaceActor(20, 14, 30);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Event_Wait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Engine_ActorStartRepeatedMotion(1, 2);
    Engine_ActorStartRepeatedMotion(3, 2);
    Engine_ActorRunRepeatedMotion(2, 2);
    Event_Wait(30);
    Event_Wait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 14, 0x8000, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 0);
    Engine_ActorFaceEachOther(3, 2, 50);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 2, 0xc000, 0);
    Engine_EventWait(40);
    Value3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_EventWait(30);
    Call3(Engine_ActorShowEmote, 14, 0x102, 40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x102, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(20);
    Engine_ActorFaceEachOther(14, 20, 40);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Event_Wait(10);
    Call2(Engine_ActorSetAttachedEffect, 20, 0x102);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Event_ShowMessage(20, 0);
    Actor_SetSpeed(20, 0x19999, 0xcccc);
    Engine_ActorWalkByAndWait(20, 0, 24);
    Engine_ActorFaceActor(0, 20, 0);
    Engine_ActorFaceActor(1, 20, 0);
    Engine_ActorFaceActor(3, 20, 0);
    Engine_ActorFaceActor(2, 20, 0);
    Actor_FaceDirection(14, 0x4000, 0);
    Event_ShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x100, 60);
    Engine_ActorFaceActor(20, 14, 0);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 2, 0xc000, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Event_Wait(30);
    Actor_ShowEmote(14, 0x105, 40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x101, 60);
    Call3(Engine_ActorSetSpeed, 20, 0x13333, 0x9999);
    Call3(Engine_ActorWalkByAndWait, 20, 0, -24);
    Engine_ActorFaceDirection(20, 0, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 14, 0x8000, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x102, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Event_Wait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Value3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 3, 0x102, 40);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(2, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 0);
    Engine_ActorFaceEachOther(3, 2, 50);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 2, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(20);
    Call3(Engine_ActorShowEmote, 0, 0x101, 0);
    Call3(Engine_ActorShowEmote, 1, 0x101, 0);
    Call3(Engine_ActorShowEmote, 3, 0x101, 0);
    Actor_ShowEmote(ACTOR_IVAN, 0x101, 50);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Event_ShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x102, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(14, 20, 30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_SetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Event_Wait(10);
    Engine_ActorRunRepeatedMotion(1, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Value3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x101, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Event_Wait(30);
    Actor_FaceDirection(14, 0x8000, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 2, 0x101, 40);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_ActorFaceDirection(20, 0x2000, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(3, 2);
    Engine_EventWait(20);
    Event_ShowMessage(ACTOR_MIA, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 14, 0x102, 40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(20);
    Engine_ActorSetAnimation(0, 3);
    Engine_ActorSetAnimation(1, 3);
    Engine_ActorSetAnimation(3, 3);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Engine_EventWait(30);
    Engine_EventWait(20);
    Call3(Engine_ActorShowEmote, 14, 0x105, 60);
    Engine_EventShowMessage(14, 0);
    Event_Wait(10);
    Call3(Engine_ActorShowEmote, 1, 0x101, 40);
    Engine_EventShowMessage(1, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 14, 0x100, 40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorFaceEachOther, 1, 0, 50);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 3, 0x101, 40);
    Event_ShowMessage(ACTOR_MIA, 0);
    Engine_EventWait(10);
    Actor_SetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 0, 0x101, 0);
    Actor_ShowEmote(ACTOR_GERALD, 0x101, 0);
    Call3(Engine_ActorShowEmote, 2, 0x101, 0);
    Value3(Engine_ActorShowEmote, 3, 0x101, 40);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 2, 0x100, 40);
    Engine_EventOpenMessage(2, 0);
    if (Engine_EventChooseYesNo(14, 0) == 0) {
        Event_Wait(10);
        Engine_EventShowMessage(2, 0);
        AdvanceMessage(1);
    } else {
        Engine_EventWait(10);
        AdvanceMessage(1);
        Engine_EventShowMessage(2, 0);
    }

    Event_Wait(10);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Event_Wait(10);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Event_Wait(20);
    Engine_ActorFaceDirection(20, 0, 0);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceActor(14, 20, 40);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 40);
    Engine_EventShowMessage(1, 0);
    Actor_FaceDirection(14, 0x4000, 0);
    Value3(Engine_ActorFaceDirection, 20, 0x2000, 0);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Value3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Event_Wait(30);
    Engine_ActorFaceEachOther(3, 2, 60);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Engine_ActorFaceDirection(2, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventShowMessage(3, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(2, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(2, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(20, 14, 60);
    Call3(Engine_ActorFaceDirection, 20, 0x2000, 0);
    Value3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_EventWait(30);
    Engine_ActorFaceDirection(14, 0x4000, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Event_Wait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_RunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventOpenMessage(20, 0);
    if (Engine_EventChooseYesNo(0, 0) == 0) {
        Engine_EventWait(20);
        Call3(Engine_ActorShowEmote, 1, 0x102, 40);
        Engine_EventShowMessage(1, 0);
        AdvanceMessage(1);
    } else {
        Engine_EventWait(10);
        AdvanceMessage(1);
        Engine_EventShowMessage(1, 0);
    }

    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x100, 40);
    Engine_EventShowMessage(20, 0);
    Event_Wait(20);
    Engine_ActorSetAnimation(0, 3);
    Engine_ActorSetAnimation(1, 3);
    Engine_ActorSetAnimation(3, 3);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 14, 0x100, 40);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceActor(20, 14, 40);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x102, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceActor(14, 20, 40);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(20, 0);
    Engine_ActorFaceDirection(14, 0x4000, 0);
    Engine_EventWait(20);
    Engine_ActorRunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Actor_ShowEmote(ACTOR_PARTY_LEADER, 0x101, 80);
    Call3(Engine_ActorShowEmote, 20, 0x102, 70);
    Engine_ActorSetAnimationAndWait(14, 4);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorFaceEachOther(1, 0, 0);
    Engine_ActorFaceEachOther(3, 2, 50);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Engine_ActorFaceDirection(2, 0xc000, 0);
    Engine_EventWait(30);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 20, 0x106, 50);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Actor_FaceDirection(20, 0x2000, 0);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 14, 0x108, 40);
    Engine_EventOpenMessage(14, 0);
    if (Engine_EventChooseYesNo(0, 0) == 0) {
        Event_Wait(20);
        Call3(Engine_ActorShowEmote, 14, 0x100, 40);
        Event_ShowMessage(14, 0);
        AdvanceMessage(1);
    } else {
        Engine_EventWait(10);
        Call3(Engine_ActorShowEmote, 14, 0x100, 40);
        AdvanceMessage(1);
        Event_ShowMessage(14, 0);
    }

    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Engine_EventWait(20);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceActor(14, 20, 40);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorFaceActor(20, 14, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Call3(Engine_ActorShowEmote, 14, 0x100, 40);
    Value3(Engine_ActorFaceDirection, 14, 0x8000, 0);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Event_Wait(10);
    Call3(Engine_ActorShowEmote, 20, 0x100, 40);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Actor_RunRepeatedMotion(14, 2);
    Engine_EventWait(20);
    Engine_EventShowMessage(14, 0);
    Engine_EventWait(10);
    Engine_ActorRunRepeatedMotion(20, 2);
    Event_Wait(20);
    Engine_EventShowMessage(20, 0);
    Engine_EventWait(10);
    Engine_ActorSetAnimationAndWait(20, 3);
    Event_Wait(30);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Engine_ActorFaceDirection(20, 0x2000, 0);
    Engine_EventWait(20);
    Object_LinkObjectAndSetCallbackFar(0, 20);
    Object_LinkObjectAndSetCallbackFar(1, 20);
    Object_LinkObjectAndSetCallbackFar(3, 20);
    Object_LinkObjectAndSetCallbackFar(2, 20);
    Call3(Engine_ActorSetSpeed, 20, 0x10000, 0x8000);
    Engine_ActorWalkByAndWait(20, 0, 32);
    Engine_ActorFaceDirection(20, 0, 0);
    Value3(Engine_ActorFaceDirection, 14, 0x4000, 0);
    Engine_EventWait(20);
    Event_ShowMessage(20, 0);
    Engine_EventWait(10);
    Actor_SetAnimationAndWait(20, 3);
    Engine_EventWait(30);
    Engine_ActorWalkByAndWait(1, 16, 0);
    Engine_ActorWalkBy(20, 0, 80);
    Engine_EventWait(40);
    Actor_WalkByAndWait(ACTOR_GERALD, -16, 0);
    Call3(Engine_ActorFaceDirection, 1, 0x4000, 0);
    Value3(Engine_ActorFaceDirection, 3, 0x4000, 0);
    Actor_WaitForMove(20);
    Engine_EventWait(80);
    Engine_ActorSetPosition(20, 0, 0);
    Call3(Engine_ActorFaceDirection, 0, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 1, 0xc000, 0);
    Call3(Engine_ActorFaceDirection, 3, 0xc000, 0);
    Engine_ActorFaceDirection(2, 0xc000, 0);
    Event_Wait(30);
    Object_LinkObjectAndSetCallbackFar(0, 14);
    Object_LinkObjectAndSetCallbackFar(1, 14);
    Object_LinkObjectAndSetCallbackFar(3, 14);
    Object_LinkObjectAndSetCallbackFar(2, 14);
    Engine_EventWait(30);
    Engine_ActorSetAnimationAndWait(14, 3);
    Engine_EventWait(30);
    Actor_SetSpeed(14, 0xcccc, 0x6666);
    Engine_ActorWalkByAndWait(14, 0, 24);
    Engine_ActorWalkByAndWait(14, -80, 0);
    Engine_EventWait(10);
    Engine_ActorFaceDirection(14, 0, 0);
    Engine_EventWait(20);
    Event_ShowMessage(14, 0);
    Engine_EventWait(20);
    Actor_FaceDirection(14, 0x4000, 0);
    Engine_EventWait(20);
    Actor_WalkByAndWait(14, 0, 48);
    Engine_ActorWalkByAndWait(14, -64, 0);
    Engine_ActorStop(0);
    Actor_Stop(ACTOR_GERALD);
    Engine_ActorStop(3);
    Engine_ActorStop(2);
    Actor_SetPosition(14, 0, 0);
    Engine_EventWait(20);
    Engine_ActorFaceEachOther(0, 3, 0);
    Engine_ActorFaceEachOther(1, 2, 0);
    Engine_EventWait(30);
    Engine_ActorSetAnimation(0, 3);
    Engine_ActorSetAnimation(1, 3);
    Engine_ActorSetAnimation(3, 3);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Engine_EventWait(30);
    Engine_AudioPlayCue(17);
    Call3(Engine_ActorSetSpeed, 1, 0x13333, 0x9999);
    Call3(Engine_ActorSetSpeed, 2, 0x13333, 0x9999);
    Actor_SetSpeed(ACTOR_MIA, 0x13333, 0x9999);
    Engine_ActorSetAnimation(1, 2);
    position = Engine_ActorGet(0);
    if (position != 0)
        ObjectMotion_ResetAndSetPositionFar(1, position[5], position[9]);
    Engine_ActorWaitForMove(1);
    Engine_ActorSetPosition(1, 0, 0);
    Actor_SetAnimation(ACTOR_IVAN, 2);
    position = Actor_Get(ACTOR_PARTY_LEADER);
    if (position != 0)
        ObjectMotion_ResetAndSetPositionFar(2, position[5], position[9]);
    Engine_ActorWaitForMove(2);
    Engine_ActorSetPosition(2, 0, 0);
    Engine_ActorSetAnimation(3, 2);
    position = Engine_ActorGet(0);
    if (position != 0)
        ObjectMotion_ResetAndSetPositionFar(3, position[5], position[9]);
    Engine_ActorWaitForMove(3);
    Engine_ActorSetPosition(3, 0, 0);
    carry = Value1(Engine_EventWait, 10);
    carry = Audio_PlayCueFromEventWorkFar(carry);
    Call1(Engine_EventEnd, carry);
}

void FieldScene_RunScene3b8_02003d40(void)
{
    struct EventWork *work;

    work = (struct EventWork *)gWork[0];
    Event_Begin();
    Audio_PlayCue(158);
    Actor_SetSpeed(ACTOR_PARTY_LEADER, 0x8000, 0x4000);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, 2);
    if (work->touched_trigger == 32) {
        Map_ClearLayerEntryFlagFar(1);
        Event_Wait(10);
        Actor_SetDestinationOffset(ACTOR_PARTY_LEADER, 0, -16);
    } else {
        if (work->touched_trigger == 30) {
            Map_ClearLayerEntryFlagFar(4);
            Event_Wait(10);
            Actor_CenterAndWalk(ACTOR_PARTY_LEADER, 3, -16);
        } else {
            Map_ClearLayerEntryFlagFar(2);
            Event_Wait(10);
            Actor_CenterAndWalk(ACTOR_PARTY_LEADER, 3, -16);
        }
    }
    Event_Wait(16);
    Event_RequestExit(work->touched_trigger);
    Map_SetLayerEntryFlagFar(1);
    Map_SetLayerEntryFlagFar(2);
    Map_SetLayerEntryFlagFar(4);
    Event_End();
}

void RunSceneEffectSetup(void)
{
    Event_Begin();
    Actor_SetSpeed(ACTOR_PARTY_LEADER, 32768, 16384);
    Audio_PlayCue(158);
    Map_AnimateCells(33604944, 36, 10);
    SetSceneEffectOffset(0, 2, -16);
    Event_Wait(16);
    Event_RequestExit(2);
    Event_End();
}
