[workspace]

[package]
name = "late-runtime-residual"
version = "0.1.0"
edition = "2021"

[dependencies]
canonical-json = { path = "../canonical-json" }
late-runtime-data = { path = "../late-runtime-data" }
serde_json = { version = "1", features = ["preserve_order"] }

[[bin]]
name = "late-runtime-residual"
path = "src/main.rs"
