#ifndef ALCHEMY_ABI_UI_RUNTIME_INIT_INIT_COUNTERS_WITH_RESOURCE_AND_SCHEDULE_REFRESH
#define ALCHEMY_ABI_UI_RUNTIME_INIT_INIT_COUNTERS_WITH_RESOURCE_AND_SCHEDULE_REFRESH

/* Binding layer — not production source. Address / far-call ABI only. */

#define gIw Data_03001e8c

#endif
