[workspace]

[package]
name = "compose-scene"
version = "0.1.0"
edition = "2021"

[lib]
name = "compose_scene"
path = "src/lib.rs"

[[bin]]
name = "compose-scene"
path = "src/main.rs"

[dependencies]
alchemy-zlib = { path = "../zlib" }
import-asset = { path = "../import-asset" }
export-asset = { path = "../export-asset" }

[profile.release]
debug = false
