#ifndef ALCHEMY_ABI_BATTLE_EFFECTS_PARTICLES_UPDATE_DESCENDING_POSITIVE_ARC
#define ALCHEMY_ABI_BATTLE_EFFECTS_PARTICLES_UPDATE_DESCENDING_POSITIVE_ARC

/* Binding layer — not production source. Address / far-call ABI only. */

#define gCell Data_02000240

#endif
