/* Draft of resource_3ad 0x02008828..0x020091b8 (2448 bytes with pool),
 * Reunion_Converse; the listing keeps the rows. Remaining difference: the
 * reference loads the first messages of its conversations (0x2516, 0x253f)
 * from its literal pool as link-time values; the integer messages are
 * scheduled differently (2452 bytes, 329 differ from +0xd8). */
#include "../../../../../games/THE BROKEN SEAL/SRC/FIELD/RUNPA_DOU/CAVE.H"

/* Everyone gathers by the cave mouth and talks over how Hammet was saved. */
void Reunion_Converse(void)
{
    s32 reunion;
    s32 plan;

    Event_Begin();
    Actor_SetPosition(ACTOR_GERALD, PIXELS(200), PIXELS(544));
    Actor_SetPosition(ACTOR_PARTY_LEADER, PIXELS(184), PIXELS(544));
    Actor_SetPosition(ACTOR_MIA, PIXELS(168), PIXELS(544));
    Actor_SetPosition(ACTOR_IVAN, PIXELS(212), PIXELS(528));
    Actor_SetPosition(ACTOR_HAMMET, PIXELS(200), PIXELS(512));
    Actor_SetPosition(ACTOR_BUNZA, PIXELS(168), PIXELS(512));
    Actor_FaceDirection(ACTOR_GERALD, FACING_NORTH, 0);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, FACING_NORTH, 0);
    Actor_FaceDirection(ACTOR_MIA, FACING_NORTH, 0);
    Actor_FaceDirection(ACTOR_IVAN, FACING_WEST, 0);
    Actor_FaceDirection(ACTOR_HAMMET, FACING_WEST, 0);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_EAST, 0);
    Actor_SetAnimation(ACTOR_BUNZA, ANIM_STAND);
    Camera_FollowActor(ACTOR_PARTY_LEADER, 0);
    Task_Wait(1);
    Map_Redraw();
    Task_Wait(1);
    Event_OpenScreen();
    Event_WaitForScreen();
    Event_Wait(20);

    Actor_SetAnimationAndWait(ACTOR_IVAN, ANIM_NOD);
    Event_Wait(30);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 2, 70);
    reunion = 0x2516;
    Event_SetMessage(reunion + REUNION_BUNZA_ASKS_ABOUT_RELEASE);
    Event_ShowMessage(ACTOR_BUNZA, 0);
    Actor_SetAnimationAndWait(ACTOR_HAMMET, ANIM_NOD);
    Event_SetMessage(reunion + REUNION_HAMMET_CREDITS_IVAN);
    Event_ShowMessage(ACTOR_HAMMET, 0);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_HAMMET, 0);
    Event_Wait(30);
    Actor_RunRepeatedMotion(ACTOR_IVAN, 1);
    Event_Wait(40);
    Event_SetMessage(reunion + REUNION_IVAN_CREDITS_LEADER);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_IVAN, 0);
    Event_Wait(10);
    Actor_ShowEmote(ACTOR_GERALD, EMOTE_IN_FRONT | 7, 80);
    Event_SetMessage(reunion + REUNION_GERALD_QUESTIONS_IVAN);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_GERALD, 0);
    Actor_ShowEmote(ACTOR_IVAN, EMOTE_IN_FRONT | 0, 70);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_GERALD, 0);
    Event_SetMessage(reunion + REUNION_IVAN_CREDITS_EVERYONE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_FaceDirection(ACTOR_HAMMET, FACING_SOUTH - FACING_STEP, 0);
    Event_Wait(60);
    Actor_FaceDirection(ACTOR_HAMMET, FACING_SOUTH + FACING_STEP, 0);
    Event_Wait(60);
    Event_SetMessage(reunion + REUNION_HAMMET_THANKS_PARTY);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Event_Wait(30);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, ANIM_NOD);
    Actor_SetAnimation(ACTOR_MIA, ANIM_NOD);
    Actor_SetAnimation(ACTOR_GERALD, ANIM_NOD);
    Event_Wait(120);
    Actor_FaceDirection(ACTOR_HAMMET, FACING_SOUTH - FACING_STEP, 0);
    Event_Wait(30);
    Actor_ShowEmote(ACTOR_HAMMET, EMOTE_IN_FRONT | 8, 80);
    Event_SetMessage(reunion + REUNION_HAMMET_THANKS_IVAN);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_HAMMET, 0);
    Actor_ShowEmote(ACTOR_IVAN, EMOTE_IN_FRONT | 8, 60);
    Actor_SetAnimationAndWait(ACTOR_IVAN, ANIM_NOD);
    Event_Wait(30);

    Actor_ShowEmote(ACTOR_MIA, EMOTE_IN_FRONT | 1, 40);
    Actor_FaceActor(ACTOR_MIA, ACTOR_BUNZA, 0);
    Event_SetMessage(reunion + REUNION_MIA_PRAISES_BUNZA);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_MIA, 0);
    Actor_ShowEmote(ACTOR_HAMMET, EMOTE_IN_FRONT | 0, 60);
    Actor_FaceActor(ACTOR_HAMMET, ACTOR_BUNZA, 0);
    Event_SetMessage(reunion + REUNION_HAMMET_PRAISES_BUNZA);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 2, 70);
    Event_SetMessage(reunion + REUNION_BUNZA_CALLS_IT_CHANCE);
    Event_ShowMessage(ACTOR_BUNZA, 0);
    Actor_RunRepeatedMotion(ACTOR_BUNZA, 1);
    Event_Wait(20);
    Event_SetMessage(reunion + REUNION_BUNZA_AVOIDED_LUNPA);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceEachOther(ACTOR_HAMMET, ACTOR_IVAN, 0);
    Event_Wait(60);
    Actor_FaceActor(ACTOR_HAMMET, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_BUNZA, 0);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_SHAKE_HEAD);
    Event_Wait(30);
    Event_SetMessage(reunion + REUNION_BUNZA_KNEW_OF_PRISON);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
    Event_Wait(20);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_BUNZA, 0);
    Event_SetMessage(reunion + REUNION_GERALD_ASKS_WHY_BUNZA_CAME);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_GERALD, 0);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_GERALD, 0);
    Event_Wait(20);
    Event_SetMessage(reunion + REUNION_BUNZA_RECALLS_ADVICE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_MIA, ACTOR_BUNZA, 0);
    Actor_ShowEmote(ACTOR_MIA, EMOTE_IN_FRONT | 1, 70);
    Event_SetMessage(reunion + REUNION_MIA_ASKS_ABOUT_TRADE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_MIA, 0);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_NOD);
    Event_Wait(40);
    Event_SetMessage(reunion + REUNION_BUNZA_MEANS_WISDOM);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_ShowEmote(ACTOR_HAMMET, EMOTE_IN_FRONT | 0, 70);
    Event_SetMessage(reunion + REUNION_HAMMET_ON_APPEARANCES);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_HAMMET, 0);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_NOD);
    Event_Wait(30);
    Event_SetMessage(reunion + REUNION_BUNZA_ON_UNPLEASANT_PLACES);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_SetAnimationAndWait(ACTOR_HAMMET, ANIM_NOD);
    Event_Wait(30);
    Event_SetMessage(reunion + REUNION_HAMMET_ON_SELLING);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 8, 70);
    Actor_StartRepeatedMotion(ACTOR_IVAN, 1);
    Event_Wait(30);
    Event_SetMessage(reunion + REUNION_IVAN_ASKS_ABOUT_SERVING);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_IVAN, 0);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_NOD);
    Event_Wait(30);
    Event_SetMessage(reunion + REUNION_IVAN_ON_FATE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
    Event_SetMessage(reunion + REUNION_GERALD_ASKS_ABOUT_ENTRY);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_GERALD, 0);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH - FACING_STEP, 0);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_SHAKE_HEAD);
    Event_SetMessage(reunion + REUNION_BUNZA_WAS_REFUSED);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_RunRepeatedMotion(ACTOR_MIA, 1);
    Event_SetMessage(reunion + REUNION_MIA_ASKS_WHY_BUNZA_STILL_CAME);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_MIA, 0);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_MIA, 0);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 0, 60);
    Event_SetMessage(reunion + REUNION_BUNZA_MENTIONS_COMMOTION);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceEachOther(ACTOR_IVAN, ACTOR_HAMMET, 0);
    Event_Wait(20);
    Actor_SetAnimationAndWait(ACTOR_IVAN, ANIM_NOD);
    Event_Wait(30);
    Event_SetMessage(reunion + REUNION_IVAN_EXPLAINS_COMMOTION);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_SetAnimationAndWait(ACTOR_HAMMET, ANIM_NOD);
    Actor_FaceActor(ACTOR_HAMMET, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_BUNZA, 0);
    Event_Wait(20);
    Event_SetMessage(reunion + REUNION_BUNZA_LINKS_COMMOTION);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_SetAttachedEffect(ACTOR_BUNZA, EMOTE_IN_FRONT | 2);
    Event_SetMessage(reunion + REUNION_BUNZA_HAD_TO_KNOW);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_BUNZA, 0);
    Event_SetMessage(reunion + REUNION_GERALD_ASKS_ABOUT_CAVE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_GERALD, 0);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 5, 70);
    Actor_SetAnimationAndWait(ACTOR_MIA, ANIM_SHAKE_HEAD);
    Event_SetMessage(reunion + REUNION_MIA_ON_GATE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_MIA, 0);
    Actor_RunRepeatedMotion(ACTOR_BUNZA, 1);
    Event_SetMessage(reunion + REUNION_BUNZA_HID);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_RunRepeatedMotion(ACTOR_BUNZA, 1);
    Event_SetMessage(reunion + REUNION_HAMMET_STARTLED_BUNZA);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Event_Wait(30);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_HAMMET, 0);
    Event_Wait(60);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_SHAKE_HEAD);
    Event_SetMessage(reunion + REUNION_BUNZA_IS_GLAD);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_SetAnimationAndWait(ACTOR_HAMMET, ANIM_NOD);
    Event_Wait(30);

    /* Bunza goes to look out of the cave, then hurries back. */
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH, 0);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 0, 60);
    Actor_SetSpeed(ACTOR_BUNZA, 0x18000, 0xc000);
    Actor_WalkTo(ACTOR_BUNZA, 144, 528);
    Actor_WaitForMove(ACTOR_BUNZA);
    Actor_WalkTo(ACTOR_BUNZA, 168, 560);
    Actor_WaitForMove(ACTOR_BUNZA);
    Event_Wait(60);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH - FACING_STEP, 0);
    Event_Wait(40);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH + FACING_STEP, 0);
    Event_Wait(40);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH - FACING_STEP, 0);
    Event_Wait(40);
    Actor_WalkTo(ACTOR_BUNZA, 144, 528);
    Actor_WaitForMove(ACTOR_BUNZA);
    Actor_WalkTo(ACTOR_BUNZA, 168, 488);
    Event_SetMessage(reunion + REUNION_IVAN_ASKS_WHY);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_WaitForMove(ACTOR_BUNZA);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH - FACING_STEP, 0);
    Actor_SetAnimation(ACTOR_BUNZA, ANIM_STAND);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_SHAKE_HEAD);
    Event_Wait(20);
    Event_SetMessage(reunion + REUNION_BUNZA_WARNS_OF_SEARCH);
    Event_ShowMessage(ACTOR_BUNZA, 0);
    Event_Wait(20);
    Actor_FaceEachOther(ACTOR_GERALD, ACTOR_PARTY_LEADER, 0);
    Event_Wait(60);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, FACING_NORTH, 0);
    Actor_FaceDirection(ACTOR_GERALD, FACING_NORTH, 0);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 2, 60);
    Event_SetMessage(reunion + REUNION_BUNZA_FEARS_CAPTURE);
    Event_ShowMessage(ACTOR_BUNZA, 0);
    Actor_RunRepeatedMotion(ACTOR_MIA, 1);
    Event_SetMessage(reunion + REUNION_MIA_URGES_ESCAPE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_MIA, 0);
    Actor_ShowEmote(ACTOR_IVAN, EMOTE_IN_FRONT | 2, 60);
    Event_SetMessage(reunion + REUNION_IVAN_WANTS_STEALTH);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_PARTY_LEADER, 0);
    Actor_ShowEmote(ACTOR_IVAN, EMOTE_IN_FRONT | 2, 40);
    Event_SetMessage(reunion + REUNION_GERALD_ASKS_TO_FIGHT);
    Event_OpenMessage(SPEAKER_WINDOW_ABOVE | ACTOR_GERALD, 0);
    if (Event_ChooseYesNo(ACTOR_PARTY_LEADER, 0) == 0) {
        Event_SetMessage(reunion + REUNION_BUNZA_DISCOURAGES_FIGHT);
        Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    } else {
        Event_SetMessage(reunion + REUNION_BUNZA_AGREES_NOT_TO_FIGHT);
        Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    }

    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH - FACING_STEP, 0);
    Actor_FaceActor(ACTOR_PARTY_LEADER, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_MIA, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_HAMMET, ACTOR_BUNZA, 0);
    Actor_ShowEmote(ACTOR_HAMMET, EMOTE_IN_FRONT | 1, 60);
    plan = 0x253f;
    Event_SetMessage(plan + PLAN_HAMMET_ASKS_PLAN);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_HAMMET, 0);
    Event_Wait(20);
    Actor_ShowEmote(ACTOR_BUNZA, EMOTE_IN_FRONT | 8, 60);
    Event_SetMessage(plan + PLAN_BUNZA_HAS_WAGON);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_ShowEmote(ACTOR_MIA, EMOTE_IN_FRONT | 1, 60);
    Event_SetMessage(plan + PLAN_MIA_ASKS_ABOUT_WAGON);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_MIA, 0);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_MIA, 0);
    Event_Wait(10);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_NOD);
    Actor_FaceDirection(ACTOR_BUNZA, FACING_SOUTH - FACING_STEP, 0);
    Event_SetMessage(plan + PLAN_BUNZA_OFFERS_RIDE);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_IVAN, ACTOR_BUNZA, 0);
    Event_SetMessage(plan + PLAN_IVAN_DOUBTS_WAGON);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_IVAN, 0);
    Event_Wait(10);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_SHAKE_HEAD);
    Event_SetMessage(plan + PLAN_BUNZA_REASSURES);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceEachOther(ACTOR_PARTY_LEADER, ACTOR_GERALD, 0);
    Event_Wait(60);
    Actor_FaceActor(ACTOR_PARTY_LEADER, ACTOR_BUNZA, 0);
    Actor_FaceActor(ACTOR_GERALD, ACTOR_BUNZA, 0);
    Event_SetMessage(plan + PLAN_GERALD_AGREES);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_GERALD, 0);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_GERALD, 0);
    Actor_SetAnimationAndWait(ACTOR_BUNZA, ANIM_NOD);
    Event_Wait(20);
    Event_SetMessage(plan + PLAN_BUNZA_IS_UNSUSPECTED);
    Event_ShowMessage(SPEAKER_WINDOW_ABOVE | ACTOR_BUNZA, 0);
    Actor_FaceEachOther(ACTOR_HAMMET, ACTOR_IVAN, 0);
    Event_Wait(60);
    Actor_SetAnimation(ACTOR_HAMMET, ANIM_NOD);
    Actor_SetAnimation(ACTOR_IVAN, ANIM_NOD);
    Event_Wait(60);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, ANIM_NOD);
    Actor_SetAnimation(ACTOR_GERALD, ANIM_NOD);
    Actor_SetAnimation(ACTOR_MIA, ANIM_NOD);
    Actor_FaceActor(ACTOR_BUNZA, ACTOR_PARTY_LEADER, 0);
    Actor_SetAnimation(ACTOR_BUNZA, ANIM_NOD);
    Event_Wait(60);
    WagonChoice_Run();
}
