[workspace]

[package]
name = "resource-01c"
version = "0.1.0"
edition = "2021"

[lib]
name = "resource_01c"
path = "src/lib.rs"

[[bin]]
name = "resource-01c"
path = "src/main.rs"

[dependencies]
canonical-json = { path = "../canonical-json" }
export-asset = { path = "../export-asset" }
extract-resource = { path = "../extract-resource" }
import-asset = { path = "../import-asset" }
serde_json = { version = "1", features = ["preserve_order"] }
