[package]
name = "sentou-gamen-data"
version = "0.1.0"
edition = "2021"

[lib]
name = "sentou_gamen_data"
path = "src/lib.rs"

[[bin]]
name = "sentou-gamen-data"
path = "src/main.rs"

[dependencies]
canonical-json = { path = "../canonical-json" }
import-asset = { path = "../import-asset" }
serde_json = { version = "1", features = ["preserve_order"] }

[workspace]
