#include "TYPES.H"
#include "FIELD_EVENT.H"
#include "FIELD_SCENE.H"
#include "OVERLAY_OBJECT.H"
#include "CREATE_CONFIGURED_OVERLAY_OBJECT.H"
#include "AERIE.H"
extern u8 MsgMakyuriGot[];

void RunScene59Sequence(void)
{
    s32 actor9_fixed_y;
    void *actor_one_record;
    void *scene_counter_initial;
    void *scene_counter_initial_alt;
    void *scene_counter_mid_a;
    void *scene_counter_mid_b;
    void *scene_counter_first_a;
    void *scene_counter_first_b;
    void *scene_counter_system_a;
    void *scene_counter_system_b;
    void *scene_counter_later_a;
    void *scene_counter_later_b;
    void *scene_counter_final_a;
    void *scene_counter_final_b;

    Event_Begin();
    FIELD(Actor_Get(9), s8 *, 0x55) = 0;
    Actor_SetPosition(ACTOR_PARTY_LEADER, PIXELS(0x158), PIXELS(0xE0));
    Actor_SetPosition(ACTOR_GERALD, PIXELS(0x148), PIXELS(0xE0));
    Actor_SetPosition(ACTOR_IVAN, PIXELS(0x158), PIXELS(0xE8));
    Actor_SetPosition(ACTOR_MIA, PIXELS(0x148), PIXELS(0xE8));
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xA000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xC000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0xC000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xC000, 0);
    Actor_SetPosition(0x16, PIXELS(0x150), PIXELS(0xB0));
    Actor_SetAnimation(0x16, 9);
    Value2(SetOverlayObjectMode, ((s32)Engine_ActorGet(0x16)), 0);
    Camera_MoveTo(PIXELS(0x150), -1, PIXELS(0xD0), 0);
    Task_Wait(1);
    Map_Redraw();
    Task_Wait(1);
    /* The ROM loads this IWRAM pointer cell before the request store. */
    EVENT_TRANSITION(gWork) = 0x100;
    Event_OpenScreen();
    Event_WaitForScreen();
    Event_Wait(60);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 2);
    Event_Wait(20);
    Actor_FaceDirection(ACTOR_GERALD, 0, 20);
    Call1(Event_SetValue1d8Far, (s32)MsgMakyuriGot);
    Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x8000, 20);
    Actor_SetAnimationAndWait(ACTOR_PARTY_LEADER, 3);
    Event_Wait(20);
    Actor_RunRepeatedMotion(0x16, 2);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x16, 0, 20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xC000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xC000, 20);
    Actor_ShowEmote(ACTOR_IVAN, 0x00000101, 60);
    Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    Actor_RunRepeatedMotion(0x16, 2);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x16, 0, 30);
    Actor_SetPosition(0x18, PIXELS(0x138), PIXELS(0x70));
    Audio_PlayCue(0x120);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_ShowEmote(ACTOR_MIA, 0x100, 60);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 30);
    Audio_PlayCue(0x1D);
    Camera_SetSpeed(0x0000cccc, 0x00001999);
    FIELD(Value0(Battle_GetWorkObject1e0Far), s8 *, 0x55) = 0;
    Camera_MoveTo(PIXELS(0x150), -1, PIXELS(0xA8), 1);
    Event_Wait(20);
    Actor_SetSpeed(0x18, 0x0000cccc, 0x00006666);
    Actor_WalkToAndWait(0x18, 0x158, 0x88);
    Actor_FaceDirection(0x18, 0x5000, 20);
    Camera_WaitForMove();
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 30);
    Camera_MoveTo(PIXELS(0x150), -1, PIXELS(0xB8), 1);
    Actor_WalkToAndWait(0x18, 0x158, 0xA0);
    Actor_WalkToAndWait(0x18, 0x148, 0xA8);
    Actor_WalkToAndWait(0x18, 0x138, 0xB0);
    Actor_FaceDirection(0x18, 0x3000, 20);
    Camera_WaitForMove();
    Actor_SetAnimationAndWait(0x18, 3);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x6000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0x4000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0x8000, 20);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_SetAnimationAndWait(0x18, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_FaceDirection(ACTOR_GERALD, 0x2000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xE000, 60);
    Actor_FaceDirection(0x18, 0xB000, 20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xA000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xC000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xC000, 20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_StartRepeatedMotion(0x18, 2);
    Actor_ShowEmote(0x18, 0x100, 60);
    Actor_FaceDirection(0x18, 0x3000, 20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_ShowEmote(ACTOR_MIA, 0x00000101, 60);
    Actor_SetAnimationAndWait(0x18, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_SetAnimationAndWait(0x18, 3);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_RunRepeatedMotion(ACTOR_MIA, 1);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_WalkToAndWait(0x18, 0x138, 0xB8);
    Actor_FaceDirection(0x18, 0x3000, 20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 2);
    Event_Wait(10);
    Actor_FaceDirection(ACTOR_GERALD, 0, 20);
    Value2(UiText_OpenMessageAtObjectFar, 1, 0);
    if (Event_ChooseYesNo(0, 0) == 0) {
        Actor_RunRepeatedMotion(ACTOR_GERALD, 2);
        Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
        scene_counter_initial = gWork;
        EVENT_MESSAGE(scene_counter_initial) = (u16)(EVENT_MESSAGE(scene_counter_initial) + 1);
    } else {
        scene_counter_initial_alt = gWork;
        EVENT_MESSAGE(scene_counter_initial_alt) = (u16)(EVENT_MESSAGE(scene_counter_initial_alt) + 1);
        Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
        Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    }
    Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    Actor_FaceDirection(ACTOR_GERALD, 0xC000, 20);
    Actor_SetAnimationAndWait(0x18, 3);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_FaceDirection(0x18, 0xD000, 20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_FaceDirection(0x18, 0x3000, 20);
    Actor_SetAnimationAndWait(0x18, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_ShowEmote(ACTOR_MIA, 0x00000101, 60);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_SetAnimationAndWait(0x18, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_FaceDirection(0x18, 0xB000, 20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Event_Wait(10);
    Actor_RunRepeatedMotion(0x18, 2);
    Event_Wait(30);
    Event_ShowMessage(0x18, 0);
    Event_Wait(10);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 2);
    Event_Wait(30);
    Event_ShowMessage(1, 0);
    Event_Wait(10);
    Actor_FaceDirection(0x18, 0x2000, 0);
    Event_Wait(30);
    Actor_SetAnimationAndWait(0x18, 4);
    Event_Wait(20);
    Event_ShowMessage(0x18, 0);
    Event_Wait(20);
    Actor_RunRepeatedMotion(0x18, 2);
    Event_Wait(30);
    Event_ShowMessage(0x18, 0);
    Event_Wait(10);
    Actor_ShowEmote(ACTOR_IVAN, 0x100, 60);
    Event_ShowMessage(2, 0);
    Event_Wait(10);
    Actor_SetAnimationAndWait(0x18, 3);
    Event_Wait(30);
    Event_ShowMessage(0x18, 0);
    Event_Wait(20);
    Actor_RunRepeatedMotion(0x18, 2);
    Event_Wait(30);
    Event_ShowMessage(0x18, 0);
    Event_Wait(10);
    Actor_FaceDirection(0x18, 0x1000, 0);
    Event_Wait(30);
    Actor_ShowEmote(0x18, 0x108, 60);
    Event_Wait(10);
    Actor_RunRepeatedMotion(0x16, 2);
    Event_Wait(30);
    Actor_SetAnimation(0x16, 8);
    Event_Wait(45);
    Actor_SetAnimation(0x16, 1);
    Value2(SetOverlayObjectMode, ((s32)Engine_ActorGet(0x16)), 1);
    Event_Wait(40);
    Actor_ShowEmote(ACTOR_IVAN, 0x102, 60);
    Event_ShowMessage(2, 0);
    Event_Wait(10);
    Actor_FaceDirection(0x16, 0x2000, 0);
    Event_Wait(20);
    Actor_SetAnimationAndWait(0x16, 4);
    Event_Wait(30);
    Event_ShowMessage(0x16, 0);
    Event_Wait(20);
    Actor_FaceDirection(0x18, 0x2000, 0);
    Event_Wait(30);
    Event_ShowMessage(0x18, 0);
    Event_Wait(10);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Event_Wait(30);
    Event_ShowMessage(3, 0);
    Event_Wait(10);
    Call3(Object_LinkPairFar, 0x18, 0x16, 0);
    Event_Wait(35);
    Actor_SetAnimationAndWait(0x16, 3);
    Event_Wait(30);
    Actor_SetAnimationAndWait(0x18, 3);
    Event_Wait(20);
    Actor_WalkToAndWait(0x18, 0x148, 0xB0);
    Actor_FaceDirection(0x18, 0x3000, 20);
    Actor_SetAnimation(0x18, 5);
    Actor_SetAnimation(0x16, 7);
    Event_Wait(20);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
    Event_Wait(20);
    Event_ShowMessage(1, 0);
    Event_Wait(10);
    Actor_ShowEmote(0x18, 0x00000101, 60);
    Value2(UiText_OpenMessageAtObjectFar, 0x18, 0);
    Event_Wait(30);
    Actor_StartRepeatedMotion(ACTOR_GERALD, 2);
    Actor_StartRepeatedMotion(ACTOR_IVAN, 2);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Actor_FaceDirection(ACTOR_GERALD, 0, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0xC000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xE000, 0);
    Event_Wait(20);
    if (Event_ChooseYesNo(0, 0) == 0) {
        Event_Wait(30);
        Event_ShowMessage(0x18, 0);
        scene_counter_first_a = gWork;
        EVENT_MESSAGE(scene_counter_first_a) = (u16)(EVENT_MESSAGE(scene_counter_first_a) + 1);
    } else {
        Event_Wait(30);
        /* This branch needs its own workspace load; stale register contents
         * are not a valid C dependency. */
        scene_counter_first_b = gWork;
        EVENT_MESSAGE(scene_counter_first_b) = (u16)(EVENT_MESSAGE(scene_counter_first_b) + 1);
        Event_ShowMessage(0x18, 0);
    }
    Event_Wait(20);
    Actor_SetAnimationAndWait(0x18, 4);
    Event_Wait(20);
    Actor_FaceDirection(ACTOR_GERALD, 0xC000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xC000, 0);
    Event_Wait(20);
    Event_ShowMessage(0x18, 0);
    Actor_RunRepeatedMotion(0x16, 1);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x16, 0, 20);
    Call0(MakyuriChojo_SinkActorPair);
    Event_Wait(20);
    Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Actor_StartRepeatedMotion(ACTOR_GERALD, 2);
    Actor_StartRepeatedMotion(ACTOR_IVAN, 2);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0, 5);
    Actor_FaceDirection(ACTOR_GERALD, 0xE000, 5);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 5);
    Actor_FaceDirection(ACTOR_MIA, 0x8000, 5);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0xE000, 5);
    Actor_FaceDirection(ACTOR_GERALD, 0xA000, 5);
    Actor_FaceDirection(ACTOR_IVAN, 0x8000, 5);
    Actor_FaceDirection(ACTOR_MIA, 0, 5);
    FIELD(Value0(Battle_GetWorkObject1e0Far), s8 *, 0x55) = 0;
    Camera_MoveTo(PIXELS(0x118), -1, PIXELS(0xE8), 1);
    Camera_WaitForMove();
    Actor_SetChildValue(0x16, 0xF);
    Actor_SetChildValue(0x18, 0xF);
    Actor_SetPosition(0x16, PIXELS(0xF0), PIXELS(0xD0));
    Actor_SetPosition(0x18, PIXELS(0xE8), PIXELS(0xD0));
    Actor_FaceDirection(0x16, 0x5000, 0);
    Actor_FaceDirection(0x18, 0x3000, 0);
    Call0(MakyuriChojo_RiseActorPair);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x8000, 10);
    Actor_FaceDirection(ACTOR_GERALD, 0x8000, 15);
    Actor_FaceDirection(ACTOR_IVAN, 0x8000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0x8000, 20);
    Actor_WalkTo(ACTOR_PARTY_LEADER, 0x148, 0xD0);
    Actor_WalkTo(ACTOR_IVAN, 0x150, 0xE0);
    Actor_WalkToAndWait(ACTOR_GERALD, 0x138, 0xD8);
    Actor_FaceDirection(ACTOR_GERALD, 0x8000, 0);
    Actor_WaitForMove(ACTOR_IVAN);
    Actor_FaceDirection(ACTOR_IVAN, 0x8000, 0);
    Actor_WaitForMove(ACTOR_PARTY_LEADER);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x8000, 30);
    Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_FaceDirection(ACTOR_GERALD, 0x5000, 20);
    Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    Actor_FaceDirection(ACTOR_GERALD, 0x8000, 20);
    Actor_RunRepeatedMotion(ACTOR_IVAN, 1);
    Actor_FaceDirection(ACTOR_IVAN, 0x6000, 20);
    Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_FaceDirection(ACTOR_IVAN, 0x8000, 20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Camera_SetSpeed(0x30000, 0x6000);
    {
        void **scene_system_cell;
        Camera_MoveTo(PIXELS(0x98), -1, PIXELS(0xD8), 1);
        scene_system_cell = (void **)(gCam + 0x164);
        FIELD(scene_system_cell, s32 *, 0xC) = 0x03800000;
        scene_system_cell = (void **)&gCam;
        Map_Redraw();
        Task_Wait(1);
        FIELD(Actor_Get(9), s8 *, 0x55) = 0;
        Actor_SetPosition(9, PIXELS(0x68), PIXELS(0x108));
        actor9_fixed_y = 0xffe00000;
        FIELD(Actor_Get(9), s32 *, 0xC) = actor9_fixed_y;
        FIELD(((s32)Engine_ActorGet(9)), s32 *, 0x3C) = actor9_fixed_y;
        Map_CopyCellsTo(0x1D, 0x4A, 4, 0x4A, 5, 4);
        Actor_SetSpritePriority(0x11, 0);
        Actor_SetSpritePriority(0x12, 0);
        Call0(MakyuriChojo_RaiseCollectedActors);
        Actor_SetSpritePriority(0x11, 1);
        Actor_SetSpritePriority(0x12, 1);
        Camera_WaitForMove();
        Event_Wait(30);
        Actor_FaceDirection(0x18, 0x8000, 20);
        Event_ShowMessageAndWait(0x18, 0, 20);
        Camera_MoveTo(PIXELS(0x118), -1, PIXELS(0xD8), 1);
        Camera_WaitForMove();
        Actor_FaceDirection(0x18, 0x3000, 20);
        Actor_SetAnimation(0x18, 5);
        Event_ShowMessageAndWait(0x18, 0, 20);
        Actor_RunRepeatedMotion(ACTOR_IVAN, 2);
        Event_Wait(20);
        Actor_FaceDirection(ACTOR_IVAN, 0xA000, 20);
        Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
        Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
        Event_Wait(20);
        Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
        Actor_ShowEmote(0x18, 0x00000101, 60);
        Value2(UiText_OpenMessageAtObjectFar, 0x18, 0);
        if (Event_ChooseYesNo(0, 0) == 0) {
            Event_Wait(20);
            Actor_RunRepeatedMotion(0x16, 2);
            Event_Wait(20);
            Event_ShowMessageAndWait(0x16, 0, 20);
            scene_counter_system_a = FIELD(scene_system_cell, void **, 0x4C);
            EVENT_MESSAGE(scene_counter_system_a) = (u16)(EVENT_MESSAGE(scene_counter_system_a) + 1);
        } else {
            scene_counter_system_b = FIELD(scene_system_cell, void **, 0x4C);
            EVENT_MESSAGE(scene_counter_system_b) = (u16)(EVENT_MESSAGE(scene_counter_system_b) + 1);
            Event_Wait(20);
            Event_ShowMessageAndWait(0x16, 0, 20);
        }
    }
    Actor_RunRepeatedMotion(0x18, 2);
    Event_Wait(20);
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_ShowEmote(ACTOR_PARTY_LEADER, 0x00000101, 0);
    Actor_ShowEmote(ACTOR_GERALD, 0x00000101, 0);
    Actor_ShowEmote(ACTOR_IVAN, 0x00000101, 0);
    Actor_ShowEmote(ACTOR_MIA, 0x00000101, 60);
    Value2(UiText_OpenMessageAtObjectFar, 0x18, 0);
    if (Event_ChooseYesNo(0, 0) == 0) {
        Event_Wait(20);
        Actor_RunRepeatedMotion(0x18, 2);
        Event_Wait(20);
        Event_ShowMessageAndWait(0x18, 0, 20);
        scene_counter_mid_a = gWork;
        EVENT_MESSAGE(scene_counter_mid_a) = (u16)(EVENT_MESSAGE(scene_counter_mid_a) + 1);
    } else {
        scene_counter_mid_b = gWork;
        EVENT_MESSAGE(scene_counter_mid_b) = (u16)(EVENT_MESSAGE(scene_counter_mid_b) + 1);
        Event_Wait(20);
        Actor_RunRepeatedMotion(0x18, 1);
        Event_Wait(20);
        Event_ShowMessageAndWait(0x18, 0, 20);
    }
    Event_Wait(20);
    Call0(MakyuriChojo_SinkActorPair);
    Event_Wait(20);
    Camera_MoveTo(PIXELS(0x80), -1, PIXELS(0xC8), 1);
    Camera_WaitForMove();
    Actor_SetAnimation(0x16, 1);
    Actor_SetAnimation(0x18, 1);
    Actor_SetChildValue(0x16, 0xF);
    Actor_SetChildValue(0x18, 0xF);
    Actor_SetPosition(0x16, PIXELS(0x78), PIXELS(0x98));
    Actor_SetPosition(0x18, PIXELS(0x70), PIXELS(0xA0));
    Actor_FaceDirection(0x16, 0x5000, 0);
    Actor_FaceDirection(0x18, 0x3000, 0);
    Call0(MakyuriChojo_RiseActorPair);
    Event_Wait(30);
    Actor_FaceDirection(0x18, 0, 20);
    Value2(UiText_OpenMessageAtObjectFar, 0x18, 0);
    if (Event_ChooseYesNo(0, 0) == 0) {
        Actor_SetAnimationAndWait(0x18, 3);
        Event_Wait(20);
        Event_ShowMessageAndWait(0x18, 0, 20);
        scene_counter_later_a = gWork;
        EVENT_MESSAGE(scene_counter_later_a) = (u16)(EVENT_MESSAGE(scene_counter_later_a) + 1);
    } else {
        scene_counter_later_b = gWork;
        EVENT_MESSAGE(scene_counter_later_b) = (u16)(EVENT_MESSAGE(scene_counter_later_b) + 1);
        Actor_SetAnimationAndWait(0x18, 4);
        Event_Wait(20);
        Event_ShowMessageAndWait(0x18, 0, 20);
    }
    Event_ShowMessageAndWait(0x18, 0, 20);
    Actor_RunRepeatedMotion(0x16, 1);
    Event_Wait(20);
    Actor_FaceDirection(0x16, 0, 20);
    Event_ShowMessageAndWait(0x16, 0, 20);
    Event_Wait(20);
    Actor_FaceDirection(0x18, 0, 20);
    Actor_SetSpritePriority(0x11, 0);
    Actor_SetSpritePriority(0x12, 0);
    Call0(MakyuriChojo_LowerCollectedActors);
    Actor_SetSpritePriority(0x11, 1);
    Actor_SetSpritePriority(0x12, 1);
    Audio_PlayCue(0x11);
    Camera_MoveTo(PIXELS(0x150), -1, PIXELS(0xD8), 1);
    Camera_WaitForMove();
    Actor_SetAnimationAndWait(ACTOR_IVAN, 4);
    Event_Wait(20);
    Call0(Audio_PlayCueFromEventWorkFar);
    Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x4000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0x3000, 22);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 2);
    Event_Wait(10);
    Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    Actor_ShowEmote(ACTOR_MIA, 0x00000105, 60);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_FaceDirection(ACTOR_MIA, 0xA000, 20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_FaceDirection(ACTOR_MIA, 0x8000, 20);
    Actor_SetAnimation(ACTOR_MIA, 0x10);
    FIELD(Actor_Get(ACTOR_MIA), s32 *, 0x18) = (s32) 0xffff0000;
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 40);
    Actor_RunRepeatedMotion(ACTOR_IVAN, 2);
    Event_Wait(20);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 20);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 4);
    Event_Wait(20);
    Value2(UiText_OpenMessageAtObjectFar, 2, 0);
    Actor_SetAnimation(ACTOR_MIA, 1);
    FIELD(Actor_Get(ACTOR_MIA), s32 *, 0x18) = 0x10000;
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x4000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0xE000, 0);
    Actor_FaceDirection(ACTOR_MIA, 0xC000, 20);
    if (Event_ChooseYesNo(0, 0) == 0) {
        Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
        Event_Wait(20);
        Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
        scene_counter_final_a = gWork;
        EVENT_MESSAGE(scene_counter_final_a) = (u16)(EVENT_MESSAGE(scene_counter_final_a) + 1);
    } else {
        scene_counter_final_b = gWork;
        EVENT_MESSAGE(scene_counter_final_b) = (u16)(EVENT_MESSAGE(scene_counter_final_b) + 1);
        Actor_RunRepeatedMotion(ACTOR_IVAN, 2);
        Event_Wait(20);
        Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    }
    Actor_FaceDirection(ACTOR_IVAN, 0x6000, 20);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    Actor_FaceDirection(ACTOR_MIA, 0xE000, 30);
    Actor_FaceDirection(ACTOR_GERALD, 0x2000, 20);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
    Event_Wait(10);
    Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    Actor_FaceDirection(ACTOR_MIA, 0xA000, 20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 3);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_RunRepeatedMotion(ACTOR_MIA, 1);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_ShowEmote(ACTOR_PARTY_LEADER, 0x00000101, 0);
    Actor_ShowEmote(ACTOR_GERALD, 0x00000101, 0);
    Actor_ShowEmote(ACTOR_IVAN, 0x00000101, 60);
    Actor_SetSpeed(ACTOR_MIA, 0x0000cccc, 0x00006666);
    Actor_SetSpeed(ACTOR_GERALD, 0x0000cccc, 0x00006666);
    Actor_WalkToAndWait(ACTOR_MIA, 0x148, 0xD8);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 0);
    actor_one_record = Actor_Get(ACTOR_GERALD);
    FIELD(actor_one_record, u8 *, 0x5A) = (u8)(0xFE & FIELD(actor_one_record, u8 *, 0x5A));
    Actor_WalkTo(ACTOR_GERALD, 0x138, 0xC8);
    Actor_WalkTo(ACTOR_MIA, 0x118, 0xD8);
    Actor_WaitForMove(ACTOR_GERALD);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x6000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0x6000, 0);
    Actor_WaitForMove(ACTOR_MIA);
    Actor_RunRepeatedMotion(ACTOR_MIA, 2);
    Event_Wait(30);
    Actor_FaceDirection(ACTOR_MIA, 0, 20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_RunRepeatedMotion(ACTOR_GERALD, 1);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_GERALD, 0, 20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 3);
    Actor_StartRepeatedMotion(ACTOR_PARTY_LEADER, 2);
    Actor_StartRepeatedMotion(ACTOR_IVAN, 2);
    Actor_StartRepeatedMotion(ACTOR_GERALD, 2);
    Actor_SetAttachedEffect(ACTOR_PARTY_LEADER, 0x102);
    Actor_SetAttachedEffect(ACTOR_GERALD, 0x102);
    Actor_SetAttachedEffect(ACTOR_IVAN, 0x102);
    Event_Wait(60);
    Event_ShowMessageAndWait(ACTOR_IVAN, 0, 20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_FaceDirection(ACTOR_MIA, 0xE000, 20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_FaceDirection(ACTOR_MIA, 0, 20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 4);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 30);
    Actor_FaceDirection(ACTOR_GERALD, 0x2000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0xA000, 20);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, 3);
    Actor_SetAnimation(ACTOR_GERALD, 3);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Event_Wait(30);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x6000, 0);
    Actor_FaceDirection(ACTOR_GERALD, 0x6000, 0);
    Actor_FaceDirection(ACTOR_IVAN, 0x6000, 40);
    Actor_SetAnimation(ACTOR_PARTY_LEADER, 3);
    Actor_SetAnimation(ACTOR_GERALD, 3);
    Actor_SetAnimationAndWait(ACTOR_IVAN, 3);
    Event_Wait(20);
    Actor_SetAnimationAndWait(ACTOR_MIA, 3);
    Event_Wait(20);
    Event_ShowMessageAndWait(ACTOR_MIA, 0, 20);
    Actor_WalkTo(ACTOR_PARTY_LEADER, 0x138, 0xD8);
    Actor_WalkTo(ACTOR_GERALD, 0x138, 0xD8);
    Actor_WalkTo(ACTOR_IVAN, 0x138, 0xD8);
    Actor_WalkTo(ACTOR_MIA, 0x138, 0xD8);
    Actor_WaitForMove(ACTOR_PARTY_LEADER);
    Actor_WaitForMove(ACTOR_GERALD);
    Actor_SetPosition(ACTOR_GERALD, 0, 0);
    Actor_WaitForMove(ACTOR_IVAN);
    Actor_SetPosition(ACTOR_IVAN, 0, 0);
    Actor_WaitForMove(ACTOR_MIA);
    Actor_SetPosition(ACTOR_MIA, 0, 0);
    {
        void **record;
        record = (void **)(gCam + 0x164);
        FIELD(record, s32 *, 0xC) = 0x04000000;
    }
    Map_Redraw();
    Task_Wait(1);
    Map_CopyCellsTo(4, 0x46, 4, 0x4A, 5, 4);
    GameFlag_Set(0x880);
    GameFlag_Set(0x00000881);
    Event_End();
}

void FieldScene_RunScene39d_02002ddc(void)
{
    s32 record;
    u8 *work;

    work = gCam + 0x164;
    Event_Begin();
    *(s32 *)(work + 12) = 0x3800000;
    Map_Redraw();
    Task_Wait(1);
    *(u8 *)(((s32)Engine_ActorGet(9)) + 85) = 0;
    Actor_SetPosition(9, PIXELS(0x68), PIXELS(0x108));
    record = ((s32)Engine_ActorGet(9));
    *(s32 *)(record + 12) = -0x200000;
    record = Actor_Get(9);
    *(s32 *)(record + 60) = -0x200000;
    *(u8 *)(Battle_GetWorkObject1e0Far() + 85) = 0;
    Camera_SetSpeed(0xcccc, 0x1999);
    Camera_MoveTo(PIXELS(0x80), -1, PIXELS(0xB8), 1);
    Camera_WaitForMove();
    Event_Wait(30);
    Map_CopyCellsTo(29, 74, 4, 74, 5, 4);
    Actor_SetSpritePriority(17, 0);
    Actor_SetSpritePriority(18, 0);
    MakyuriChojo_RaiseCollectedActors();
    Actor_SetSpritePriority(17, 1);
    Actor_SetSpritePriority(18, 1);
    Event_Wait(20);
    GameFlag_Set(0x251);
    Event_End();
}

void FieldScene_RunScene39d_02002eb8(void)
{
    u32 i;
    s32 record;

    Event_Begin();
    Actor_SetSpeed(ACTOR_PARTY_LEADER, 0x8000, 0x4000);
    Actor_WalkToAndWait(ACTOR_PARTY_LEADER, 104, 152);
    Actor_FaceDirection(ACTOR_PARTY_LEADER, 0x4000, 60);
    Actor_SetSpritePriority(17, 0);
    Actor_SetSpritePriority(18, 0);
    MakyuriChojo_LowerCollectedActors();
    Camera_MoveTo(-1, -1, -1, 0);
    Event_RequestExit(1);
    Event_End();
}
