@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"08006384.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_08006384
	.thumb_func
	.type	 Func_08006384,function
Func_08006384:
	push	{r5, r6, lr}
	ldr	r1, .L8
	mov	r5, r0
	ldrh	r2, [r1]
	mov	r3, r5
	and	r3, r3, r2
	cmp	r3, r5
	beq	.L3
	mov	r6, r1
.L7:
	mov	r0, #1
	bl	Func_080030f8
	ldrh	r2, [r6]
	mov	r3, r5
	and	r3, r3, r2
	cmp	r3, r5
	bne	.L7
.L3:
	ldr	r3, .L8+4
	ldr	r0, [r3]
	lsl	r0, r0, #26
	lsr	r0, r0, #30
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	Data_03001f64
	.word	Data_04000128
.Lfe1:
	.size	 Func_08006384,.Lfe1-Func_08006384
