@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"08003f04.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_08003f04
	.thumb_func
	.type	 Func_08003f04,function
Func_08003f04:
	push	{r5, lr}
	mov	r4, #0
	cmp	r0, #95
	bhi	.L10
	mov	r1, #128
	ldr	r2, .L11
	mov	r5, #255
	lsl	r1, r1, #2
.L8:
	ldrb	r3, [r2]
	cmp	r3, r0
	bne	.L7
	strb	r5, [r2]
	add	r4, r4, #1
.L7:
	sub	r1, r1, #1
	add	r2, r2, #1
	cmp	r1, #0
	bne	.L8
	cmp	r4, #0
	beq	.L9
.L10:
	mov	r0, #1
	neg	r0, r0
	b	.L2
.L9:
	mov	r0, #0
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	Data_03001810
.Lfe1:
	.size	 Func_08003f04,.Lfe1-Func_08003f04
