@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"08003bb4.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_08003bb4
	.thumb_func
	.type	 Func_08003bb4,function
Func_08003bb4:
	ldr	r3, .L3+4
	mov	r4, #0
	strb	r4, [r3]
	ldr	r2, .L3+8
	ldrh	r3, .L3
	strh	r3, [r2]
	ldr	r2, .L3+12
	ldr	r1, .L3+16
	ldrb	r3, [r2]
	strb	r3, [r1]
	ldr	r3, .L3+20
	strb	r4, [r2]
	strb	r0, [r3]
	ldr	r2, .L3+24
	ldrb	r3, [r3]
	strb	r3, [r2]
	b	.L4
.L5:
	.align	2, 0
.L3:
	.word	62
	.word	Data_03001cd4
	.word	Data_03001cf8
	.word	Data_03001ca8
	.word	Data_03001aec
	.word	Data_03001c98
	.word	Data_03001ac0
.L4:
	bx	lr
.Lfe1:
	.size	 Func_08003bb4,.Lfe1-Func_08003bb4
