@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"0800b9a4.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_0800b9a4
	.thumb_func
	.type	 Func_0800b9a4,function
Func_0800b9a4:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	mov	r7, r1
	cmp	r5, #0
	beq	.L3
	cmp	r7, #3
	bhi	.L3
	lsl	r3, r7, #2
	mov	r6, r3
	add	r6, r6, #40
	ldr	r0, [r5, r6]
	cmp	r0, #0
	beq	.L3
	bl	Func_0800bc48
	mov	r3, #0
	add	r2, r7, #1
	str	r3, [r5, r6]
	mov	r0, #0
	cmp	r2, #3
	bhi	.L5
	lsl	r3, r2, #2
	add	r3, r3, r5
	mov	r1, r3
	add	r1, r1, #40
.L10:
	ldmia	r1!, {r3}
	cmp	r3, #0
	beq	.L9
	add	r0, r0, #1
.L9:
	add	r2, r2, #1
	cmp	r2, #3
	bls	.L10
.L5:
	cmp	r0, #0
	bne	.L3
	mov	r3, r5
	add	r3, r3, #39
	strb	r7, [r3]
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_0800b9a4,.Lfe1-Func_0800b9a4
