@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"08078480.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_08078480
	.thumb_func
	.type	 Func_08078480,function
Func_08078480:
	push	{lr}
	bl	Func_08078414
	ldrb	r3, [r0, #2]
	mov	r2, #0
	cmp	r3, #1
	bne	.L3
	mov	r2, #1
	b	.L4
.L3:
	cmp	r3, #2
	beq	.L6
	cmp	r3, #3
	beq	.L6
	cmp	r3, #4
	beq	.L6
	cmp	r3, #5
	beq	.L6
	cmp	r3, #9
	bne	.L4
.L6:
	mov	r2, #2
.L4:
	mov	r0, r2
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_08078480,.Lfe1-Func_08078480
