@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"08091584.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_08091584
	.thumb_func
	.type	 Func_08091584,function
Func_08091584:
	push	{lr}
	bl	Func_0808ba1c
	mov	r3, r0
	add	r3, r3, #84
	ldrb	r3, [r3]
	cmp	r3, #1
	bne	.L4
	ldr	r0, [r0, #80]
	cmp	r0, #0
	beq	.L4
	ldr	r0, [r0, #40]
	cmp	r0, #0
	bne	.L3
.L4:
	mov	r0, #0
	b	.L2
.L3:
	mov	r3, #0
	ldrsh	r0, [r0, r3]
.L2:
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_08091584,.Lfe1-Func_08091584
