@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"08099920.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_08099920
	.thumb_func
	.type	 Func_08099920,function
Func_08099920:
	push	{r5, r6, r7, lr}
	mov	r6, r0
	ldr	r2, [r6, #12]
	ldr	r3, [r6, #20]
	cmp	r2, r3
	bgt	.L3
	mov	r2, r6
	add	r2, r2, #94
	mov	r3, #2
	strh	r3, [r2]
	ldr	r1, .L10
	bl	Func_08009098
	mov	r5, #0
	mov	r7, #0
	str	r5, [r6, #108]
	b	.L4
.L8:
	mov	r3, #128
	lsl	r3, r3, #8
	mov	r2, r5
	add	r2, r2, #85
	str	r3, [r5, #28]
	str	r3, [r5, #24]
	mov	r3, #2
	strb	r3, [r2]
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r5, #40]
	bl	Func_08004458
	ldr	r3, .L10+4
	add	r0, r0, r3
	str	r0, [r5, #48]
	bl	Func_08004458
	mov	r1, #128
	mov	r2, r0
	lsl	r1, r1, #14
	mov	r0, r5
	bl	Func_08096bec
	mov	r2, r5
	add	r2, r2, #94
	mov	r3, #6
	strh	r3, [r2]
	mov	r0, r5
	ldr	r1, .L10
	bl	Func_08009098
	add	r7, r7, #1
.L4:
	cmp	r7, #2
	bgt	.L3
	ldr	r1, [r6, #8]
	ldr	r2, [r6, #12]
	ldr	r3, [r6, #16]
	mov	r0, #240
	bl	Func_08096c80
	mov	r5, r0
	cmp	r5, #0
	bne	.L8
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	134869168
	.word	78643
.Lfe1:
	.size	 Func_08099920,.Lfe1-Func_08099920
