@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"080b0574.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_080b0574
	.thumb_func
	.type	 Func_080b0574,function
Func_080b0574:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L10
	mov	r2, #224
	ldr	r6, [r3]
	lsl	r2, r2, #2
	add	r7, r6, r2
	ldr	r3, [r7]
	ldrb	r3, [r3, #5]
	add	r2, r2, #36
	mov	sl, r3
	add	r3, r6, r2
	mov	r5, r0
	ldrh	r0, [r3]
	bl	Func_0808a540
	ldr	r2, .L10+4
	add	r3, r6, r2
	mov	r1, #0
	ldrsb	r1, [r3, r1]
	mov	r8, r0
	cmp	r1, #2
	bne	.L3
	ldr	r3, .L10+8
	ldr	r2, .L10+12
	sub	r3, r3, r2
	add	r5, r5, r3
.L3:
	cmp	r1, #0
	bne	.L4
	ldr	r3, .L10+16
	ldr	r2, .L10+12
	sub	r3, r3, r2
	add	r5, r5, r3
.L4:
	mov	r2, #235
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	cmp	r3, #0
	beq	.L5
	ldr	r3, .L10+20
	ldr	r2, .L10+12
	sub	r3, r3, r2
	add	r5, r5, r3
.L5:
	ldr	r2, [r7]
	mov	r3, #13
	strb	r3, [r2, #5]
	bl	Func_08015140
	mov	r2, r8
	lsl	r3, r2, #16
	mov	r2, #34
	orr	r3, r3, r2
	mov	r0, r5
	mov	r1, #5
	mov	r2, #0
	bl	Func_08015038
	b	.L6
.L8:
	mov	r0, #1
	bl	Func_080030f8
.L6:
	bl	Func_08015048
	cmp	r0, #0
	beq	.L8
	mov	r0, #1
	bl	Func_080030f8
	mov	r2, #224
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldr	r3, [r3]
	mov	r2, sl
	strb	r2, [r3, #5]
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	50339628
	.word	937
	.word	Data_00000cc6
	.word	Data_00000c9b
	.word	Data_00000cf1
	.word	Data_00000d4c
.Lfe1:
	.size	 Func_080b0574,.Lfe1-Func_080b0574
