@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"080fa1c8.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_080fa1c8
	.thumb_func
	.type	 Func_080fa1c8,function
Func_080fa1c8:
	ldr	r2, [r1, #64]
	add	r3, r2, #1
	str	r3, [r1, #64]
	ldrb	r3, [r2]
	bx	lr
.Lfe1:
	.size	 Func_080fa1c8,.Lfe1-Func_080fa1c8
