/* Translation unit unit-08093fa0: 0x08093fa0 .. 0x08094154.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/08093fa0.c"
