/* Translation unit unit-080ae9f0: 0x080ae9f0 .. 0x080aea4c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080ae9f0.c"
