/* Translation unit unit-giant-orbitfx: 0x080d4ce8 .. 0x080d5238.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080d4ce8.c"
/* hole: 0x080d5094 stays retained assembly (no C anywhere yet) */
