/* Translation unit unit-08004cb4: 0x08004cb4 .. 0x08004cf0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/08004cb4.c"
