[package]
name = "diff"
version = "0.1.0"
edition = "2021"

[dependencies]
candidate-compiler = { path = "../candidate-compiler" }
serde_json = { version = "1", features = ["preserve_order"] }
serde = { version = "1", features = ["derive"] }
regex = "1"
sha2 = "0.10"
compiler-core = { path = "../compiler-core" }
disassemble = { path = "../disassemble" }

[dev-dependencies]
tempfile = "3"

[lib]
name = "diff"
path = "src/lib.rs"
