/* Translation unit battle-summon: 0x080b7424 .. 0x080b770c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/battle/summon/layout_positions.c"
#include "../../../src/battle/summon/find_available_slot.c"
#include "../main/080b7548.c"
#include "../main/080b75dc.c"
