/* Translation unit unit-080b595c: 0x080b595c .. 0x080b5b16.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/battle/intro/announce_encounter.c"
#include "../../../../src/battle/party/collect_unit_list.c"
/* hole: 0x080b5ad4 stays retained assembly (no C anywhere yet) */
#include "../../../../src/party/reserved_no_op.c"
