/* Translation unit unit-080b3210: 0x080b3210 .. 0x080b386c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/inn/calculate_room_price.c"
#include "../../../../src/inn/check_in.c"
#include "../../../../src/inn/play_sleep_sequence.c"
#include "../main/080b3444.c"
#include "../../../../src/shop/select_use_item.c"
