/* Translation unit unit-080db6c8: 0x080db6c8 .. 0x080dbb9a.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/battle/effects/particle_field/mode_1.c"
#include "../../../../src/battle/effects/particle_field/mode_0.c"
#include "../main/080db6e0.c"
#include "../../../../src/battle/effects/common/spawn_objects.c"
#include "../../../../src/battle/effects/common/no_effect.c"
