/* Translation unit unit-giant-affinefx: 0x080dd9c0 .. 0x080ddde0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080dd9c0.c"
/* hole: 0x080dda3c stays retained assembly (no C anywhere yet) */
/* hole: 0x080ddb34 stays retained assembly (no C anywhere yet) */
