/* Translation unit unit-080f4008: 0x080f4008 .. 0x080f474a.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/unidentified/main/audio/audio_owner_7.c"
#include "../../../../src/camera/scene/reset_defaults.c"
#include "../../../../src/math/multiply_fixed_8_8.c"
#include "../../../../src/math/scale_by_ratio_fixed.c"
#include "../../../../src/math/reciprocal_fixed.c"
#include "../../../../src/graphics/color/scale_rgb555_buffer.c"
/* hole: 0x080f4168 stays retained assembly (no C anywhere yet) */
/* hole: 0x080f4318 stays retained assembly (no C anywhere yet) */
