/* Translation unit unit-080a21b0: 0x080a21b0 .. 0x080a2680.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/menu/draw_page_indicator.c"
#include "../../../../src/render/tilemap/set_flag_rect.c"
/* hole: 0x080a2324 stays retained assembly (no C anywhere yet) */
#include "../../../../src/unidentified/main/ui/ui_owner_18.c"
#include "../../../../src/ui/window/set_bounds.c"
#include "../../../../src/unidentified/main/ui/ui_owner_27.c"
#include "../../../../src/unidentified/main/audio/audio_owner_3.c"
#include "../../../../src/menu/input/cancel_sound_tick.c"
#include "../../../../src/menu/input/reset_cancel_sound.c"
#include "../../../../src/menu/input/ensure_cancel_sound.c"
#include "../../../../src/unidentified/main/graphics/graphics_owner_8.c"
#include "../../../../src/unidentified/main/graphics/graphics_owner_12.c"
#include "../../../../src/unidentified/main/graphics/graphics_owner_5.c"
#include "../main/080a24d0.c"
