/* Translation unit unit-08078e28: 0x08078e28 .. 0x0807905c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/owner/action/add.c"
#include "../../../src/owner/action/check_level_threshold.c"
#include "../../../src/owner/get_record_stride180.c"
#include "../main/08078ee8.c"
#include "../../../src/owner/reserved_no_op_b.c"
#include "../../../src/owner/get_level_threshold.c"
