/* Translation unit unit-080a735c: 0x080a735c .. 0x080a7478.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/psynergy_menu/is_action_restricted.c"
#include "../../../../src/menu/open_character_selector.c"
#include "../main/080a7440.c"
