/* Translation unit unit-080f9ef8: 0x080f9ef8 .. 0x080f9f3c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080f9ef8.c"
