/* Translation unit unit-08077320: 0x08077320 .. 0x08077d38.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/owner/refresh_and_reset_zero.c"
#include "../../../src/trade/get_offer_state.c"
#include "../../../src/party/get_average_level.c"
#include "../main/08077394.c"
#include "../../../src/owner/get_record.c"
#include "../../../src/runtime/memory/copy_bytes_directional.c"
/* hole: 0x08077428 stays retained assembly (no C anywhere yet) */
#include "../../../src/game_flags/refresh_lure_cap.c"
#include "../../../src/runtime/get_build_stamp_time.c"
