/* Translation unit unit-080c0cec: 0x080c0cec .. 0x080c11ec.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080c0cec.c"
#include "../../../src/unidentified/main/battle/battle_owner_33.c"
#include "../../../src/graphics/blend/fade_alpha_out.c"
#include "../../../src/graphics/blend/fade_alpha_in.c"
#include "../../../src/graphics/blend/set_control.c"
/* hole: 0x080c0eb8 stays retained assembly (no C anywhere yet) */
#include "../../../src/unidentified/main/runtime/runtime_owner_215.c"
#include "../../../src/unidentified/main/ui/ui_owner_16.c"
#include "../../../src/battle/presentation/set_actor_record_mode.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_2.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_19.c"
#include "../../../src/graphics/palette/advance_cycle.c"
#include "../../../src/battle/presentation/set_actor_modes.c"
