/* Translation unit unit-080a172c: 0x080a172c .. 0x080a1abe.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/ui/icon/create_with_resource.c"
#include "../../../src/ui/icon/create_with_resource_variant.c"
#include "../../../src/ui/icon/prepare_object.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_86.c"
#include "../../../src/ui/menu/create_cursor.c"
#include "../../../src/psynergy_menu/initialize_entry_objects.c"
#include "../../../src/menu/release_entry_objects.c"
#include "../../../src/unidentified/main/ui/ui_owner_25.c"
#include "../main/080a1a40.c"
