/* Translation unit unit-080bae40: 0x080bae40 .. 0x080bb7c0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080bae40.c"
#include "../../../../src/battle/actor/reset_runtime_fields.c"
#include "../main/080bb65c.c"
