/* Translation unit unit-0808e23c: 0x0808e23c .. 0x0808e9c0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0808e23c.c"
#include "../main/0808e4b4.c"
#include "../../../src/unidentified/main/battle/battle_owner_23.c"
#include "../main/0808e680.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_207.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_135.c"
#include "../../../src/object/motion/snap_to_terrain.c"
