/* Translation unit unit-08095a44: 0x08095a44 .. 0x08096140.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/battle/effects/heavy_impact/finish.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_3.c"
#include "../../../src/unidentified/main/field/field_owner_141.c"
#include "../../../src/unidentified/main/field/field_owner_88.c"
#include "../main/08095c08.c"
#include "../main/08095dd0.c"
#include "../../../src/unidentified/main/field/field_owner_6.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_107.c"
#include "../../../src/battle/effects/particles/update_radial_spread.c"
