/* Translation unit unit-080c0774: 0x080c0774 .. 0x080c08ec.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080c0774.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_10.c"
