/* Translation unit unit-0808e23c: 0x0808e23c .. 0x0808e9c0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0808e23c.c"
#include "../../../src/battle/effects/find_matching_event.c"
#include "../../../src/battle/effects/execute_packed_ability_effect.c"
#include "../../../src/battle/command/execute_selected_action.c"
#include "../../../src/battle/effects/has_matching_event5.c"
#include "../../../src/battle/effects/has_trigger.c"
#include "../../../src/object/motion/snap_to_terrain.c"
