/* Translation unit unit-0801e260: 0x0801e260 .. 0x0801e41a.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/ui/window/clear_tile_attributes_in_rect.c"
#include "../main/0801e318.c"
#include "../../../src/unidentified/main/field/field_owner_36.c"
#include "../../../src/ui/render/reserved_no_op.c"
