/* Translation unit unit-giant-dispatcher: 0x080be378 .. 0x080bf1e8.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080be378.c"
/* hole: 0x080be76c stays retained assembly (no C anywhere yet) */
/* hole: 0x080beb08 stays retained assembly (no C anywhere yet) */
/* hole: 0x080bef88 stays retained assembly (no C anywhere yet) */
