/* Translation unit unit-0808df1c: 0x0808df1c .. 0x0808e14c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0808df1c.c"
#include "../../../src/battle/effects/random_particle/play_cue_and_start_emitter_on_target.c"
#include "../../../src/animation/apply_child_palette.c"
#include "../../../src/battle/runtime/reset_effect_counter.c"
