/* Translation unit unit-080aae14: 0x080aae14 .. 0x080aafb8.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080aae14.c"
#include "../../../../src/unidentified/main/field/field_owner_25.c"
