/* Translation unit unit-080a6794: 0x080a6794 .. 0x080a6a98.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/psynergy_menu/create_entry_grid.c"
#include "../../../../src/psynergy_menu/close_windows.c"
#include "../../../../src/psynergy_menu/draw_psynergy_icons.c"
#include "../main/080a68ec.c"
#include "../../../../src/psynergy_menu/build_page_result.c"
