/* Translation unit unit-080bffb8: 0x080bffb8 .. 0x080c0130.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/battle/presentation/run_mosaic_fade_out.c"
#include "../../../src/graphics/tile/build_sequential_table.c"
#include "../main/080c00d8.c"
