/* Translation unit unit-080b6a60: 0x080b6a60 .. 0x080b6c08.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080b6a60.c"
#include "../../../../src/battle/party/list_present_enemies.c"
#include "../../../../src/battle/party/list_living_units.c"
