/* Translation unit unit-080b7dd0: 0x080b7dd0 .. 0x080b8c1c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/battle/motion/get_battle_object_slot.c"
#include "../../../../src/battle/motion/reset_motion_record_group.c"
#include "../../../../src/battle/motion/reset_battle_object_record_groups.c"
#include "../../../../src/battle/motion/activate_battle_object_slot.c"
#include "../../../../src/unidentified/main/battle/battle_owner_30.c"
#include "../../../../src/unidentified/main/field/field_owner_10.c"
#include "../../../../src/unidentified/main/battle/battle_owner_63.c"
/* hole: 0x080b7f20 stays retained assembly (no C anywhere yet) */
#include "../../../../src/battle/motion/get_motion_record.c"
#include "../../../../src/unidentified/main/battle/battle_owner_26.c"
#include "../../../../src/battle/motion/reset_actor_at_anchor.c"
#include "../../../../src/unidentified/main/battle/battle_owner_5.c"
#include "../../../../src/battle/motion/interpolate_position.c"
#include "../../../../src/battle/motion/set_object_position.c"
#include "../../../../src/battle/motion/reset_object_at_scaled_anchor.c"
/* hole: 0x080b81c8 stays retained assembly (no C anywhere yet) */
#include "../../../../src/battle/motion/apply_variant_motion.c"
#include "../../../../src/battle/motion/approach_target.c"
#include "../../../../src/unidentified/main/battle/battle_owner_65.c"
#include "../../../../src/battle/motion/reserved_no_op.c"
#include "../../../../src/unidentified/main/battle/battle_owner_13.c"
#include "../../../../src/unidentified/main/battle/battle_owner_55.c"
/* hole: 0x080b845c stays retained assembly (no C anywhere yet) */
/* hole: 0x080b84c0 stays retained assembly (no C anywhere yet) */
#include "../../../../src/unidentified/main/field/field_owner_16.c"
#include "../main/080b8574.c"
#include "../../../../src/unidentified/main/field/field_owner_121.c"
#include "../../../../src/battle/presentation/run_action.c"
#include "../../../../src/battle/object/is_valid_id.c"
#include "../../../../src/battle/escape/play_run.c"
#include "../../../../src/unidentified/main/battle/battle_owner_6.c"
#include "../main/080b88d0.c"
#include "../../../../src/unidentified/main/battle/battle_owner_48.c"
