/* Translation unit unit-080a847c: 0x080a847c .. 0x080a8604.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/character_menu/draw_selection_cursor.c"
#include "../../../../src/character_menu/draw_selection_labels.c"
#include "../main/080a8578.c"
