/* Translation unit unit-giant-walker: 0x0800ebec .. 0x0800f2f8.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0800ebec.c"
/* hole: 0x0800ee14 stays retained assembly (no C anywhere yet) */
/* hole: 0x0800f1fa stays retained assembly (no C anywhere yet) */
