/* Translation unit unit-080fb2a4: 0x080fb2a4 .. 0x080fb792.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080fb2a4.c"
#include "../../../../src/audio/music/player/set_volume.c"
#include "../../../../src/audio/music/player/set_pitch.c"
#include "../../../../src/audio/music/player/set_pan.c"
#include "../../../../src/audio/music/track/clear_modulation.c"
#include "../../../../src/audio/music/player/set_modulation_depth.c"
#include "../../../../src/audio/music/player/set_lfo_speed.c"
#include "../../../../src/audio/execute_memory_access_command.c"
#include "../../../../src/audio/music/track/dispatch_extended_command.c"
#include "../../../../src/unidentified/main/battle/battle_owner_52.c"
#include "../../../../src/audio/music/track/read_wave_pointer.c"
#include "../../../../src/audio/music/track/set_tone_type.c"
#include "../../../../src/audio/music/track/set_tone_attack.c"
#include "../../../../src/audio/music/track/set_tone_decay.c"
#include "../../../../src/audio/music/track/set_tone_sustain.c"
#include "../../../../src/audio/music/track/set_tone_release.c"
#include "../../../../src/audio/music/track/set_pseudo_echo_volume.c"
#include "../../../../src/audio/music/track/set_pseudo_echo_length.c"
#include "../../../../src/audio/music/track/set_tone_length.c"
#include "../../../../src/audio/music/track/set_tone_pan_sweep.c"
#include "../../../../src/audio/dummy_callback.c"
