/* Translation unit unit-080970f8: 0x080970f8 .. 0x080974d8.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/battle/effects/setup_object_pair.c"
#include "../../../src/effect_runtime/stop_current_object.c"
#include "../main/08097194.c"
#include "../../../src/field/event_object/initialize.c"
#include "../main/08097384.c"
#include "../../../src/battle/effects/interpolate/prepare.c"
