/* Translation unit unit-0808fe38: 0x0808fe38 .. 0x0808fefc.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0808fe38.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_183.c"
#include "../main/0808fecc.c"
