/* Translation unit unit-080b0894: 0x080b0894 .. 0x080b0aac.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/unidentified/main/runtime/runtime_owner_157.c"
#include "../main/080b08b8.c"
#include "../main/080b0958.c"
#include "../../../../src/shop/set_cursor_position.c"
#include "../main/080b0a20.c"
#include "../../../../src/shop/place_cursor.c"
