/* Translation unit unit-080197b4: 0x080197b4 .. 0x08019aa0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/unidentified/main/runtime/runtime_owner_27.c"
#include "../../../src/ui/render/drain_pending.c"
#include "../main/08019854.c"
#include "../../../src/unidentified/main/field/field_owner_134.c"
#include "../../../src/unidentified/main/graphics/graphics_owner_9.c"
#include "../../../src/ui/render/lookup_named_value.c"
#include "../../../src/unidentified/main/graphics/graphics_owner_3.c"
#include "../../../src/unidentified/main/graphics/graphics_owner_10.c"
#include "../../../src/ui/render/finalize_pending.c"
