/* Translation unit unit-080b6e30: 0x080b6e30 .. 0x080b7738.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/unidentified/main/runtime/runtime_owner_62.c"
#include "../../../../src/unidentified/main/runtime/runtime_owner_156.c"
#include "../../../../src/battle/presentation/spawn_actor_object.c"
#include "../../../../src/unidentified/main/runtime/runtime_owner_55.c"
#include "../../../../recon/en/units/battle-summon.c"
#include "../../../../recon/en/units/battle-summon.c"
#include "../main/080b7548.c"
#include "../main/080b75dc.c"
#include "../../../../src/unidentified/main/battle/battle_owner_49.c"
