/* Translation unit unit-0809a890: 0x0809a890 .. 0x0809b450.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/unidentified/main/field/field_owner_129.c"
#include "../../../src/unidentified/main/field/field_owner_137.c"
#include "../main/0809a8c4.c"
#include "../../../src/battle/effects/radial_camera/update.c"
#include "../../../src/unidentified/main/field/field_owner_79.c"
#include "../main/0809abb4.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_193.c"
#include "../../../src/battle/effects/object_control/pause_object.c"
#include "../../../src/battle/effects/object_control/resume_object.c"
#include "../../../src/battle/effects/filter_object_id.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_209.c"
#include "../main/0809ae64.c"
#include "../../../src/battle/effects/runtime/update_spin_angle.c"
#include "../../../src/battle/effects/runtime/update_descending_object.c"
#include "../../../src/battle/effects/particles/update_radial_launch.c"
#include "../../../src/battle/effects/run_effect15.c"
#include "../../../src/battle/effects/particles/update_descending_positive_arc.c"
#include "../../../src/battle/effects/particles/update_descending_negative_arc.c"
