/* Translation unit unit-080a448c: 0x080a448c .. 0x080a4924.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/inventory_menu/build_command_states.c"
#include "../../../../src/inventory_menu/draw_command_labels.c"
#include "../../../../src/items/classify_use_mode.c"
#include "../../../../src/inventory_menu/maybe_break_selected_item.c"
#include "../../../../src/inventory_menu/open_item_details.c"
#include "../../../../src/menu/select_quantity.c"
