/* Translation unit unit-080b5c08: 0x080b5c08 .. 0x080b5f0c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/battle/placement/update_entries.c"
#include "../../../../src/battle/summon/update_availability.c"
#include "../../../../src/party/update_name_entries.c"
