/* Translation unit unit-0808d394: 0x0808d394 .. 0x0808d9a4.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0808d394.c"
#include "../../../src/game_flags/is_condition_active.c"
#include "../../../src/unidentified/main/script/script_owner_17.c"
#include "../main/0808d48c.c"
#include "../../../src/unidentified/main/battle/battle_owner_68.c"
#include "../../../src/unidentified/main/runtime/runtime_owner_151.c"
#include "../main/0808d5dc.c"
#include "../../../src/unidentified/main/battle/battle_owner_43.c"
#include "../../../src/unidentified/main/audio/audio_owner_9.c"
#include "../../../src/unidentified/main/battle/battle_owner_36.c"
