/* Translation unit unit-08095a44: 0x08095a44 .. 0x08096140.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/battle/effects/heavy_impact/finish.c"
#include "../../../src/battle/effects/objects/set_alternating_words.c"
#include "../../../src/battle/effects/advance_object_field6_with_ramp.c"
#include "../../../src/battle/effects/shrink_object_and_destroy_slow.c"
#include "../main/08095c08.c"
#include "../main/08095dd0.c"
#include "../../../src/battle/effects/shrink_object_and_destroy_fast.c"
#include "../../../src/battle/effects/objects/update_descending_orbit.c"
#include "../../../src/battle/effects/particles/update_radial_spread.c"
