/* Translation unit unit-0808b02c: 0x0808b02c .. 0x0808b158.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/effect_runtime/lookup_by_table_entry.c"
#include "../../../src/battle/effects/apply_lookup_result.c"
#include "../../../src/battle/effects/data/get_weighted_result.c"
#include "../../../src/battle/effects/data/get_phase_result.c"
#include "../main/0808b090.c"
