/* Translation unit unit-080197b4: 0x080197b4 .. 0x08019aa0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/runtime/clear_word_if_set.c"
#include "../../../src/ui/render/drain_pending.c"
#include "../main/08019854.c"
#include "../../../src/ui/runtime/clear_value_name_tables.c"
#include "../../../src/ui/runtime/push_value_slot.c"
#include "../../../src/ui/render/lookup_named_value.c"
#include "../../../src/ui/runtime/check_cancel_by_input.c"
#include "../../../src/ui/runtime/check_cancel_by_mode_input.c"
#include "../../../src/ui/render/finalize_pending.c"
