/* Translation unit unit-0809b588: 0x0809b588 .. 0x0809b86c.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/battle/effects/update_effect16_state.c"
#include "../../../src/battle/effects/particles/update_paired_arc_spawner.c"
#include "../../../src/field/events/show_status_message.c"
#include "../main/0809b698.c"
/* hole: 0x0809b7e4 stays retained assembly (no C anywhere yet) */
#include "../../../src/battle/effects/runtime/update_slot.c"
