/* Translation unit unit-080a3c08: 0x080a3c08 .. 0x080a3eec.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/equipment_menu/update_compatibility_indicators.c"
#include "../../../src/equipment_menu/start_compatibility_indicators.c"
#include "../../../src/inventory_menu/is_special_item_range.c"
#include "../../../src/inventory_menu/draw_message.c"
#include "../../../src/inventory_menu/hide_empty_entry_icons.c"
#include "../../../src/inventory_menu/count_items.c"
#include "../../../src/inventory_menu/get_item_quantity.c"
#include "../main/080a3ddc.c"
#include "../../../src/inventory_menu/draw_item_icons.c"
#include "../../../src/inventory_menu/refresh_owner_items.c"
