/* Translation unit unit-080d9ab8: 0x080d9ab8 .. 0x080da2ac.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/battle/effects/palette_ramp/mode_0.c"
#include "../../../../src/battle/effects/palette_ramp/mode_1.c"
#include "../../../../src/battle/effects/palette_ramp/mode_2.c"
#include "../../../../src/battle/effects/palette_ramp/mode_3.c"
#include "../main/080d9ae8.c"
#include "../../../../src/battle/effects/puff_arc/run.c"
#include "../../../../src/battle/effects/common/build_centered_index_list.c"
