/* Translation unit unit-080983a0: 0x080983a0 .. 0x08098848.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080983a0.c"
#include "../../../../src/battle/effects/scene_transition/reset.c"
#include "../../../../src/battle/effects/burst_particles/run_main_object.c"
#include "../../../../src/battle/effects/burst_particles/run.c"
#include "../main/08098698.c"
