/* Translation unit unit-080b9ec0: 0x080b9ec0 .. 0x080ba6ac.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080b9ec0.c"
#include "../../../src/unidentified/main/field/field_owner_77.c"
#include "../main/080ba2c0.c"
#include "../../../src/battle/run_simple_presentation.c"
