/* Translation unit unit-080b8db8: 0x080b8db8 .. 0x080b9470.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/080b8db8.c"
#include "../../../../src/unidentified/main/battle/battle_owner_19.c"
#include "../../../../src/battle/target/replace_defeated.c"
#include "../../../../src/unidentified/main/graphics/graphics_owner_11.c"
#include "../../../../src/camera/scene/configure.c"
#include "../../../../src/unidentified/main/battle/battle_owner_57.c"
#include "../../../../src/battle/escape/check_success.c"
#include "../main/080b920c.c"
#include "../main/080b9324.c"
