/* Translation unit unit-0808d394: 0x0808d394 .. 0x0808d9a4.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/0808d394.c"
#include "../../../src/game_flags/is_condition_active.c"
#include "../../../src/battle/effects/descriptors/check_kind3_result.c"
#include "../../../src/battle/effects/descriptors/find_matching.c"
#include "../../../src/runtime/dispatch/call_work_block_entry.c"
#include "../../../src/battle/effects/descriptors/find_with_override.c"
#include "../../../src/battle/effects/descriptors/run_action.c"
#include "../../../src/battle/effects/descriptors/run_kind6_action.c"
#include "../../../src/battle/runtime/run_descriptor.c"
#include "../../../src/battle/event/dispatch_input_event.c"
