/* Translation unit unit-08098954: 0x08098954 .. 0x080992f0.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../main/08098954.c"
#include "../../../src/battle/effects/item_break/spawn_mode_3.c"
#include "../../../src/battle/effects/radial_burst/update.c"
#include "../../../src/battle/effects/heavy_impact/spawn.c"
#include "../../../src/unidentified/main/field/field_owner_50.c"
#include "../main/08098cd8.c"
#include "../../../src/battle/effects/orbiting_particles/update_main.c"
#include "../../../src/battle/effects/orbiting_particles/update_fade.c"
#include "../../../src/battle/effects/orbiting_particles/update_orbit_left.c"
#include "../../../src/battle/effects/orbiting_particles/update_orbit_right.c"
#include "../../../src/battle/effects/orbiting_particles/start.c"
#include "../../../src/battle/effects/orbiting_particles/run.c"
