/* Translation unit unit-080994c0: 0x080994c0 .. 0x08099da4.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../src/unidentified/main/field/field_owner_29.c"
#include "../main/080994d0.c"
#include "../../../src/map/events/check_object_tile.c"
#include "../../../src/map/events/run_tile_trigger_sequence.c"
#include "../../../src/unidentified/main/field/field_owner_92.c"
#include "../main/08099838.c"
#include "../../../src/unidentified/main/battle/battle_owner_17.c"
#include "../../../src/unidentified/main/field/field_owner_126.c"
#include "../../../src/unidentified/main/field/field_owner_60.c"
#include "../main/080999f0.c"
#include "../../../src/battle/effects/particles/spawn_falling.c"
