/* Translation unit unit-080cd418: 0x080cd418 .. 0x080cd594.
 * Address-ordered composite; holes stay retained assembly and are listed
 * in the manifest. Generated by tools/unit-scaffold, then maintained by
 * hand: resolve declaration collisions here or in shared headers. */

#include "../../../../src/graphics/registers/apply_window_blend.c"
#include "../../../../src/graphics/registers/apply_bg2_reference.c"
#include "../../../../src/unidentified/main/battle/battle_owner_61.c"
#include "../../../../src/unidentified/main/battle/battle_owner_54.c"
#include "../../../../src/object/group/tick_member_timers.c"
